##################################
# generate/priv.py
#
# Privileged test generation orchestration.
# jcarlin@hmc.edu Jan 2026
# SPDX-License-Identifier: Apache-2.0
##################################

"""Privileged test generation orchestration."""

from pathlib import Path
from random import seed

from testgen.asm.helpers import reproducible_hash
from testgen.data.config import TestConfig
from testgen.data.state import TestData
from testgen.data.test_chunk import TestChunk
from testgen.io.writer import write_test_file
from testgen.priv.registry import (
    get_priv_test_defines,
    get_priv_test_generator,
    get_priv_test_march_extensions,
    get_priv_test_params,
    get_priv_test_required_extensions,
)

# ---------------------------------------------------------------------------
# Testsuites that need file splitting AND the fast trap handler.
# These generate very large bodies (100k+ lines) that would overflow Sail's
# trap signature region if the standard framework handler were used.
# The fast handler itself lives in tests/env/rvtest_trap_handler.h
# (RVTEST_FAST_TRAP_HANDLER) and is enabled per-file with
# `#define RVTEST_USE_FAST_TRAP_HANDLER`; the trap prolog then installs it in
# mtvec/stvec instead of the standard trampolines.
# ---------------------------------------------------------------------------
_SPLIT_TESTSUITES: frozenset[str] = frozenset({"SsstrictSm", "SsstrictS", "SsstrictU"})

# Maximum body lines per generated .S file for split testsuites.
# 8000 lines keeps file count low (~10 files) which minimises per-file startup
# overhead on slower simulators (spike, QEMU).  Each file still completes in
# well under one second on Sail even when every instruction traps.
_LINES_PER_FILE: int = 8000

_SPLIT_FILE_GPR_INIT: list[str] = (
    [
        "",
        "# Re-initialize GPRs at the top of every split Ssstrict file.",
        "# x8 = scratch base (rs1 for load/store sweep); x7,x9-x31 = 0xDEADBEEF",
        "# so accidental loads/stores from non-x8 registers fault rather than silently succeed.",
        "\tli x7, 0xDEADBEEF",
    ]
    + [f"\tmv x{r}, x7" for r in range(9, 32)]
    + ["\tla x8, scratch", "", ""]
)

# GPR init for SsstrictS split files: switch to S-mode then reload all scratch regs.
# RVTEST_GOTO_LOWER_MODE Smode runs from M-mode here, writing a valid M-mode sp
# into the framework save area so RVTEST_CODE_END's epilog can restore it.
_SPLIT_FILE_SMODE_GPR_INIT: list[str] = (
    [
        "",
        "# Switch to S-mode and re-initialize GPRs for this split file.",
        "\tRVTEST_GOTO_LOWER_MODE Smode",
        "\tcsrw    mie, x0",
        "\t# x8 = scratch base (rs1 for load/store sweep); x7,x9-x31 = 0xDEADBEEF",
        "\tli x7, 0xDEADBEEF",
    ]
    + [f"\tmv x{r}, x7" for r in range(9, 32)]
    + ["\tla x8, scratch", "", ""]
)

# GPR init for SsstrictU split files: switch to U-mode then reload all scratch regs.
_SPLIT_FILE_UMODE_GPR_INIT: list[str] = (
    [
        "",
        "# Switch to U-mode and re-initialize GPRs for this split file.",
        "\tRVTEST_GOTO_LOWER_MODE Umode",
        "\t# x8 = scratch base (rs1 for load/store sweep); x7,x9-x31 = 0xDEADBEEF",
        "\tli x7, 0xDEADBEEF",
    ]
    + [f"\tmv x{r}, x7" for r in range(9, 32)]
    + ["\tla x8, scratch", "", ""]
)


def _split_at_blank(lines: list[str], max_lines: int) -> list[list[str]]:
    """Split lines into groups of ≤ max_lines, preferring blank-line boundaries."""
    if not lines:
        return [[]]
    groups: list[list[str]] = []
    start = 0
    while start < len(lines):
        end = min(start + max_lines, len(lines))
        if end == len(lines):
            groups.append(lines[start:])
            break
        # Search backwards up to 20 % of the window for a blank-line cut point
        search_from = max(start, end - max_lines // 5)
        split_at = end
        for i in range(end - 1, search_from - 1, -1):
            if lines[i].strip() == "":
                split_at = i + 1
                break
        groups.append(lines[start:split_at])
        start = split_at
    return groups


def generate_priv_test(testsuite: str, output_test_dir: Path) -> None:
    """
    Generate tests for a privileged testsuite.

    For most testsuites: produces a single SsstrictXx-00.S file (original
    behaviour, generate/priv.py unchanged from the framework default).

    For Ssstrict testsuites (SsstrictSm, SsstrictS, SsstrictU): splits the
    body into multiple ≤ _LINES_PER_FILE-line files and enables the fast
    trap handler (RVTEST_FAST_TRAP_HANDLER in rvtest_trap_handler.h) via
    `#define RVTEST_USE_FAST_TRAP_HANDLER`.  This prevents the standard framework
    trap handler from overflowing the trap-signature region across the
    150k+ traps generated by the CSR and instruction-encoding sweeps.

    Args:
        testsuite: Testsuite name (e.g., \"ExceptionsSm\", \"SsstrictSm\")
        output_test_dir: Base directory to output generated tests
    """
    output_path = output_test_dir / "priv" / testsuite
    output_path.mkdir(parents=True, exist_ok=True)

    test_config = TestConfig(
        xlen=0,
        flen=64,
        testsuite=testsuite,
        E_ext=False,
        # config_dependent=True,
        required_extensions=get_priv_test_required_extensions(testsuite),
        march_extensions=get_priv_test_march_extensions(testsuite),
        extra_params=get_priv_test_params(testsuite),
    )

    test_data = TestData(test_config)
    tc = test_data.begin_test_chunk()

    # Reserve registers for priv tests:
    #   - x0: avoid so desired values are actually loaded into registers
    #   - x1/ra: used as the return address for function calls
    #   - x6, x7, x9: used by the RVTEST_GOTO_LOWER_MODE macro
    #   - x16-x31: ensure the same test can be used for I or E bases
    priv_exclude_regs = [0, 1, 6, 7, 9, *range(16, 32)]
    test_data.int_regs.consume_registers(priv_exclude_regs)
    seed(reproducible_hash(testsuite))

    priv_test_generator = get_priv_test_generator(testsuite)
    body_lines = priv_test_generator(test_data)

    test_data.int_regs.return_registers(priv_exclude_regs)
    tc.code = "\n".join(body_lines)
    test_data.end_test_chunk()

    # Produce actual test file
    extra_defines = [*get_priv_test_defines(testsuite)]

    if testsuite not in _SPLIT_TESTSUITES:
        # ── Standard single-file output (original behaviour) ──────────────────
        write_test_file(test_config, None, [tc], output_path, file_idx=0, extra_defines=extra_defines)
    else:
        # ── Ssstrict: split into multiple files with the fast trap handler ─────
        #
        # Every split file defines RVTEST_USE_FAST_TRAP_HANDLER, which makes
        # RVTEST_CODE_END instantiate RVTEST_FAST_TRAP_HANDLER (see
        # rvtest_trap_handler.h) and the trap prologs install it in
        # mtvec/stvec instead of the standard trampolines.
        #
        # SsstrictSm: all code runs from M-mode.
        #   Each file gets _SPLIT_FILE_GPR_INIT (scratch reload, no mode switch).
        #
        # SsstrictS: all code runs from S-mode; illegal instructions delegated
        #   to S-mode.
        #   Each file gets _SPLIT_FILE_SMODE_GPR_INIT (GOTO Smode + scratch reload).
        #
        # TODO: SsstrictU: all code runs from U-mode; illegal instructions delegated (same as SsstrictS).
        #   Each file gets _SPLIT_FILE_UMODE_GPR_INIT (GOTO Umode + scratch reload).
        extra_defines.append("#define RVTEST_USE_FAST_TRAP_HANDLER")
        if testsuite == "SsstrictS":
            gpr_init = _SPLIT_FILE_SMODE_GPR_INIT
        elif testsuite == "SsstrictU":
            gpr_init = _SPLIT_FILE_UMODE_GPR_INIT
        else:
            gpr_init = _SPLIT_FILE_GPR_INIT

        groups = _split_at_blank(body_lines, _LINES_PER_FILE)
        for file_idx, group in enumerate(groups):
            chunk = TestChunk()
            # Prepend the per-file register init to EVERY file so scratch
            # registers are reloaded at the start of each split body.
            chunk.code = "\n".join(gpr_init + group)
            # Count trap-inducing instructions in this group to size the
            # signature region correctly.  There are two kinds:
            #   1. _cg_ testcase labels — each precedes a CSR instruction that
            #      may trap (illegal CSR access).
            #   2. Raw .word/.hword directives — each IS an illegal instruction
            #      in the reserved-encoding sweeps; every one traps.
            # Each trap writes 4 signature words (mstatus, mcause, mepc, mtval).
            # Counting both kinds ensures that large compressed/vector sweeps
            # (thousands of .hword/.word lines, zero _cg_ labels) don't
            # overflow the signature region and corrupt the TRAP_CANARY.
            cg_count = sum(1 for line in group if line.strip().endswith(":") and "_cg_" in line)
            raw_instr_count = sum(
                1 for line in group if line.strip().startswith(".word ") or line.strip().startswith(".hword ")
            )
            chunk.sigupd_count = 4 * (cg_count + raw_instr_count)
            # Pass a COPY of extra_defines: insert_header_template() calls
            # extra_defines.extend(...) which mutates the list in-place.
            # Without a copy, each successive file accumulates duplicate
            # #define RVTEST_FP / #define rvtest_mtrap_routine lines.
            write_test_file(
                test_config,
                None,
                [chunk],
                output_path,
                file_idx=file_idx,
                extra_defines=extra_defines[:],
            )

    test_data.destroy()
