// --------------------------------------------------------------------------------
// Copyright (C) 2025 Harvey Mudd College & Oklahoma State University, UET Lahore, Habib University
// SPDX-License-Identifier: Apache-2.0
//
// Title           : Comprehensive PMP (Physical Memory Protection) Verification
// Authors         : Umer Shahid, Allen Baum, David Harris
//                  Muhammad Abdullah, Hamza Ali, Muhammad Zain
//
// Description : This test verifies the functionality and enforcement of
//               Physical Memory Protection (PMP) configurations in RISC-V
//               systems. It specifically tests the Read, Write, and Execute
//               permissions for a designated memory region, ensuring that
//               the PMP settings are correctly applied and that the system
//               behaves as expected when accessing this region.
//
// Coverpoints :  cp_tor_boundary for PMPM is partially covered in this test file.
//
// Test Cases  :  Checking doubleword access crossing TOR 4-byte region fails.
//                   With pmpcfg_i.L = 1, pmpcfg_i.A = TOR, pmpcfg_i.XWR = 111,
//                  pmpaddr_i = {lower half of doubleword}, pmpcfg_i-1.A = OFF,
//                  pmpcfg_i-1.XWR=111, pmpaddr_i-1 = pmpaddr_i - 4. Performing
//                  {ld, sd} on doubleword. Should access fault because doubleword
//                  access crosses boundary of word or pass if access is split
//                  into two.

// --------------------------------------------------------------------------------

#define SKIP_MEPC
##### START_TEST_CONFIG #####
# REQUIRED_EXTENSIONS:  ['Sm']
# params:
#   MXLEN: 64
#   NUM_PMP_ENTRIES: '>0'
# MARCH: rv64i_zicsr_zifencei
##### END_TEST_CONFIG #####

// Define the name of this test file for reporting and the size of the signature region
#define TEST_FILE "pmpsm_tor_boundary-01.S"
#define SIGUPD_COUNT 50


// Include framework macros
#include "riscv_arch_test.h"

// Set up test environment and declare main entry point
RVTEST_BEGIN

#define g   (1 << (UDB_PMP_GRANULARITY))

.macro VERIFICATION_RWX ADDRESS TEST_CASE

    LI(a4, DOUBLE_NOP)                                              // Value to write (DOUBLE_NOP)

    LA(a5, (\ADDRESS))                                     // Address to be verified
    \TEST_CASE\()_1:
    sd a4, 0(a5)                                             // Doubleword-level store test
    nop
    RVTEST_SIGUPD(x2, x5, x4, a4, \TEST_CASE\()_1, test_1_str)

    \TEST_CASE\()_2:
    ld a4, 0(a5)                                             // Doubleword-level load test
    nop
    RVTEST_SIGUPD(x2, x5, x4, a4, \TEST_CASE\()_2, test_2_str)

.endm

main:
    // Loop to SET ALL pmpcfg REGs to zero
    .set pmpcfgi, CSR_PMPCFG0
    .rept UDB_NUM_PMP_ENTRIES/8
    csrw pmpcfgi , x0
    .set pmpcfgi, pmpcfgi+2
    .endr

    // Loop to SET ALL pmpaddr REGs to zero
    .set pmpaddri, CSR_PMPADDR0
    .rept UDB_NUM_PMP_ENTRIES
    csrw pmpaddri, x0
    .set pmpaddri, pmpaddri+1
    .endr

#define PMP_REGION_GLOBAL    ((((PMP_L|PMP_R|PMP_W|PMP_X|PMP_NAPOT)&0xFF)   << PMP7_CFG_SHIFT))  // Background region with RWX enable.
#define PMPREGION0_LXWR     ((((PMP_L|PMP_R|PMP_W|PMP_X          )&0xFF)   << PMP0_CFG_SHIFT))
#define PMPREGION1_LXWR     ((((PMP_L|PMP_R|PMP_W|PMP_X|PMP_TOR  )&0xFF)   << PMP1_CFG_SHIFT))

#define PMPADDRESS_TOP_GLOBAL        -1                                                // All memory region
#define REGIONSTART            TEST_FOR_EXECUTION        // RAM_BASE_ADDR + PROGRAM_SIZE

    LA(x4, PMPADDRESS_TOP_GLOBAL)
    csrw     pmpaddr15, x4

    //Lock the Background region.
    LI(x4, PMP_REGION_GLOBAL)
    csrw pmpcfg2, x4

    LA(x4, REGIONSTART)
    srl x4, x4, PMP_SHIFT
    csrw pmpaddr0, x4

    LA(x4, REGIONSTART)
    LI(t0, g)
    add x4, x4, t0
    srl x4, x4, PMP_SHIFT
    csrw pmpaddr1, x4

//                                            Verification Section
// Test Case: 1 -- LXWR Permissions given to the tor Region and accessing double word.

    LI(x4, PMPREGION1_LXWR|PMPREGION0_LXWR)
    csrw pmpcfg0, x4

    VERIFICATION_RWX    TEST_FOR_EXECUTION, test_1

RVTEST_CODE_END
RVTEST_DATA_BEGIN
.align 4

// Test case strings for reporting
test_1_str: .string "\"test: 1; cp: cp_tor_boundary_sd\""
test_2_str: .string "\"test: 2; cp: cp_tor_boundary_ld\""

.align 12
.align (UDB_PMP_GRANULARITY)
TEST_FOR_EXECUTION_0:
    jr ra

TEST_FOR_EXECUTION:
    .rept (1<<(UDB_PMP_GRANULARITY))
    nop
    .endr

RETURN_INSTRUCTION:
    nop
    nop
    jr ra                                                        // Get back to the point from where TEST_FOR_EXECUTION was called.

RVTEST_DATA_END

// Signature region for self-checking
RVTEST_SIG_SETUP
