name: cv32e40p-v2-rv32imc
compiler_exe: riscv64-unknown-elf-gcc
objdump_exe: riscv64-unknown-elf-objdump
ref_model_exe: sail_riscv_sim
udb_config: cv32e40p-v2-rv32imc.yaml
linker_script: link.ld
dut_include_dir: .
