# SPDX-License-Identifier: Apache-2.0
# Jordan Carlin jcarlin@hmc.edu April 2026
# CI configuration for CORE-V Wally (CVW)
# Requires Verilator and the CVW repository

# SsstrictSm excluded because of Sail bug (incorrect decoding of add.uw instruction)
# Sail Issue Link: https://github.com/riscv/sail-riscv/issues/1711
ci_enabled: true
exclude_extensions: "Sm,SsstrictSm,SsstrictS,SsstrictU,InterruptsS,InterruptsU,InterruptsSstc,ExceptionsZalrsc,ExceptionsZaamo,ExceptionsSvZalrsc,ExceptionsSvZaamo,Sv,Svpbmt,Zicsr"
apt_packages: "autoconf flex bison help2man libfl-dev ccache"
install_script: ".github/scripts/install-cvw.sh"
setup_script: ".github/scripts/setup-cvw.sh"
