# SPDX-License-Identifier: Apache-2.0
# Jordan Carlin jcarlin@hmc.edu April 2026
# CI configuration for Spike simulator
# Shared across all Spike configs

# SsstrictSm, SsstrictS, SsstrictU excluded because of Sail bugs and not all instructions in spike-max supported by Sail
# 1. incorrect decoding of add.uw instruction) Link: https://github.com/riscv/sail-riscv/issues/1711
# 2. vmv<nr>r.v instructions fail to trap when vill=1 Link: https://github.com/riscv/sail-riscv/issues/1709
# 3. Add configuration parameter for vsetvli/vsetvl behavior on reserved vtype values Link: https://github.com/riscv/sail-riscv/issues/1699
# 4. Spike mtval reports cache-block-aligned address on CBO access fault instead of faulting virtual address, Link: https://github.com/riscv-software-src/riscv-isa-sim/issues/2296
ci_enabled: true
# TODO: Priv tests mismatch due to config issues. Atomics failure still needs to be diagnosed.
# TODO: Remove Zama16b when spike starts supporting it.
# TODO: Remove SsstrictV when sail SsstrictV is implemented
# Smstateen will be added back once sail starts supporting Sscsrind too
exclude_extensions: "Sm,SsstrictSm,SsstrictS,SsstrictU,ExceptionsZaamo,ExceptionsZicboS,ExceptionsZicboU,PMPSm,Zama16b,SsstrictV,Smstateen"
install_script: ".github/scripts/install-spike.sh"
apt_packages: "device-tree-compiler libboost-regex-dev libboost-system-dev"
