///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    ExceptionsVf16_vfadd_vf_cg = new(); ExceptionsVf16_vfadd_vf_cg.set_inst_name("obj_ExceptionsVf16_vfadd_vf");
    ExceptionsVf16_vfadd_vv_cg = new(); ExceptionsVf16_vfadd_vv_cg.set_inst_name("obj_ExceptionsVf16_vfadd_vv");
    ExceptionsVf16_vfclass_v_cg = new(); ExceptionsVf16_vfclass_v_cg.set_inst_name("obj_ExceptionsVf16_vfclass_v");
    ExceptionsVf16_vfcvt_f_x_v_cg = new(); ExceptionsVf16_vfcvt_f_x_v_cg.set_inst_name("obj_ExceptionsVf16_vfcvt_f_x_v");
    ExceptionsVf16_vfcvt_f_xu_v_cg = new(); ExceptionsVf16_vfcvt_f_xu_v_cg.set_inst_name("obj_ExceptionsVf16_vfcvt_f_xu_v");
    ExceptionsVf16_vfcvt_rtz_x_f_v_cg = new(); ExceptionsVf16_vfcvt_rtz_x_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfcvt_rtz_x_f_v");
    ExceptionsVf16_vfcvt_rtz_xu_f_v_cg = new(); ExceptionsVf16_vfcvt_rtz_xu_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfcvt_rtz_xu_f_v");
    ExceptionsVf16_vfcvt_x_f_v_cg = new(); ExceptionsVf16_vfcvt_x_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfcvt_x_f_v");
    ExceptionsVf16_vfcvt_xu_f_v_cg = new(); ExceptionsVf16_vfcvt_xu_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfcvt_xu_f_v");
    ExceptionsVf16_vfdiv_vf_cg = new(); ExceptionsVf16_vfdiv_vf_cg.set_inst_name("obj_ExceptionsVf16_vfdiv_vf");
    ExceptionsVf16_vfdiv_vv_cg = new(); ExceptionsVf16_vfdiv_vv_cg.set_inst_name("obj_ExceptionsVf16_vfdiv_vv");
    ExceptionsVf16_vfmacc_vf_cg = new(); ExceptionsVf16_vfmacc_vf_cg.set_inst_name("obj_ExceptionsVf16_vfmacc_vf");
    ExceptionsVf16_vfmacc_vv_cg = new(); ExceptionsVf16_vfmacc_vv_cg.set_inst_name("obj_ExceptionsVf16_vfmacc_vv");
    ExceptionsVf16_vfmadd_vf_cg = new(); ExceptionsVf16_vfmadd_vf_cg.set_inst_name("obj_ExceptionsVf16_vfmadd_vf");
    ExceptionsVf16_vfmadd_vv_cg = new(); ExceptionsVf16_vfmadd_vv_cg.set_inst_name("obj_ExceptionsVf16_vfmadd_vv");
    ExceptionsVf16_vfmax_vf_cg = new(); ExceptionsVf16_vfmax_vf_cg.set_inst_name("obj_ExceptionsVf16_vfmax_vf");
    ExceptionsVf16_vfmax_vv_cg = new(); ExceptionsVf16_vfmax_vv_cg.set_inst_name("obj_ExceptionsVf16_vfmax_vv");
    ExceptionsVf16_vfmerge_vfm_cg = new(); ExceptionsVf16_vfmerge_vfm_cg.set_inst_name("obj_ExceptionsVf16_vfmerge_vfm");
    ExceptionsVf16_vfmin_vf_cg = new(); ExceptionsVf16_vfmin_vf_cg.set_inst_name("obj_ExceptionsVf16_vfmin_vf");
    ExceptionsVf16_vfmin_vv_cg = new(); ExceptionsVf16_vfmin_vv_cg.set_inst_name("obj_ExceptionsVf16_vfmin_vv");
    ExceptionsVf16_vfmsac_vf_cg = new(); ExceptionsVf16_vfmsac_vf_cg.set_inst_name("obj_ExceptionsVf16_vfmsac_vf");
    ExceptionsVf16_vfmsac_vv_cg = new(); ExceptionsVf16_vfmsac_vv_cg.set_inst_name("obj_ExceptionsVf16_vfmsac_vv");
    ExceptionsVf16_vfmsub_vf_cg = new(); ExceptionsVf16_vfmsub_vf_cg.set_inst_name("obj_ExceptionsVf16_vfmsub_vf");
    ExceptionsVf16_vfmsub_vv_cg = new(); ExceptionsVf16_vfmsub_vv_cg.set_inst_name("obj_ExceptionsVf16_vfmsub_vv");
    ExceptionsVf16_vfmul_vf_cg = new(); ExceptionsVf16_vfmul_vf_cg.set_inst_name("obj_ExceptionsVf16_vfmul_vf");
    ExceptionsVf16_vfmul_vv_cg = new(); ExceptionsVf16_vfmul_vv_cg.set_inst_name("obj_ExceptionsVf16_vfmul_vv");
    ExceptionsVf16_vfmv_f_s_cg = new(); ExceptionsVf16_vfmv_f_s_cg.set_inst_name("obj_ExceptionsVf16_vfmv_f_s");
    ExceptionsVf16_vfmv_s_f_cg = new(); ExceptionsVf16_vfmv_s_f_cg.set_inst_name("obj_ExceptionsVf16_vfmv_s_f");
    ExceptionsVf16_vfmv_v_f_cg = new(); ExceptionsVf16_vfmv_v_f_cg.set_inst_name("obj_ExceptionsVf16_vfmv_v_f");
    ExceptionsVf16_vfncvt_f_x_w_cg = new(); ExceptionsVf16_vfncvt_f_x_w_cg.set_inst_name("obj_ExceptionsVf16_vfncvt_f_x_w");
    ExceptionsVf16_vfncvt_f_xu_w_cg = new(); ExceptionsVf16_vfncvt_f_xu_w_cg.set_inst_name("obj_ExceptionsVf16_vfncvt_f_xu_w");
    ExceptionsVf16_vfncvt_rod_f_f_w_cg = new(); ExceptionsVf16_vfncvt_rod_f_f_w_cg.set_inst_name("obj_ExceptionsVf16_vfncvt_rod_f_f_w");
    ExceptionsVf16_vfncvt_rtz_x_f_w_cg = new(); ExceptionsVf16_vfncvt_rtz_x_f_w_cg.set_inst_name("obj_ExceptionsVf16_vfncvt_rtz_x_f_w");
    ExceptionsVf16_vfncvt_rtz_xu_f_w_cg = new(); ExceptionsVf16_vfncvt_rtz_xu_f_w_cg.set_inst_name("obj_ExceptionsVf16_vfncvt_rtz_xu_f_w");
    ExceptionsVf16_vfncvt_x_f_w_cg = new(); ExceptionsVf16_vfncvt_x_f_w_cg.set_inst_name("obj_ExceptionsVf16_vfncvt_x_f_w");
    ExceptionsVf16_vfncvt_xu_f_w_cg = new(); ExceptionsVf16_vfncvt_xu_f_w_cg.set_inst_name("obj_ExceptionsVf16_vfncvt_xu_f_w");
    ExceptionsVf16_vfnmacc_vf_cg = new(); ExceptionsVf16_vfnmacc_vf_cg.set_inst_name("obj_ExceptionsVf16_vfnmacc_vf");
    ExceptionsVf16_vfnmacc_vv_cg = new(); ExceptionsVf16_vfnmacc_vv_cg.set_inst_name("obj_ExceptionsVf16_vfnmacc_vv");
    ExceptionsVf16_vfnmadd_vf_cg = new(); ExceptionsVf16_vfnmadd_vf_cg.set_inst_name("obj_ExceptionsVf16_vfnmadd_vf");
    ExceptionsVf16_vfnmadd_vv_cg = new(); ExceptionsVf16_vfnmadd_vv_cg.set_inst_name("obj_ExceptionsVf16_vfnmadd_vv");
    ExceptionsVf16_vfnmsac_vf_cg = new(); ExceptionsVf16_vfnmsac_vf_cg.set_inst_name("obj_ExceptionsVf16_vfnmsac_vf");
    ExceptionsVf16_vfnmsac_vv_cg = new(); ExceptionsVf16_vfnmsac_vv_cg.set_inst_name("obj_ExceptionsVf16_vfnmsac_vv");
    ExceptionsVf16_vfnmsub_vf_cg = new(); ExceptionsVf16_vfnmsub_vf_cg.set_inst_name("obj_ExceptionsVf16_vfnmsub_vf");
    ExceptionsVf16_vfnmsub_vv_cg = new(); ExceptionsVf16_vfnmsub_vv_cg.set_inst_name("obj_ExceptionsVf16_vfnmsub_vv");
    ExceptionsVf16_vfrdiv_vf_cg = new(); ExceptionsVf16_vfrdiv_vf_cg.set_inst_name("obj_ExceptionsVf16_vfrdiv_vf");
    ExceptionsVf16_vfrec7_v_cg = new(); ExceptionsVf16_vfrec7_v_cg.set_inst_name("obj_ExceptionsVf16_vfrec7_v");
    ExceptionsVf16_vfredmax_vs_cg = new(); ExceptionsVf16_vfredmax_vs_cg.set_inst_name("obj_ExceptionsVf16_vfredmax_vs");
    ExceptionsVf16_vfredmin_vs_cg = new(); ExceptionsVf16_vfredmin_vs_cg.set_inst_name("obj_ExceptionsVf16_vfredmin_vs");
    ExceptionsVf16_vfredosum_vs_cg = new(); ExceptionsVf16_vfredosum_vs_cg.set_inst_name("obj_ExceptionsVf16_vfredosum_vs");
    ExceptionsVf16_vfredusum_vs_cg = new(); ExceptionsVf16_vfredusum_vs_cg.set_inst_name("obj_ExceptionsVf16_vfredusum_vs");
    ExceptionsVf16_vfrsqrt7_v_cg = new(); ExceptionsVf16_vfrsqrt7_v_cg.set_inst_name("obj_ExceptionsVf16_vfrsqrt7_v");
    ExceptionsVf16_vfrsub_vf_cg = new(); ExceptionsVf16_vfrsub_vf_cg.set_inst_name("obj_ExceptionsVf16_vfrsub_vf");
    ExceptionsVf16_vfsgnj_vf_cg = new(); ExceptionsVf16_vfsgnj_vf_cg.set_inst_name("obj_ExceptionsVf16_vfsgnj_vf");
    ExceptionsVf16_vfsgnj_vv_cg = new(); ExceptionsVf16_vfsgnj_vv_cg.set_inst_name("obj_ExceptionsVf16_vfsgnj_vv");
    ExceptionsVf16_vfsgnjn_vf_cg = new(); ExceptionsVf16_vfsgnjn_vf_cg.set_inst_name("obj_ExceptionsVf16_vfsgnjn_vf");
    ExceptionsVf16_vfsgnjn_vv_cg = new(); ExceptionsVf16_vfsgnjn_vv_cg.set_inst_name("obj_ExceptionsVf16_vfsgnjn_vv");
    ExceptionsVf16_vfsgnjx_vf_cg = new(); ExceptionsVf16_vfsgnjx_vf_cg.set_inst_name("obj_ExceptionsVf16_vfsgnjx_vf");
    ExceptionsVf16_vfsgnjx_vv_cg = new(); ExceptionsVf16_vfsgnjx_vv_cg.set_inst_name("obj_ExceptionsVf16_vfsgnjx_vv");
    ExceptionsVf16_vfslide1down_vf_cg = new(); ExceptionsVf16_vfslide1down_vf_cg.set_inst_name("obj_ExceptionsVf16_vfslide1down_vf");
    ExceptionsVf16_vfslide1up_vf_cg = new(); ExceptionsVf16_vfslide1up_vf_cg.set_inst_name("obj_ExceptionsVf16_vfslide1up_vf");
    ExceptionsVf16_vfsqrt_v_cg = new(); ExceptionsVf16_vfsqrt_v_cg.set_inst_name("obj_ExceptionsVf16_vfsqrt_v");
    ExceptionsVf16_vfsub_vf_cg = new(); ExceptionsVf16_vfsub_vf_cg.set_inst_name("obj_ExceptionsVf16_vfsub_vf");
    ExceptionsVf16_vfsub_vv_cg = new(); ExceptionsVf16_vfsub_vv_cg.set_inst_name("obj_ExceptionsVf16_vfsub_vv");
    ExceptionsVf16_vfwadd_vf_cg = new(); ExceptionsVf16_vfwadd_vf_cg.set_inst_name("obj_ExceptionsVf16_vfwadd_vf");
    ExceptionsVf16_vfwadd_vv_cg = new(); ExceptionsVf16_vfwadd_vv_cg.set_inst_name("obj_ExceptionsVf16_vfwadd_vv");
    ExceptionsVf16_vfwadd_wf_cg = new(); ExceptionsVf16_vfwadd_wf_cg.set_inst_name("obj_ExceptionsVf16_vfwadd_wf");
    ExceptionsVf16_vfwadd_wv_cg = new(); ExceptionsVf16_vfwadd_wv_cg.set_inst_name("obj_ExceptionsVf16_vfwadd_wv");
    ExceptionsVf16_vfwcvt_f_f_v_cg = new(); ExceptionsVf16_vfwcvt_f_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfwcvt_f_f_v");
    ExceptionsVf16_vfwcvt_f_x_v_cg = new(); ExceptionsVf16_vfwcvt_f_x_v_cg.set_inst_name("obj_ExceptionsVf16_vfwcvt_f_x_v");
    ExceptionsVf16_vfwcvt_f_xu_v_cg = new(); ExceptionsVf16_vfwcvt_f_xu_v_cg.set_inst_name("obj_ExceptionsVf16_vfwcvt_f_xu_v");
    ExceptionsVf16_vfwcvt_rtz_x_f_v_cg = new(); ExceptionsVf16_vfwcvt_rtz_x_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfwcvt_rtz_x_f_v");
    ExceptionsVf16_vfwcvt_rtz_xu_f_v_cg = new(); ExceptionsVf16_vfwcvt_rtz_xu_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfwcvt_rtz_xu_f_v");
    ExceptionsVf16_vfwcvt_x_f_v_cg = new(); ExceptionsVf16_vfwcvt_x_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfwcvt_x_f_v");
    ExceptionsVf16_vfwcvt_xu_f_v_cg = new(); ExceptionsVf16_vfwcvt_xu_f_v_cg.set_inst_name("obj_ExceptionsVf16_vfwcvt_xu_f_v");
    ExceptionsVf16_vfwmacc_vf_cg = new(); ExceptionsVf16_vfwmacc_vf_cg.set_inst_name("obj_ExceptionsVf16_vfwmacc_vf");
    ExceptionsVf16_vfwmacc_vv_cg = new(); ExceptionsVf16_vfwmacc_vv_cg.set_inst_name("obj_ExceptionsVf16_vfwmacc_vv");
    ExceptionsVf16_vfwmsac_vf_cg = new(); ExceptionsVf16_vfwmsac_vf_cg.set_inst_name("obj_ExceptionsVf16_vfwmsac_vf");
    ExceptionsVf16_vfwmsac_vv_cg = new(); ExceptionsVf16_vfwmsac_vv_cg.set_inst_name("obj_ExceptionsVf16_vfwmsac_vv");
    ExceptionsVf16_vfwmul_vf_cg = new(); ExceptionsVf16_vfwmul_vf_cg.set_inst_name("obj_ExceptionsVf16_vfwmul_vf");
    ExceptionsVf16_vfwmul_vv_cg = new(); ExceptionsVf16_vfwmul_vv_cg.set_inst_name("obj_ExceptionsVf16_vfwmul_vv");
    ExceptionsVf16_vfwnmacc_vf_cg = new(); ExceptionsVf16_vfwnmacc_vf_cg.set_inst_name("obj_ExceptionsVf16_vfwnmacc_vf");
    ExceptionsVf16_vfwnmacc_vv_cg = new(); ExceptionsVf16_vfwnmacc_vv_cg.set_inst_name("obj_ExceptionsVf16_vfwnmacc_vv");
    ExceptionsVf16_vfwnmsac_vf_cg = new(); ExceptionsVf16_vfwnmsac_vf_cg.set_inst_name("obj_ExceptionsVf16_vfwnmsac_vf");
    ExceptionsVf16_vfwnmsac_vv_cg = new(); ExceptionsVf16_vfwnmsac_vv_cg.set_inst_name("obj_ExceptionsVf16_vfwnmsac_vv");
    ExceptionsVf16_vfwredosum_vs_cg = new(); ExceptionsVf16_vfwredosum_vs_cg.set_inst_name("obj_ExceptionsVf16_vfwredosum_vs");
    ExceptionsVf16_vfwredusum_vs_cg = new(); ExceptionsVf16_vfwredusum_vs_cg.set_inst_name("obj_ExceptionsVf16_vfwredusum_vs");
    ExceptionsVf16_vfwsub_vf_cg = new(); ExceptionsVf16_vfwsub_vf_cg.set_inst_name("obj_ExceptionsVf16_vfwsub_vf");
    ExceptionsVf16_vfwsub_vv_cg = new(); ExceptionsVf16_vfwsub_vv_cg.set_inst_name("obj_ExceptionsVf16_vfwsub_vv");
    ExceptionsVf16_vfwsub_wf_cg = new(); ExceptionsVf16_vfwsub_wf_cg.set_inst_name("obj_ExceptionsVf16_vfwsub_wf");
    ExceptionsVf16_vfwsub_wv_cg = new(); ExceptionsVf16_vfwsub_wv_cg.set_inst_name("obj_ExceptionsVf16_vfwsub_wv");
    ExceptionsVf16_vmfeq_vf_cg = new(); ExceptionsVf16_vmfeq_vf_cg.set_inst_name("obj_ExceptionsVf16_vmfeq_vf");
    ExceptionsVf16_vmfeq_vv_cg = new(); ExceptionsVf16_vmfeq_vv_cg.set_inst_name("obj_ExceptionsVf16_vmfeq_vv");
    ExceptionsVf16_vmfge_vf_cg = new(); ExceptionsVf16_vmfge_vf_cg.set_inst_name("obj_ExceptionsVf16_vmfge_vf");
    ExceptionsVf16_vmfgt_vf_cg = new(); ExceptionsVf16_vmfgt_vf_cg.set_inst_name("obj_ExceptionsVf16_vmfgt_vf");
    ExceptionsVf16_vmfle_vf_cg = new(); ExceptionsVf16_vmfle_vf_cg.set_inst_name("obj_ExceptionsVf16_vmfle_vf");
    ExceptionsVf16_vmfle_vv_cg = new(); ExceptionsVf16_vmfle_vv_cg.set_inst_name("obj_ExceptionsVf16_vmfle_vv");
    ExceptionsVf16_vmflt_vf_cg = new(); ExceptionsVf16_vmflt_vf_cg.set_inst_name("obj_ExceptionsVf16_vmflt_vf");
    ExceptionsVf16_vmflt_vv_cg = new(); ExceptionsVf16_vmflt_vv_cg.set_inst_name("obj_ExceptionsVf16_vmflt_vv");
    ExceptionsVf16_vmfne_vf_cg = new(); ExceptionsVf16_vmfne_vf_cg.set_inst_name("obj_ExceptionsVf16_vmfne_vf");
    ExceptionsVf16_vmfne_vv_cg = new(); ExceptionsVf16_vmfne_vv_cg.set_inst_name("obj_ExceptionsVf16_vmfne_vv");
