///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    ExceptionsVls_vl1re16_v_cg = new(); ExceptionsVls_vl1re16_v_cg.set_inst_name("obj_ExceptionsVls_vl1re16_v");
    ExceptionsVls_vl1re32_v_cg = new(); ExceptionsVls_vl1re32_v_cg.set_inst_name("obj_ExceptionsVls_vl1re32_v");
    ExceptionsVls_vl1re64_v_cg = new(); ExceptionsVls_vl1re64_v_cg.set_inst_name("obj_ExceptionsVls_vl1re64_v");
    ExceptionsVls_vl1re8_v_cg = new(); ExceptionsVls_vl1re8_v_cg.set_inst_name("obj_ExceptionsVls_vl1re8_v");
    ExceptionsVls_vl2re16_v_cg = new(); ExceptionsVls_vl2re16_v_cg.set_inst_name("obj_ExceptionsVls_vl2re16_v");
    ExceptionsVls_vl2re32_v_cg = new(); ExceptionsVls_vl2re32_v_cg.set_inst_name("obj_ExceptionsVls_vl2re32_v");
    ExceptionsVls_vl2re64_v_cg = new(); ExceptionsVls_vl2re64_v_cg.set_inst_name("obj_ExceptionsVls_vl2re64_v");
    ExceptionsVls_vl2re8_v_cg = new(); ExceptionsVls_vl2re8_v_cg.set_inst_name("obj_ExceptionsVls_vl2re8_v");
    ExceptionsVls_vl4re16_v_cg = new(); ExceptionsVls_vl4re16_v_cg.set_inst_name("obj_ExceptionsVls_vl4re16_v");
    ExceptionsVls_vl4re32_v_cg = new(); ExceptionsVls_vl4re32_v_cg.set_inst_name("obj_ExceptionsVls_vl4re32_v");
    ExceptionsVls_vl4re64_v_cg = new(); ExceptionsVls_vl4re64_v_cg.set_inst_name("obj_ExceptionsVls_vl4re64_v");
    ExceptionsVls_vl4re8_v_cg = new(); ExceptionsVls_vl4re8_v_cg.set_inst_name("obj_ExceptionsVls_vl4re8_v");
    ExceptionsVls_vl8re16_v_cg = new(); ExceptionsVls_vl8re16_v_cg.set_inst_name("obj_ExceptionsVls_vl8re16_v");
    ExceptionsVls_vl8re32_v_cg = new(); ExceptionsVls_vl8re32_v_cg.set_inst_name("obj_ExceptionsVls_vl8re32_v");
    ExceptionsVls_vl8re64_v_cg = new(); ExceptionsVls_vl8re64_v_cg.set_inst_name("obj_ExceptionsVls_vl8re64_v");
    ExceptionsVls_vl8re8_v_cg = new(); ExceptionsVls_vl8re8_v_cg.set_inst_name("obj_ExceptionsVls_vl8re8_v");
    ExceptionsVls_vle16_v_cg = new(); ExceptionsVls_vle16_v_cg.set_inst_name("obj_ExceptionsVls_vle16_v");
    ExceptionsVls_vle16ff_v_cg = new(); ExceptionsVls_vle16ff_v_cg.set_inst_name("obj_ExceptionsVls_vle16ff_v");
    ExceptionsVls_vle32_v_cg = new(); ExceptionsVls_vle32_v_cg.set_inst_name("obj_ExceptionsVls_vle32_v");
    ExceptionsVls_vle32ff_v_cg = new(); ExceptionsVls_vle32ff_v_cg.set_inst_name("obj_ExceptionsVls_vle32ff_v");
    ExceptionsVls_vle64_v_cg = new(); ExceptionsVls_vle64_v_cg.set_inst_name("obj_ExceptionsVls_vle64_v");
    ExceptionsVls_vle64ff_v_cg = new(); ExceptionsVls_vle64ff_v_cg.set_inst_name("obj_ExceptionsVls_vle64ff_v");
    ExceptionsVls_vle8_v_cg = new(); ExceptionsVls_vle8_v_cg.set_inst_name("obj_ExceptionsVls_vle8_v");
    ExceptionsVls_vle8ff_v_cg = new(); ExceptionsVls_vle8ff_v_cg.set_inst_name("obj_ExceptionsVls_vle8ff_v");
    ExceptionsVls_vlm_v_cg = new(); ExceptionsVls_vlm_v_cg.set_inst_name("obj_ExceptionsVls_vlm_v");
    ExceptionsVls_vloxei16_v_cg = new(); ExceptionsVls_vloxei16_v_cg.set_inst_name("obj_ExceptionsVls_vloxei16_v");
    ExceptionsVls_vloxei32_v_cg = new(); ExceptionsVls_vloxei32_v_cg.set_inst_name("obj_ExceptionsVls_vloxei32_v");
`ifdef XLEN64
    ExceptionsVls_vloxei64_v_cg = new(); ExceptionsVls_vloxei64_v_cg.set_inst_name("obj_ExceptionsVls_vloxei64_v");
`endif
    ExceptionsVls_vloxei8_v_cg = new(); ExceptionsVls_vloxei8_v_cg.set_inst_name("obj_ExceptionsVls_vloxei8_v");
    ExceptionsVls_vloxseg2ei16_v_cg = new(); ExceptionsVls_vloxseg2ei16_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg2ei16_v");
    ExceptionsVls_vloxseg2ei32_v_cg = new(); ExceptionsVls_vloxseg2ei32_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg2ei32_v");
`ifdef XLEN64
    ExceptionsVls_vloxseg2ei64_v_cg = new(); ExceptionsVls_vloxseg2ei64_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg2ei64_v");
`endif
    ExceptionsVls_vloxseg2ei8_v_cg = new(); ExceptionsVls_vloxseg2ei8_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg2ei8_v");
    ExceptionsVls_vloxseg3ei16_v_cg = new(); ExceptionsVls_vloxseg3ei16_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg3ei16_v");
    ExceptionsVls_vloxseg3ei32_v_cg = new(); ExceptionsVls_vloxseg3ei32_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg3ei32_v");
`ifdef XLEN64
    ExceptionsVls_vloxseg3ei64_v_cg = new(); ExceptionsVls_vloxseg3ei64_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg3ei64_v");
`endif
    ExceptionsVls_vloxseg3ei8_v_cg = new(); ExceptionsVls_vloxseg3ei8_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg3ei8_v");
    ExceptionsVls_vloxseg4ei16_v_cg = new(); ExceptionsVls_vloxseg4ei16_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg4ei16_v");
    ExceptionsVls_vloxseg4ei32_v_cg = new(); ExceptionsVls_vloxseg4ei32_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg4ei32_v");
`ifdef XLEN64
    ExceptionsVls_vloxseg4ei64_v_cg = new(); ExceptionsVls_vloxseg4ei64_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg4ei64_v");
`endif
    ExceptionsVls_vloxseg4ei8_v_cg = new(); ExceptionsVls_vloxseg4ei8_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg4ei8_v");
    ExceptionsVls_vloxseg5ei16_v_cg = new(); ExceptionsVls_vloxseg5ei16_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg5ei16_v");
    ExceptionsVls_vloxseg5ei32_v_cg = new(); ExceptionsVls_vloxseg5ei32_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg5ei32_v");
`ifdef XLEN64
    ExceptionsVls_vloxseg5ei64_v_cg = new(); ExceptionsVls_vloxseg5ei64_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg5ei64_v");
`endif
    ExceptionsVls_vloxseg5ei8_v_cg = new(); ExceptionsVls_vloxseg5ei8_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg5ei8_v");
    ExceptionsVls_vloxseg6ei16_v_cg = new(); ExceptionsVls_vloxseg6ei16_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg6ei16_v");
    ExceptionsVls_vloxseg6ei32_v_cg = new(); ExceptionsVls_vloxseg6ei32_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg6ei32_v");
`ifdef XLEN64
    ExceptionsVls_vloxseg6ei64_v_cg = new(); ExceptionsVls_vloxseg6ei64_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg6ei64_v");
`endif
    ExceptionsVls_vloxseg6ei8_v_cg = new(); ExceptionsVls_vloxseg6ei8_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg6ei8_v");
    ExceptionsVls_vloxseg7ei16_v_cg = new(); ExceptionsVls_vloxseg7ei16_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg7ei16_v");
    ExceptionsVls_vloxseg7ei32_v_cg = new(); ExceptionsVls_vloxseg7ei32_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg7ei32_v");
`ifdef XLEN64
    ExceptionsVls_vloxseg7ei64_v_cg = new(); ExceptionsVls_vloxseg7ei64_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg7ei64_v");
`endif
    ExceptionsVls_vloxseg7ei8_v_cg = new(); ExceptionsVls_vloxseg7ei8_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg7ei8_v");
    ExceptionsVls_vloxseg8ei16_v_cg = new(); ExceptionsVls_vloxseg8ei16_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg8ei16_v");
    ExceptionsVls_vloxseg8ei32_v_cg = new(); ExceptionsVls_vloxseg8ei32_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg8ei32_v");
`ifdef XLEN64
    ExceptionsVls_vloxseg8ei64_v_cg = new(); ExceptionsVls_vloxseg8ei64_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg8ei64_v");
`endif
    ExceptionsVls_vloxseg8ei8_v_cg = new(); ExceptionsVls_vloxseg8ei8_v_cg.set_inst_name("obj_ExceptionsVls_vloxseg8ei8_v");
    ExceptionsVls_vlse16_v_cg = new(); ExceptionsVls_vlse16_v_cg.set_inst_name("obj_ExceptionsVls_vlse16_v");
    ExceptionsVls_vlse32_v_cg = new(); ExceptionsVls_vlse32_v_cg.set_inst_name("obj_ExceptionsVls_vlse32_v");
    ExceptionsVls_vlse64_v_cg = new(); ExceptionsVls_vlse64_v_cg.set_inst_name("obj_ExceptionsVls_vlse64_v");
    ExceptionsVls_vlse8_v_cg = new(); ExceptionsVls_vlse8_v_cg.set_inst_name("obj_ExceptionsVls_vlse8_v");
    ExceptionsVls_vlseg2e16_v_cg = new(); ExceptionsVls_vlseg2e16_v_cg.set_inst_name("obj_ExceptionsVls_vlseg2e16_v");
    ExceptionsVls_vlseg2e16ff_v_cg = new(); ExceptionsVls_vlseg2e16ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg2e16ff_v");
    ExceptionsVls_vlseg2e32_v_cg = new(); ExceptionsVls_vlseg2e32_v_cg.set_inst_name("obj_ExceptionsVls_vlseg2e32_v");
    ExceptionsVls_vlseg2e32ff_v_cg = new(); ExceptionsVls_vlseg2e32ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg2e32ff_v");
    ExceptionsVls_vlseg2e64_v_cg = new(); ExceptionsVls_vlseg2e64_v_cg.set_inst_name("obj_ExceptionsVls_vlseg2e64_v");
    ExceptionsVls_vlseg2e64ff_v_cg = new(); ExceptionsVls_vlseg2e64ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg2e64ff_v");
    ExceptionsVls_vlseg2e8_v_cg = new(); ExceptionsVls_vlseg2e8_v_cg.set_inst_name("obj_ExceptionsVls_vlseg2e8_v");
    ExceptionsVls_vlseg2e8ff_v_cg = new(); ExceptionsVls_vlseg2e8ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg2e8ff_v");
    ExceptionsVls_vlseg3e16_v_cg = new(); ExceptionsVls_vlseg3e16_v_cg.set_inst_name("obj_ExceptionsVls_vlseg3e16_v");
    ExceptionsVls_vlseg3e16ff_v_cg = new(); ExceptionsVls_vlseg3e16ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg3e16ff_v");
    ExceptionsVls_vlseg3e32_v_cg = new(); ExceptionsVls_vlseg3e32_v_cg.set_inst_name("obj_ExceptionsVls_vlseg3e32_v");
    ExceptionsVls_vlseg3e32ff_v_cg = new(); ExceptionsVls_vlseg3e32ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg3e32ff_v");
    ExceptionsVls_vlseg3e64_v_cg = new(); ExceptionsVls_vlseg3e64_v_cg.set_inst_name("obj_ExceptionsVls_vlseg3e64_v");
    ExceptionsVls_vlseg3e64ff_v_cg = new(); ExceptionsVls_vlseg3e64ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg3e64ff_v");
    ExceptionsVls_vlseg3e8_v_cg = new(); ExceptionsVls_vlseg3e8_v_cg.set_inst_name("obj_ExceptionsVls_vlseg3e8_v");
    ExceptionsVls_vlseg3e8ff_v_cg = new(); ExceptionsVls_vlseg3e8ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg3e8ff_v");
    ExceptionsVls_vlseg4e16_v_cg = new(); ExceptionsVls_vlseg4e16_v_cg.set_inst_name("obj_ExceptionsVls_vlseg4e16_v");
    ExceptionsVls_vlseg4e16ff_v_cg = new(); ExceptionsVls_vlseg4e16ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg4e16ff_v");
    ExceptionsVls_vlseg4e32_v_cg = new(); ExceptionsVls_vlseg4e32_v_cg.set_inst_name("obj_ExceptionsVls_vlseg4e32_v");
    ExceptionsVls_vlseg4e32ff_v_cg = new(); ExceptionsVls_vlseg4e32ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg4e32ff_v");
    ExceptionsVls_vlseg4e64_v_cg = new(); ExceptionsVls_vlseg4e64_v_cg.set_inst_name("obj_ExceptionsVls_vlseg4e64_v");
    ExceptionsVls_vlseg4e64ff_v_cg = new(); ExceptionsVls_vlseg4e64ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg4e64ff_v");
    ExceptionsVls_vlseg4e8_v_cg = new(); ExceptionsVls_vlseg4e8_v_cg.set_inst_name("obj_ExceptionsVls_vlseg4e8_v");
    ExceptionsVls_vlseg4e8ff_v_cg = new(); ExceptionsVls_vlseg4e8ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg4e8ff_v");
    ExceptionsVls_vlseg5e16_v_cg = new(); ExceptionsVls_vlseg5e16_v_cg.set_inst_name("obj_ExceptionsVls_vlseg5e16_v");
    ExceptionsVls_vlseg5e16ff_v_cg = new(); ExceptionsVls_vlseg5e16ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg5e16ff_v");
    ExceptionsVls_vlseg5e32_v_cg = new(); ExceptionsVls_vlseg5e32_v_cg.set_inst_name("obj_ExceptionsVls_vlseg5e32_v");
    ExceptionsVls_vlseg5e32ff_v_cg = new(); ExceptionsVls_vlseg5e32ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg5e32ff_v");
    ExceptionsVls_vlseg5e64_v_cg = new(); ExceptionsVls_vlseg5e64_v_cg.set_inst_name("obj_ExceptionsVls_vlseg5e64_v");
    ExceptionsVls_vlseg5e64ff_v_cg = new(); ExceptionsVls_vlseg5e64ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg5e64ff_v");
    ExceptionsVls_vlseg5e8_v_cg = new(); ExceptionsVls_vlseg5e8_v_cg.set_inst_name("obj_ExceptionsVls_vlseg5e8_v");
    ExceptionsVls_vlseg5e8ff_v_cg = new(); ExceptionsVls_vlseg5e8ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg5e8ff_v");
    ExceptionsVls_vlseg6e16_v_cg = new(); ExceptionsVls_vlseg6e16_v_cg.set_inst_name("obj_ExceptionsVls_vlseg6e16_v");
    ExceptionsVls_vlseg6e16ff_v_cg = new(); ExceptionsVls_vlseg6e16ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg6e16ff_v");
    ExceptionsVls_vlseg6e32_v_cg = new(); ExceptionsVls_vlseg6e32_v_cg.set_inst_name("obj_ExceptionsVls_vlseg6e32_v");
    ExceptionsVls_vlseg6e32ff_v_cg = new(); ExceptionsVls_vlseg6e32ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg6e32ff_v");
    ExceptionsVls_vlseg6e64_v_cg = new(); ExceptionsVls_vlseg6e64_v_cg.set_inst_name("obj_ExceptionsVls_vlseg6e64_v");
    ExceptionsVls_vlseg6e64ff_v_cg = new(); ExceptionsVls_vlseg6e64ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg6e64ff_v");
    ExceptionsVls_vlseg6e8_v_cg = new(); ExceptionsVls_vlseg6e8_v_cg.set_inst_name("obj_ExceptionsVls_vlseg6e8_v");
    ExceptionsVls_vlseg6e8ff_v_cg = new(); ExceptionsVls_vlseg6e8ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg6e8ff_v");
    ExceptionsVls_vlseg7e16_v_cg = new(); ExceptionsVls_vlseg7e16_v_cg.set_inst_name("obj_ExceptionsVls_vlseg7e16_v");
    ExceptionsVls_vlseg7e16ff_v_cg = new(); ExceptionsVls_vlseg7e16ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg7e16ff_v");
    ExceptionsVls_vlseg7e32_v_cg = new(); ExceptionsVls_vlseg7e32_v_cg.set_inst_name("obj_ExceptionsVls_vlseg7e32_v");
    ExceptionsVls_vlseg7e32ff_v_cg = new(); ExceptionsVls_vlseg7e32ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg7e32ff_v");
    ExceptionsVls_vlseg7e64_v_cg = new(); ExceptionsVls_vlseg7e64_v_cg.set_inst_name("obj_ExceptionsVls_vlseg7e64_v");
    ExceptionsVls_vlseg7e64ff_v_cg = new(); ExceptionsVls_vlseg7e64ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg7e64ff_v");
    ExceptionsVls_vlseg7e8_v_cg = new(); ExceptionsVls_vlseg7e8_v_cg.set_inst_name("obj_ExceptionsVls_vlseg7e8_v");
    ExceptionsVls_vlseg7e8ff_v_cg = new(); ExceptionsVls_vlseg7e8ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg7e8ff_v");
    ExceptionsVls_vlseg8e16_v_cg = new(); ExceptionsVls_vlseg8e16_v_cg.set_inst_name("obj_ExceptionsVls_vlseg8e16_v");
    ExceptionsVls_vlseg8e16ff_v_cg = new(); ExceptionsVls_vlseg8e16ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg8e16ff_v");
    ExceptionsVls_vlseg8e32_v_cg = new(); ExceptionsVls_vlseg8e32_v_cg.set_inst_name("obj_ExceptionsVls_vlseg8e32_v");
    ExceptionsVls_vlseg8e32ff_v_cg = new(); ExceptionsVls_vlseg8e32ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg8e32ff_v");
    ExceptionsVls_vlseg8e64_v_cg = new(); ExceptionsVls_vlseg8e64_v_cg.set_inst_name("obj_ExceptionsVls_vlseg8e64_v");
    ExceptionsVls_vlseg8e64ff_v_cg = new(); ExceptionsVls_vlseg8e64ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg8e64ff_v");
    ExceptionsVls_vlseg8e8_v_cg = new(); ExceptionsVls_vlseg8e8_v_cg.set_inst_name("obj_ExceptionsVls_vlseg8e8_v");
    ExceptionsVls_vlseg8e8ff_v_cg = new(); ExceptionsVls_vlseg8e8ff_v_cg.set_inst_name("obj_ExceptionsVls_vlseg8e8ff_v");
    ExceptionsVls_vlsseg2e16_v_cg = new(); ExceptionsVls_vlsseg2e16_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg2e16_v");
    ExceptionsVls_vlsseg2e32_v_cg = new(); ExceptionsVls_vlsseg2e32_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg2e32_v");
    ExceptionsVls_vlsseg2e64_v_cg = new(); ExceptionsVls_vlsseg2e64_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg2e64_v");
    ExceptionsVls_vlsseg2e8_v_cg = new(); ExceptionsVls_vlsseg2e8_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg2e8_v");
    ExceptionsVls_vlsseg3e16_v_cg = new(); ExceptionsVls_vlsseg3e16_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg3e16_v");
    ExceptionsVls_vlsseg3e32_v_cg = new(); ExceptionsVls_vlsseg3e32_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg3e32_v");
    ExceptionsVls_vlsseg3e64_v_cg = new(); ExceptionsVls_vlsseg3e64_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg3e64_v");
    ExceptionsVls_vlsseg3e8_v_cg = new(); ExceptionsVls_vlsseg3e8_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg3e8_v");
    ExceptionsVls_vlsseg4e16_v_cg = new(); ExceptionsVls_vlsseg4e16_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg4e16_v");
    ExceptionsVls_vlsseg4e32_v_cg = new(); ExceptionsVls_vlsseg4e32_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg4e32_v");
    ExceptionsVls_vlsseg4e64_v_cg = new(); ExceptionsVls_vlsseg4e64_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg4e64_v");
    ExceptionsVls_vlsseg4e8_v_cg = new(); ExceptionsVls_vlsseg4e8_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg4e8_v");
    ExceptionsVls_vlsseg5e16_v_cg = new(); ExceptionsVls_vlsseg5e16_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg5e16_v");
    ExceptionsVls_vlsseg5e32_v_cg = new(); ExceptionsVls_vlsseg5e32_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg5e32_v");
    ExceptionsVls_vlsseg5e64_v_cg = new(); ExceptionsVls_vlsseg5e64_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg5e64_v");
    ExceptionsVls_vlsseg5e8_v_cg = new(); ExceptionsVls_vlsseg5e8_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg5e8_v");
    ExceptionsVls_vlsseg6e16_v_cg = new(); ExceptionsVls_vlsseg6e16_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg6e16_v");
    ExceptionsVls_vlsseg6e32_v_cg = new(); ExceptionsVls_vlsseg6e32_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg6e32_v");
    ExceptionsVls_vlsseg6e64_v_cg = new(); ExceptionsVls_vlsseg6e64_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg6e64_v");
    ExceptionsVls_vlsseg6e8_v_cg = new(); ExceptionsVls_vlsseg6e8_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg6e8_v");
    ExceptionsVls_vlsseg7e16_v_cg = new(); ExceptionsVls_vlsseg7e16_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg7e16_v");
    ExceptionsVls_vlsseg7e32_v_cg = new(); ExceptionsVls_vlsseg7e32_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg7e32_v");
    ExceptionsVls_vlsseg7e64_v_cg = new(); ExceptionsVls_vlsseg7e64_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg7e64_v");
    ExceptionsVls_vlsseg7e8_v_cg = new(); ExceptionsVls_vlsseg7e8_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg7e8_v");
    ExceptionsVls_vlsseg8e16_v_cg = new(); ExceptionsVls_vlsseg8e16_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg8e16_v");
    ExceptionsVls_vlsseg8e32_v_cg = new(); ExceptionsVls_vlsseg8e32_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg8e32_v");
    ExceptionsVls_vlsseg8e64_v_cg = new(); ExceptionsVls_vlsseg8e64_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg8e64_v");
    ExceptionsVls_vlsseg8e8_v_cg = new(); ExceptionsVls_vlsseg8e8_v_cg.set_inst_name("obj_ExceptionsVls_vlsseg8e8_v");
    ExceptionsVls_vluxei16_v_cg = new(); ExceptionsVls_vluxei16_v_cg.set_inst_name("obj_ExceptionsVls_vluxei16_v");
    ExceptionsVls_vluxei32_v_cg = new(); ExceptionsVls_vluxei32_v_cg.set_inst_name("obj_ExceptionsVls_vluxei32_v");
`ifdef XLEN64
    ExceptionsVls_vluxei64_v_cg = new(); ExceptionsVls_vluxei64_v_cg.set_inst_name("obj_ExceptionsVls_vluxei64_v");
`endif
    ExceptionsVls_vluxei8_v_cg = new(); ExceptionsVls_vluxei8_v_cg.set_inst_name("obj_ExceptionsVls_vluxei8_v");
    ExceptionsVls_vluxseg2ei16_v_cg = new(); ExceptionsVls_vluxseg2ei16_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg2ei16_v");
    ExceptionsVls_vluxseg2ei32_v_cg = new(); ExceptionsVls_vluxseg2ei32_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg2ei32_v");
`ifdef XLEN64
    ExceptionsVls_vluxseg2ei64_v_cg = new(); ExceptionsVls_vluxseg2ei64_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg2ei64_v");
`endif
    ExceptionsVls_vluxseg2ei8_v_cg = new(); ExceptionsVls_vluxseg2ei8_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg2ei8_v");
    ExceptionsVls_vluxseg3ei16_v_cg = new(); ExceptionsVls_vluxseg3ei16_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg3ei16_v");
    ExceptionsVls_vluxseg3ei32_v_cg = new(); ExceptionsVls_vluxseg3ei32_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg3ei32_v");
`ifdef XLEN64
    ExceptionsVls_vluxseg3ei64_v_cg = new(); ExceptionsVls_vluxseg3ei64_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg3ei64_v");
`endif
    ExceptionsVls_vluxseg3ei8_v_cg = new(); ExceptionsVls_vluxseg3ei8_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg3ei8_v");
    ExceptionsVls_vluxseg4ei16_v_cg = new(); ExceptionsVls_vluxseg4ei16_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg4ei16_v");
    ExceptionsVls_vluxseg4ei32_v_cg = new(); ExceptionsVls_vluxseg4ei32_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg4ei32_v");
`ifdef XLEN64
    ExceptionsVls_vluxseg4ei64_v_cg = new(); ExceptionsVls_vluxseg4ei64_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg4ei64_v");
`endif
    ExceptionsVls_vluxseg4ei8_v_cg = new(); ExceptionsVls_vluxseg4ei8_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg4ei8_v");
    ExceptionsVls_vluxseg5ei16_v_cg = new(); ExceptionsVls_vluxseg5ei16_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg5ei16_v");
    ExceptionsVls_vluxseg5ei32_v_cg = new(); ExceptionsVls_vluxseg5ei32_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg5ei32_v");
`ifdef XLEN64
    ExceptionsVls_vluxseg5ei64_v_cg = new(); ExceptionsVls_vluxseg5ei64_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg5ei64_v");
`endif
    ExceptionsVls_vluxseg5ei8_v_cg = new(); ExceptionsVls_vluxseg5ei8_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg5ei8_v");
    ExceptionsVls_vluxseg6ei16_v_cg = new(); ExceptionsVls_vluxseg6ei16_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg6ei16_v");
    ExceptionsVls_vluxseg6ei32_v_cg = new(); ExceptionsVls_vluxseg6ei32_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg6ei32_v");
`ifdef XLEN64
    ExceptionsVls_vluxseg6ei64_v_cg = new(); ExceptionsVls_vluxseg6ei64_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg6ei64_v");
`endif
    ExceptionsVls_vluxseg6ei8_v_cg = new(); ExceptionsVls_vluxseg6ei8_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg6ei8_v");
    ExceptionsVls_vluxseg7ei16_v_cg = new(); ExceptionsVls_vluxseg7ei16_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg7ei16_v");
    ExceptionsVls_vluxseg7ei32_v_cg = new(); ExceptionsVls_vluxseg7ei32_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg7ei32_v");
`ifdef XLEN64
    ExceptionsVls_vluxseg7ei64_v_cg = new(); ExceptionsVls_vluxseg7ei64_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg7ei64_v");
`endif
    ExceptionsVls_vluxseg7ei8_v_cg = new(); ExceptionsVls_vluxseg7ei8_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg7ei8_v");
    ExceptionsVls_vluxseg8ei16_v_cg = new(); ExceptionsVls_vluxseg8ei16_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg8ei16_v");
    ExceptionsVls_vluxseg8ei32_v_cg = new(); ExceptionsVls_vluxseg8ei32_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg8ei32_v");
`ifdef XLEN64
    ExceptionsVls_vluxseg8ei64_v_cg = new(); ExceptionsVls_vluxseg8ei64_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg8ei64_v");
`endif
    ExceptionsVls_vluxseg8ei8_v_cg = new(); ExceptionsVls_vluxseg8ei8_v_cg.set_inst_name("obj_ExceptionsVls_vluxseg8ei8_v");
    ExceptionsVls_vs1r_v_cg = new(); ExceptionsVls_vs1r_v_cg.set_inst_name("obj_ExceptionsVls_vs1r_v");
    ExceptionsVls_vs2r_v_cg = new(); ExceptionsVls_vs2r_v_cg.set_inst_name("obj_ExceptionsVls_vs2r_v");
    ExceptionsVls_vs4r_v_cg = new(); ExceptionsVls_vs4r_v_cg.set_inst_name("obj_ExceptionsVls_vs4r_v");
    ExceptionsVls_vs8r_v_cg = new(); ExceptionsVls_vs8r_v_cg.set_inst_name("obj_ExceptionsVls_vs8r_v");
    ExceptionsVls_vse16_v_cg = new(); ExceptionsVls_vse16_v_cg.set_inst_name("obj_ExceptionsVls_vse16_v");
    ExceptionsVls_vse32_v_cg = new(); ExceptionsVls_vse32_v_cg.set_inst_name("obj_ExceptionsVls_vse32_v");
    ExceptionsVls_vse64_v_cg = new(); ExceptionsVls_vse64_v_cg.set_inst_name("obj_ExceptionsVls_vse64_v");
    ExceptionsVls_vse8_v_cg = new(); ExceptionsVls_vse8_v_cg.set_inst_name("obj_ExceptionsVls_vse8_v");
    ExceptionsVls_vsm_v_cg = new(); ExceptionsVls_vsm_v_cg.set_inst_name("obj_ExceptionsVls_vsm_v");
    ExceptionsVls_vsoxei16_v_cg = new(); ExceptionsVls_vsoxei16_v_cg.set_inst_name("obj_ExceptionsVls_vsoxei16_v");
    ExceptionsVls_vsoxei32_v_cg = new(); ExceptionsVls_vsoxei32_v_cg.set_inst_name("obj_ExceptionsVls_vsoxei32_v");
`ifdef XLEN64
    ExceptionsVls_vsoxei64_v_cg = new(); ExceptionsVls_vsoxei64_v_cg.set_inst_name("obj_ExceptionsVls_vsoxei64_v");
`endif
    ExceptionsVls_vsoxei8_v_cg = new(); ExceptionsVls_vsoxei8_v_cg.set_inst_name("obj_ExceptionsVls_vsoxei8_v");
    ExceptionsVls_vsoxseg2ei16_v_cg = new(); ExceptionsVls_vsoxseg2ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg2ei16_v");
    ExceptionsVls_vsoxseg2ei32_v_cg = new(); ExceptionsVls_vsoxseg2ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg2ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsoxseg2ei64_v_cg = new(); ExceptionsVls_vsoxseg2ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg2ei64_v");
`endif
    ExceptionsVls_vsoxseg2ei8_v_cg = new(); ExceptionsVls_vsoxseg2ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg2ei8_v");
    ExceptionsVls_vsoxseg3ei16_v_cg = new(); ExceptionsVls_vsoxseg3ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg3ei16_v");
    ExceptionsVls_vsoxseg3ei32_v_cg = new(); ExceptionsVls_vsoxseg3ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg3ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsoxseg3ei64_v_cg = new(); ExceptionsVls_vsoxseg3ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg3ei64_v");
`endif
    ExceptionsVls_vsoxseg3ei8_v_cg = new(); ExceptionsVls_vsoxseg3ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg3ei8_v");
    ExceptionsVls_vsoxseg4ei16_v_cg = new(); ExceptionsVls_vsoxseg4ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg4ei16_v");
    ExceptionsVls_vsoxseg4ei32_v_cg = new(); ExceptionsVls_vsoxseg4ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg4ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsoxseg4ei64_v_cg = new(); ExceptionsVls_vsoxseg4ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg4ei64_v");
`endif
    ExceptionsVls_vsoxseg4ei8_v_cg = new(); ExceptionsVls_vsoxseg4ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg4ei8_v");
    ExceptionsVls_vsoxseg5ei16_v_cg = new(); ExceptionsVls_vsoxseg5ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg5ei16_v");
    ExceptionsVls_vsoxseg5ei32_v_cg = new(); ExceptionsVls_vsoxseg5ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg5ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsoxseg5ei64_v_cg = new(); ExceptionsVls_vsoxseg5ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg5ei64_v");
`endif
    ExceptionsVls_vsoxseg5ei8_v_cg = new(); ExceptionsVls_vsoxseg5ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg5ei8_v");
    ExceptionsVls_vsoxseg6ei16_v_cg = new(); ExceptionsVls_vsoxseg6ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg6ei16_v");
    ExceptionsVls_vsoxseg6ei32_v_cg = new(); ExceptionsVls_vsoxseg6ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg6ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsoxseg6ei64_v_cg = new(); ExceptionsVls_vsoxseg6ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg6ei64_v");
`endif
    ExceptionsVls_vsoxseg6ei8_v_cg = new(); ExceptionsVls_vsoxseg6ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg6ei8_v");
    ExceptionsVls_vsoxseg7ei16_v_cg = new(); ExceptionsVls_vsoxseg7ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg7ei16_v");
    ExceptionsVls_vsoxseg7ei32_v_cg = new(); ExceptionsVls_vsoxseg7ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg7ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsoxseg7ei64_v_cg = new(); ExceptionsVls_vsoxseg7ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg7ei64_v");
`endif
    ExceptionsVls_vsoxseg7ei8_v_cg = new(); ExceptionsVls_vsoxseg7ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg7ei8_v");
    ExceptionsVls_vsoxseg8ei16_v_cg = new(); ExceptionsVls_vsoxseg8ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg8ei16_v");
    ExceptionsVls_vsoxseg8ei32_v_cg = new(); ExceptionsVls_vsoxseg8ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg8ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsoxseg8ei64_v_cg = new(); ExceptionsVls_vsoxseg8ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg8ei64_v");
`endif
    ExceptionsVls_vsoxseg8ei8_v_cg = new(); ExceptionsVls_vsoxseg8ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsoxseg8ei8_v");
    ExceptionsVls_vsse16_v_cg = new(); ExceptionsVls_vsse16_v_cg.set_inst_name("obj_ExceptionsVls_vsse16_v");
    ExceptionsVls_vsse32_v_cg = new(); ExceptionsVls_vsse32_v_cg.set_inst_name("obj_ExceptionsVls_vsse32_v");
    ExceptionsVls_vsse64_v_cg = new(); ExceptionsVls_vsse64_v_cg.set_inst_name("obj_ExceptionsVls_vsse64_v");
    ExceptionsVls_vsse8_v_cg = new(); ExceptionsVls_vsse8_v_cg.set_inst_name("obj_ExceptionsVls_vsse8_v");
    ExceptionsVls_vsseg2e16_v_cg = new(); ExceptionsVls_vsseg2e16_v_cg.set_inst_name("obj_ExceptionsVls_vsseg2e16_v");
    ExceptionsVls_vsseg2e32_v_cg = new(); ExceptionsVls_vsseg2e32_v_cg.set_inst_name("obj_ExceptionsVls_vsseg2e32_v");
    ExceptionsVls_vsseg2e64_v_cg = new(); ExceptionsVls_vsseg2e64_v_cg.set_inst_name("obj_ExceptionsVls_vsseg2e64_v");
    ExceptionsVls_vsseg2e8_v_cg = new(); ExceptionsVls_vsseg2e8_v_cg.set_inst_name("obj_ExceptionsVls_vsseg2e8_v");
    ExceptionsVls_vsseg3e16_v_cg = new(); ExceptionsVls_vsseg3e16_v_cg.set_inst_name("obj_ExceptionsVls_vsseg3e16_v");
    ExceptionsVls_vsseg3e32_v_cg = new(); ExceptionsVls_vsseg3e32_v_cg.set_inst_name("obj_ExceptionsVls_vsseg3e32_v");
    ExceptionsVls_vsseg3e64_v_cg = new(); ExceptionsVls_vsseg3e64_v_cg.set_inst_name("obj_ExceptionsVls_vsseg3e64_v");
    ExceptionsVls_vsseg3e8_v_cg = new(); ExceptionsVls_vsseg3e8_v_cg.set_inst_name("obj_ExceptionsVls_vsseg3e8_v");
    ExceptionsVls_vsseg4e16_v_cg = new(); ExceptionsVls_vsseg4e16_v_cg.set_inst_name("obj_ExceptionsVls_vsseg4e16_v");
    ExceptionsVls_vsseg4e32_v_cg = new(); ExceptionsVls_vsseg4e32_v_cg.set_inst_name("obj_ExceptionsVls_vsseg4e32_v");
    ExceptionsVls_vsseg4e64_v_cg = new(); ExceptionsVls_vsseg4e64_v_cg.set_inst_name("obj_ExceptionsVls_vsseg4e64_v");
    ExceptionsVls_vsseg4e8_v_cg = new(); ExceptionsVls_vsseg4e8_v_cg.set_inst_name("obj_ExceptionsVls_vsseg4e8_v");
    ExceptionsVls_vsseg5e16_v_cg = new(); ExceptionsVls_vsseg5e16_v_cg.set_inst_name("obj_ExceptionsVls_vsseg5e16_v");
    ExceptionsVls_vsseg5e32_v_cg = new(); ExceptionsVls_vsseg5e32_v_cg.set_inst_name("obj_ExceptionsVls_vsseg5e32_v");
    ExceptionsVls_vsseg5e64_v_cg = new(); ExceptionsVls_vsseg5e64_v_cg.set_inst_name("obj_ExceptionsVls_vsseg5e64_v");
    ExceptionsVls_vsseg5e8_v_cg = new(); ExceptionsVls_vsseg5e8_v_cg.set_inst_name("obj_ExceptionsVls_vsseg5e8_v");
    ExceptionsVls_vsseg6e16_v_cg = new(); ExceptionsVls_vsseg6e16_v_cg.set_inst_name("obj_ExceptionsVls_vsseg6e16_v");
    ExceptionsVls_vsseg6e32_v_cg = new(); ExceptionsVls_vsseg6e32_v_cg.set_inst_name("obj_ExceptionsVls_vsseg6e32_v");
    ExceptionsVls_vsseg6e64_v_cg = new(); ExceptionsVls_vsseg6e64_v_cg.set_inst_name("obj_ExceptionsVls_vsseg6e64_v");
    ExceptionsVls_vsseg6e8_v_cg = new(); ExceptionsVls_vsseg6e8_v_cg.set_inst_name("obj_ExceptionsVls_vsseg6e8_v");
    ExceptionsVls_vsseg7e16_v_cg = new(); ExceptionsVls_vsseg7e16_v_cg.set_inst_name("obj_ExceptionsVls_vsseg7e16_v");
    ExceptionsVls_vsseg7e32_v_cg = new(); ExceptionsVls_vsseg7e32_v_cg.set_inst_name("obj_ExceptionsVls_vsseg7e32_v");
    ExceptionsVls_vsseg7e64_v_cg = new(); ExceptionsVls_vsseg7e64_v_cg.set_inst_name("obj_ExceptionsVls_vsseg7e64_v");
    ExceptionsVls_vsseg7e8_v_cg = new(); ExceptionsVls_vsseg7e8_v_cg.set_inst_name("obj_ExceptionsVls_vsseg7e8_v");
    ExceptionsVls_vsseg8e16_v_cg = new(); ExceptionsVls_vsseg8e16_v_cg.set_inst_name("obj_ExceptionsVls_vsseg8e16_v");
    ExceptionsVls_vsseg8e32_v_cg = new(); ExceptionsVls_vsseg8e32_v_cg.set_inst_name("obj_ExceptionsVls_vsseg8e32_v");
    ExceptionsVls_vsseg8e64_v_cg = new(); ExceptionsVls_vsseg8e64_v_cg.set_inst_name("obj_ExceptionsVls_vsseg8e64_v");
    ExceptionsVls_vsseg8e8_v_cg = new(); ExceptionsVls_vsseg8e8_v_cg.set_inst_name("obj_ExceptionsVls_vsseg8e8_v");
    ExceptionsVls_vssseg2e16_v_cg = new(); ExceptionsVls_vssseg2e16_v_cg.set_inst_name("obj_ExceptionsVls_vssseg2e16_v");
    ExceptionsVls_vssseg2e32_v_cg = new(); ExceptionsVls_vssseg2e32_v_cg.set_inst_name("obj_ExceptionsVls_vssseg2e32_v");
    ExceptionsVls_vssseg2e64_v_cg = new(); ExceptionsVls_vssseg2e64_v_cg.set_inst_name("obj_ExceptionsVls_vssseg2e64_v");
    ExceptionsVls_vssseg2e8_v_cg = new(); ExceptionsVls_vssseg2e8_v_cg.set_inst_name("obj_ExceptionsVls_vssseg2e8_v");
    ExceptionsVls_vssseg3e16_v_cg = new(); ExceptionsVls_vssseg3e16_v_cg.set_inst_name("obj_ExceptionsVls_vssseg3e16_v");
    ExceptionsVls_vssseg3e32_v_cg = new(); ExceptionsVls_vssseg3e32_v_cg.set_inst_name("obj_ExceptionsVls_vssseg3e32_v");
    ExceptionsVls_vssseg3e64_v_cg = new(); ExceptionsVls_vssseg3e64_v_cg.set_inst_name("obj_ExceptionsVls_vssseg3e64_v");
    ExceptionsVls_vssseg3e8_v_cg = new(); ExceptionsVls_vssseg3e8_v_cg.set_inst_name("obj_ExceptionsVls_vssseg3e8_v");
    ExceptionsVls_vssseg4e16_v_cg = new(); ExceptionsVls_vssseg4e16_v_cg.set_inst_name("obj_ExceptionsVls_vssseg4e16_v");
    ExceptionsVls_vssseg4e32_v_cg = new(); ExceptionsVls_vssseg4e32_v_cg.set_inst_name("obj_ExceptionsVls_vssseg4e32_v");
    ExceptionsVls_vssseg4e64_v_cg = new(); ExceptionsVls_vssseg4e64_v_cg.set_inst_name("obj_ExceptionsVls_vssseg4e64_v");
    ExceptionsVls_vssseg4e8_v_cg = new(); ExceptionsVls_vssseg4e8_v_cg.set_inst_name("obj_ExceptionsVls_vssseg4e8_v");
    ExceptionsVls_vssseg5e16_v_cg = new(); ExceptionsVls_vssseg5e16_v_cg.set_inst_name("obj_ExceptionsVls_vssseg5e16_v");
    ExceptionsVls_vssseg5e32_v_cg = new(); ExceptionsVls_vssseg5e32_v_cg.set_inst_name("obj_ExceptionsVls_vssseg5e32_v");
    ExceptionsVls_vssseg5e64_v_cg = new(); ExceptionsVls_vssseg5e64_v_cg.set_inst_name("obj_ExceptionsVls_vssseg5e64_v");
    ExceptionsVls_vssseg5e8_v_cg = new(); ExceptionsVls_vssseg5e8_v_cg.set_inst_name("obj_ExceptionsVls_vssseg5e8_v");
    ExceptionsVls_vssseg6e16_v_cg = new(); ExceptionsVls_vssseg6e16_v_cg.set_inst_name("obj_ExceptionsVls_vssseg6e16_v");
    ExceptionsVls_vssseg6e32_v_cg = new(); ExceptionsVls_vssseg6e32_v_cg.set_inst_name("obj_ExceptionsVls_vssseg6e32_v");
    ExceptionsVls_vssseg6e64_v_cg = new(); ExceptionsVls_vssseg6e64_v_cg.set_inst_name("obj_ExceptionsVls_vssseg6e64_v");
    ExceptionsVls_vssseg6e8_v_cg = new(); ExceptionsVls_vssseg6e8_v_cg.set_inst_name("obj_ExceptionsVls_vssseg6e8_v");
    ExceptionsVls_vssseg7e16_v_cg = new(); ExceptionsVls_vssseg7e16_v_cg.set_inst_name("obj_ExceptionsVls_vssseg7e16_v");
    ExceptionsVls_vssseg7e32_v_cg = new(); ExceptionsVls_vssseg7e32_v_cg.set_inst_name("obj_ExceptionsVls_vssseg7e32_v");
    ExceptionsVls_vssseg7e64_v_cg = new(); ExceptionsVls_vssseg7e64_v_cg.set_inst_name("obj_ExceptionsVls_vssseg7e64_v");
    ExceptionsVls_vssseg7e8_v_cg = new(); ExceptionsVls_vssseg7e8_v_cg.set_inst_name("obj_ExceptionsVls_vssseg7e8_v");
    ExceptionsVls_vssseg8e16_v_cg = new(); ExceptionsVls_vssseg8e16_v_cg.set_inst_name("obj_ExceptionsVls_vssseg8e16_v");
    ExceptionsVls_vssseg8e32_v_cg = new(); ExceptionsVls_vssseg8e32_v_cg.set_inst_name("obj_ExceptionsVls_vssseg8e32_v");
    ExceptionsVls_vssseg8e64_v_cg = new(); ExceptionsVls_vssseg8e64_v_cg.set_inst_name("obj_ExceptionsVls_vssseg8e64_v");
    ExceptionsVls_vssseg8e8_v_cg = new(); ExceptionsVls_vssseg8e8_v_cg.set_inst_name("obj_ExceptionsVls_vssseg8e8_v");
    ExceptionsVls_vsuxei16_v_cg = new(); ExceptionsVls_vsuxei16_v_cg.set_inst_name("obj_ExceptionsVls_vsuxei16_v");
    ExceptionsVls_vsuxei32_v_cg = new(); ExceptionsVls_vsuxei32_v_cg.set_inst_name("obj_ExceptionsVls_vsuxei32_v");
`ifdef XLEN64
    ExceptionsVls_vsuxei64_v_cg = new(); ExceptionsVls_vsuxei64_v_cg.set_inst_name("obj_ExceptionsVls_vsuxei64_v");
`endif
    ExceptionsVls_vsuxei8_v_cg = new(); ExceptionsVls_vsuxei8_v_cg.set_inst_name("obj_ExceptionsVls_vsuxei8_v");
    ExceptionsVls_vsuxseg2ei16_v_cg = new(); ExceptionsVls_vsuxseg2ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg2ei16_v");
    ExceptionsVls_vsuxseg2ei32_v_cg = new(); ExceptionsVls_vsuxseg2ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg2ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsuxseg2ei64_v_cg = new(); ExceptionsVls_vsuxseg2ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg2ei64_v");
`endif
    ExceptionsVls_vsuxseg2ei8_v_cg = new(); ExceptionsVls_vsuxseg2ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg2ei8_v");
    ExceptionsVls_vsuxseg3ei16_v_cg = new(); ExceptionsVls_vsuxseg3ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg3ei16_v");
    ExceptionsVls_vsuxseg3ei32_v_cg = new(); ExceptionsVls_vsuxseg3ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg3ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsuxseg3ei64_v_cg = new(); ExceptionsVls_vsuxseg3ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg3ei64_v");
`endif
    ExceptionsVls_vsuxseg3ei8_v_cg = new(); ExceptionsVls_vsuxseg3ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg3ei8_v");
    ExceptionsVls_vsuxseg4ei16_v_cg = new(); ExceptionsVls_vsuxseg4ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg4ei16_v");
    ExceptionsVls_vsuxseg4ei32_v_cg = new(); ExceptionsVls_vsuxseg4ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg4ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsuxseg4ei64_v_cg = new(); ExceptionsVls_vsuxseg4ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg4ei64_v");
`endif
    ExceptionsVls_vsuxseg4ei8_v_cg = new(); ExceptionsVls_vsuxseg4ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg4ei8_v");
    ExceptionsVls_vsuxseg5ei16_v_cg = new(); ExceptionsVls_vsuxseg5ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg5ei16_v");
    ExceptionsVls_vsuxseg5ei32_v_cg = new(); ExceptionsVls_vsuxseg5ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg5ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsuxseg5ei64_v_cg = new(); ExceptionsVls_vsuxseg5ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg5ei64_v");
`endif
    ExceptionsVls_vsuxseg5ei8_v_cg = new(); ExceptionsVls_vsuxseg5ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg5ei8_v");
    ExceptionsVls_vsuxseg6ei16_v_cg = new(); ExceptionsVls_vsuxseg6ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg6ei16_v");
    ExceptionsVls_vsuxseg6ei32_v_cg = new(); ExceptionsVls_vsuxseg6ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg6ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsuxseg6ei64_v_cg = new(); ExceptionsVls_vsuxseg6ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg6ei64_v");
`endif
    ExceptionsVls_vsuxseg6ei8_v_cg = new(); ExceptionsVls_vsuxseg6ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg6ei8_v");
    ExceptionsVls_vsuxseg7ei16_v_cg = new(); ExceptionsVls_vsuxseg7ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg7ei16_v");
    ExceptionsVls_vsuxseg7ei32_v_cg = new(); ExceptionsVls_vsuxseg7ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg7ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsuxseg7ei64_v_cg = new(); ExceptionsVls_vsuxseg7ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg7ei64_v");
`endif
    ExceptionsVls_vsuxseg7ei8_v_cg = new(); ExceptionsVls_vsuxseg7ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg7ei8_v");
    ExceptionsVls_vsuxseg8ei16_v_cg = new(); ExceptionsVls_vsuxseg8ei16_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg8ei16_v");
    ExceptionsVls_vsuxseg8ei32_v_cg = new(); ExceptionsVls_vsuxseg8ei32_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg8ei32_v");
`ifdef XLEN64
    ExceptionsVls_vsuxseg8ei64_v_cg = new(); ExceptionsVls_vsuxseg8ei64_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg8ei64_v");
`endif
    ExceptionsVls_vsuxseg8ei8_v_cg = new(); ExceptionsVls_vsuxseg8ei8_v_cg.set_inst_name("obj_ExceptionsVls_vsuxseg8ei8_v");
