///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_EXCEPTIONSVFMIN
`define COVER_EXCEPTIONSVFMINCUSTOMEFFEW
`ifdef UDB_ELEN_EFFEW
    `define SEW_EFFEW_EQ_ELEN
`endif
`ifdef UDB_ELEN_TWOEFFEW
    `define SEW_EFFEW_EQ_ELEN_DIV_2
`endif
covergroup ExceptionsVfmin_vfncvt_f_f_w_cg with function sample(ins_t ins);
    option.per_instance = 0;
    //////////////////////////////////////////////////////////////////////////////////
    // cp_mstatus_fs_off
    // A vector floating-point instruction must raise an illegal-instruction trap
    // when mstatus.FS == Off (FP extension disabled). The cross pins mstatus.VS to
    // a non-Off value so the trap can only be attributed to FS being Off (not VS).
    //////////////////////////////////////////////////////////////////////////////////

    mstatus_fs_off : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "fs") {
        bins inactive = {0};
    }

    mstatus_vs_active_for_fs_off : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "vs") {
        bins active = {[1:3]};
    }

    cp_mstatus_fs_off : cross mstatus_fs_off, mstatus_vs_active_for_fs_off;

    //// end cp_mstatus_fs_off////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_mstatus_vs_off
    // A vector floating-point instruction must raise an illegal-instruction trap
    // when mstatus.VS == Off (V extension disabled). The cross pins mstatus.FS to
    // a non-Off value so the trap can only be attributed to VS being Off (not FS).
    //////////////////////////////////////////////////////////////////////////////////

    mstatus_vs_off : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "vs") {
        bins inactive = {0};
    }

    mstatus_fs_active_for_vs_off : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "fs") {
        bins active = {[1:3]};
    }

    cp_mstatus_vs_off : cross mstatus_vs_off, mstatus_fs_active_for_vs_off;

    //// end cp_mstatus_vs_off////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vectorfp_mstatus_fs_state
    // Sample the vector-FP instruction under each non-Off mstatus.FS starting
    // state (Initial=1, Clean=2, Dirty=3) with mstatus.VS != Off. We cannot
    // observe the FS state transition directly (legal impls may hard-wire FS to
    // Dirty), so this coverpoint only ensures the test exercises every starting
    // FS state. Combined with signature-based cross-model checking, this catches
    // transitioning-model bugs.
    //////////////////////////////////////////////////////////////////////////////////

    mstatus_fs_state : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "fs") {
        bins fs_initial = {1};
        bins fs_clean   = {2};
        bins fs_dirty   = {3};
    }

    mstatus_vs_active_for_fs_state : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "vs") {
        bins active = {[1:3]};
    }

    cp_vectorfp_mstatus_fs_state : cross mstatus_fs_state, mstatus_vs_active_for_fs_state;

    //// end cp_vectorfp_mstatus_fs_state////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vectorfp_mstatus_fs_state_affecting_csr
    //
    // Intentionally empty: this coverpoint cannot be expressed in pure functional
    // coverage. The "state-affecting CSR" case (e.g. vfdiv.vv 1.0/0.0 raising
    // the DZ flag in fflags) requires proving that mstatus.FS *transitioned*
    // to Dirty as a result of the vector-FP instruction modifying a fp CSR.
    // The RISC-V spec permits a legal always-Dirty implementation that
    // hard-wires mstatus.FS, so a coverage sample cannot distinguish "model
    // correctly transitioned FS" from "model is always-Dirty".
    //
    // The corresponding test sequence is still emitted by the priv test
    // generator (see generators/testgen/scripts/priv/cp_vectorfp_mstatus_fs_state_affecting_csr.py)
    // so that a transitioning model can be cross-checked against an always-Dirty
    // model via signature comparison.
    //////////////////////////////////////////////////////////////////////////////////

    //// end cp_vectorfp_mstatus_fs_state_affecting_csr////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vectorfp_mstatus_fs_state_affecting_register
    //
    // Intentionally empty: this coverpoint cannot be expressed in pure functional
    // coverage. The "state-affecting register" case (e.g. vfmv.f.s) requires
    // proving that mstatus.FS *transitioned* to Dirty as a result of the
    // vector-FP instruction writing an architectural f-register. The RISC-V
    // spec permits a legal always-Dirty implementation that hard-wires
    // mstatus.FS, so a coverage sample cannot distinguish "model correctly
    // transitioned FS" from "model is always-Dirty".
    //
    // The corresponding test sequence is still emitted by the priv test
    // generator (see generators/testgen/scripts/priv/cp_vectorfp_mstatus_fs_state_affecting_register.py)
    // so that a transitioning model can be cross-checked against an always-Dirty
    // model via signature comparison.
    //////////////////////////////////////////////////////////////////////////////////

    //// end cp_vectorfp_mstatus_fs_state_affecting_register////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vectorfp_mstatus_fs_state_nonaffecting
    //
    // Intentionally empty: this coverpoint cannot be expressed in pure functional
    // coverage. The "nonaffecting" case (e.g. vfadd.vv with vs1_val == vs2_val
    // == 0) requires proving that mstatus.FS *did not* transition out of
    // Initial/Clean as a result of the vector-FP instruction. The RISC-V spec
    // permits a legal always-Dirty implementation that hard-wires mstatus.FS,
    // so a coverage sample of FS after the instruction cannot distinguish
    // "model correctly left FS unchanged" from "model is always-Dirty".
    //
    // The corresponding test sequence is still emitted by the priv test
    // generator (see generators/testgen/scripts/priv/cp_vectorfp_mstatus_fs_state_nonaffecting.py)
    // so that a transitioning model can be cross-checked against an always-Dirty
    // model via signature comparison.
    //////////////////////////////////////////////////////////////////////////////////

    //// end cp_vectorfp_mstatus_fs_state_nonaffecting////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vill
    //////////////////////////////////////////////////////////////////////////////////

    cp_vill: coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vill") {
        bins one  = {1};
    }

    //// end cp_vill////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vstart
    //////////////////////////////////////////////////////////////////////////////////

    cp_vstart: coverpoint vstart_check(ins.hart, ins.issue) {
        bins vstart_one     = {vstart_one};
        bins vstart_vlmaxm1 = {vstart_vlmaxm1};
        bins vstart_vlmaxd2 = {vstart_vlmaxd2};
        bins vstart_legal   = {vstart_legal};   // random vstart
    }

    //// end cp_vstart////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vstart_gt_vl
    //////////////////////////////////////////////////////////////////////////////////

    cp_vstart_gt_vl: coverpoint (get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vstart", "vstart") >  get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vl", "vl") &
                                 get_vtype_vlmax(ins.hart, ins.issue, `SAMPLE_BEFORE) > get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vstart", "vstart")){
        bins true = {1};
    }

    //// end cp_vstart_gt_vl////////////////////////////////////////////////

endgroup
// ---------------------
covergroup ExceptionsVfmin_vfwcvt_f_f_v_cg with function sample(ins_t ins);
    option.per_instance = 0;
    //////////////////////////////////////////////////////////////////////////////////
    // cp_mstatus_fs_off
    // A vector floating-point instruction must raise an illegal-instruction trap
    // when mstatus.FS == Off (FP extension disabled). The cross pins mstatus.VS to
    // a non-Off value so the trap can only be attributed to FS being Off (not VS).
    //////////////////////////////////////////////////////////////////////////////////

    mstatus_fs_off : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "fs") {
        bins inactive = {0};
    }

    mstatus_vs_active_for_fs_off : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "vs") {
        bins active = {[1:3]};
    }

    cp_mstatus_fs_off : cross mstatus_fs_off, mstatus_vs_active_for_fs_off;

    //// end cp_mstatus_fs_off////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_mstatus_vs_off
    // A vector floating-point instruction must raise an illegal-instruction trap
    // when mstatus.VS == Off (V extension disabled). The cross pins mstatus.FS to
    // a non-Off value so the trap can only be attributed to VS being Off (not FS).
    //////////////////////////////////////////////////////////////////////////////////

    mstatus_vs_off : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "vs") {
        bins inactive = {0};
    }

    mstatus_fs_active_for_vs_off : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "fs") {
        bins active = {[1:3]};
    }

    cp_mstatus_vs_off : cross mstatus_vs_off, mstatus_fs_active_for_vs_off;

    //// end cp_mstatus_vs_off////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vectorfp_mstatus_fs_state
    // Sample the vector-FP instruction under each non-Off mstatus.FS starting
    // state (Initial=1, Clean=2, Dirty=3) with mstatus.VS != Off. We cannot
    // observe the FS state transition directly (legal impls may hard-wire FS to
    // Dirty), so this coverpoint only ensures the test exercises every starting
    // FS state. Combined with signature-based cross-model checking, this catches
    // transitioning-model bugs.
    //////////////////////////////////////////////////////////////////////////////////

    mstatus_fs_state : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "fs") {
        bins fs_initial = {1};
        bins fs_clean   = {2};
        bins fs_dirty   = {3};
    }

    mstatus_vs_active_for_fs_state : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "mstatus", "vs") {
        bins active = {[1:3]};
    }

    cp_vectorfp_mstatus_fs_state : cross mstatus_fs_state, mstatus_vs_active_for_fs_state;

    //// end cp_vectorfp_mstatus_fs_state////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vectorfp_mstatus_fs_state_affecting_csr
    //
    // Intentionally empty: this coverpoint cannot be expressed in pure functional
    // coverage. The "state-affecting CSR" case (e.g. vfdiv.vv 1.0/0.0 raising
    // the DZ flag in fflags) requires proving that mstatus.FS *transitioned*
    // to Dirty as a result of the vector-FP instruction modifying a fp CSR.
    // The RISC-V spec permits a legal always-Dirty implementation that
    // hard-wires mstatus.FS, so a coverage sample cannot distinguish "model
    // correctly transitioned FS" from "model is always-Dirty".
    //
    // The corresponding test sequence is still emitted by the priv test
    // generator (see generators/testgen/scripts/priv/cp_vectorfp_mstatus_fs_state_affecting_csr.py)
    // so that a transitioning model can be cross-checked against an always-Dirty
    // model via signature comparison.
    //////////////////////////////////////////////////////////////////////////////////

    //// end cp_vectorfp_mstatus_fs_state_affecting_csr////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vectorfp_mstatus_fs_state_affecting_register
    //
    // Intentionally empty: this coverpoint cannot be expressed in pure functional
    // coverage. The "state-affecting register" case (e.g. vfmv.f.s) requires
    // proving that mstatus.FS *transitioned* to Dirty as a result of the
    // vector-FP instruction writing an architectural f-register. The RISC-V
    // spec permits a legal always-Dirty implementation that hard-wires
    // mstatus.FS, so a coverage sample cannot distinguish "model correctly
    // transitioned FS" from "model is always-Dirty".
    //
    // The corresponding test sequence is still emitted by the priv test
    // generator (see generators/testgen/scripts/priv/cp_vectorfp_mstatus_fs_state_affecting_register.py)
    // so that a transitioning model can be cross-checked against an always-Dirty
    // model via signature comparison.
    //////////////////////////////////////////////////////////////////////////////////

    //// end cp_vectorfp_mstatus_fs_state_affecting_register////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vectorfp_mstatus_fs_state_nonaffecting
    //
    // Intentionally empty: this coverpoint cannot be expressed in pure functional
    // coverage. The "nonaffecting" case (e.g. vfadd.vv with vs1_val == vs2_val
    // == 0) requires proving that mstatus.FS *did not* transition out of
    // Initial/Clean as a result of the vector-FP instruction. The RISC-V spec
    // permits a legal always-Dirty implementation that hard-wires mstatus.FS,
    // so a coverage sample of FS after the instruction cannot distinguish
    // "model correctly left FS unchanged" from "model is always-Dirty".
    //
    // The corresponding test sequence is still emitted by the priv test
    // generator (see generators/testgen/scripts/priv/cp_vectorfp_mstatus_fs_state_nonaffecting.py)
    // so that a transitioning model can be cross-checked against an always-Dirty
    // model via signature comparison.
    //////////////////////////////////////////////////////////////////////////////////

    //// end cp_vectorfp_mstatus_fs_state_nonaffecting////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vill
    //////////////////////////////////////////////////////////////////////////////////

    cp_vill: coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vill") {
        bins one  = {1};
    }

    //// end cp_vill////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vstart
    //////////////////////////////////////////////////////////////////////////////////

    cp_vstart: coverpoint vstart_check(ins.hart, ins.issue) {
        bins vstart_one     = {vstart_one};
        bins vstart_vlmaxm1 = {vstart_vlmaxm1};
        bins vstart_vlmaxd2 = {vstart_vlmaxd2};
        bins vstart_legal   = {vstart_legal};   // random vstart
    }

    //// end cp_vstart////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vstart_gt_vl
    //////////////////////////////////////////////////////////////////////////////////

    cp_vstart_gt_vl: coverpoint (get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vstart", "vstart") >  get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vl", "vl") &
                                 get_vtype_vlmax(ins.hart, ins.issue, `SAMPLE_BEFORE) > get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vstart", "vstart")){
        bins true = {1};
    }

    //// end cp_vstart_gt_vl////////////////////////////////////////////////

endgroup
// ---------------------
function void exceptionsvfmin_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "vfncvt.f.f.w"     : begin
            ExceptionsVfmin_vfncvt_f_f_w_cg.sample(ins);
        end
        "vfwcvt.f.f.v"     : begin
            ExceptionsVfmin_vfwcvt_f_f_v_cg.sample(ins);
        end
    endcase
endfunction
