///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    ExceptionsVfmin_vfncvt_f_f_w_cg = new(); ExceptionsVfmin_vfncvt_f_f_w_cg.set_inst_name("obj_ExceptionsVfmin_vfncvt_f_f_w");
    ExceptionsVfmin_vfwcvt_f_f_v_cg = new(); ExceptionsVfmin_vfwcvt_f_f_v_cg.set_inst_name("obj_ExceptionsVfmin_vfwcvt_f_f_v");
