///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    MisalignedV_vl1re16_v_cg = new(); MisalignedV_vl1re16_v_cg.set_inst_name("obj_MisalignedV_vl1re16_v");
    MisalignedV_vl1re32_v_cg = new(); MisalignedV_vl1re32_v_cg.set_inst_name("obj_MisalignedV_vl1re32_v");
    MisalignedV_vl1re64_v_cg = new(); MisalignedV_vl1re64_v_cg.set_inst_name("obj_MisalignedV_vl1re64_v");
    MisalignedV_vl1re8_v_cg = new(); MisalignedV_vl1re8_v_cg.set_inst_name("obj_MisalignedV_vl1re8_v");
    MisalignedV_vl2re16_v_cg = new(); MisalignedV_vl2re16_v_cg.set_inst_name("obj_MisalignedV_vl2re16_v");
    MisalignedV_vl2re32_v_cg = new(); MisalignedV_vl2re32_v_cg.set_inst_name("obj_MisalignedV_vl2re32_v");
    MisalignedV_vl2re64_v_cg = new(); MisalignedV_vl2re64_v_cg.set_inst_name("obj_MisalignedV_vl2re64_v");
    MisalignedV_vl2re8_v_cg = new(); MisalignedV_vl2re8_v_cg.set_inst_name("obj_MisalignedV_vl2re8_v");
    MisalignedV_vl4re16_v_cg = new(); MisalignedV_vl4re16_v_cg.set_inst_name("obj_MisalignedV_vl4re16_v");
    MisalignedV_vl4re32_v_cg = new(); MisalignedV_vl4re32_v_cg.set_inst_name("obj_MisalignedV_vl4re32_v");
    MisalignedV_vl4re64_v_cg = new(); MisalignedV_vl4re64_v_cg.set_inst_name("obj_MisalignedV_vl4re64_v");
    MisalignedV_vl4re8_v_cg = new(); MisalignedV_vl4re8_v_cg.set_inst_name("obj_MisalignedV_vl4re8_v");
    MisalignedV_vl8re16_v_cg = new(); MisalignedV_vl8re16_v_cg.set_inst_name("obj_MisalignedV_vl8re16_v");
    MisalignedV_vl8re32_v_cg = new(); MisalignedV_vl8re32_v_cg.set_inst_name("obj_MisalignedV_vl8re32_v");
    MisalignedV_vl8re64_v_cg = new(); MisalignedV_vl8re64_v_cg.set_inst_name("obj_MisalignedV_vl8re64_v");
    MisalignedV_vl8re8_v_cg = new(); MisalignedV_vl8re8_v_cg.set_inst_name("obj_MisalignedV_vl8re8_v");
    MisalignedV_vle16_v_cg = new(); MisalignedV_vle16_v_cg.set_inst_name("obj_MisalignedV_vle16_v");
    MisalignedV_vle16ff_v_cg = new(); MisalignedV_vle16ff_v_cg.set_inst_name("obj_MisalignedV_vle16ff_v");
    MisalignedV_vle32_v_cg = new(); MisalignedV_vle32_v_cg.set_inst_name("obj_MisalignedV_vle32_v");
    MisalignedV_vle32ff_v_cg = new(); MisalignedV_vle32ff_v_cg.set_inst_name("obj_MisalignedV_vle32ff_v");
    MisalignedV_vle64_v_cg = new(); MisalignedV_vle64_v_cg.set_inst_name("obj_MisalignedV_vle64_v");
    MisalignedV_vle64ff_v_cg = new(); MisalignedV_vle64ff_v_cg.set_inst_name("obj_MisalignedV_vle64ff_v");
    MisalignedV_vle8_v_cg = new(); MisalignedV_vle8_v_cg.set_inst_name("obj_MisalignedV_vle8_v");
    MisalignedV_vle8ff_v_cg = new(); MisalignedV_vle8ff_v_cg.set_inst_name("obj_MisalignedV_vle8ff_v");
    MisalignedV_vlm_v_cg = new(); MisalignedV_vlm_v_cg.set_inst_name("obj_MisalignedV_vlm_v");
    MisalignedV_vloxei16_v_cg = new(); MisalignedV_vloxei16_v_cg.set_inst_name("obj_MisalignedV_vloxei16_v");
    MisalignedV_vloxei32_v_cg = new(); MisalignedV_vloxei32_v_cg.set_inst_name("obj_MisalignedV_vloxei32_v");
`ifdef XLEN64
    MisalignedV_vloxei64_v_cg = new(); MisalignedV_vloxei64_v_cg.set_inst_name("obj_MisalignedV_vloxei64_v");
`endif
    MisalignedV_vloxei8_v_cg = new(); MisalignedV_vloxei8_v_cg.set_inst_name("obj_MisalignedV_vloxei8_v");
    MisalignedV_vloxseg2ei16_v_cg = new(); MisalignedV_vloxseg2ei16_v_cg.set_inst_name("obj_MisalignedV_vloxseg2ei16_v");
    MisalignedV_vloxseg2ei32_v_cg = new(); MisalignedV_vloxseg2ei32_v_cg.set_inst_name("obj_MisalignedV_vloxseg2ei32_v");
`ifdef XLEN64
    MisalignedV_vloxseg2ei64_v_cg = new(); MisalignedV_vloxseg2ei64_v_cg.set_inst_name("obj_MisalignedV_vloxseg2ei64_v");
`endif
    MisalignedV_vloxseg2ei8_v_cg = new(); MisalignedV_vloxseg2ei8_v_cg.set_inst_name("obj_MisalignedV_vloxseg2ei8_v");
    MisalignedV_vloxseg3ei16_v_cg = new(); MisalignedV_vloxseg3ei16_v_cg.set_inst_name("obj_MisalignedV_vloxseg3ei16_v");
    MisalignedV_vloxseg3ei32_v_cg = new(); MisalignedV_vloxseg3ei32_v_cg.set_inst_name("obj_MisalignedV_vloxseg3ei32_v");
`ifdef XLEN64
    MisalignedV_vloxseg3ei64_v_cg = new(); MisalignedV_vloxseg3ei64_v_cg.set_inst_name("obj_MisalignedV_vloxseg3ei64_v");
`endif
    MisalignedV_vloxseg3ei8_v_cg = new(); MisalignedV_vloxseg3ei8_v_cg.set_inst_name("obj_MisalignedV_vloxseg3ei8_v");
    MisalignedV_vloxseg4ei16_v_cg = new(); MisalignedV_vloxseg4ei16_v_cg.set_inst_name("obj_MisalignedV_vloxseg4ei16_v");
    MisalignedV_vloxseg4ei32_v_cg = new(); MisalignedV_vloxseg4ei32_v_cg.set_inst_name("obj_MisalignedV_vloxseg4ei32_v");
`ifdef XLEN64
    MisalignedV_vloxseg4ei64_v_cg = new(); MisalignedV_vloxseg4ei64_v_cg.set_inst_name("obj_MisalignedV_vloxseg4ei64_v");
`endif
    MisalignedV_vloxseg4ei8_v_cg = new(); MisalignedV_vloxseg4ei8_v_cg.set_inst_name("obj_MisalignedV_vloxseg4ei8_v");
    MisalignedV_vloxseg5ei16_v_cg = new(); MisalignedV_vloxseg5ei16_v_cg.set_inst_name("obj_MisalignedV_vloxseg5ei16_v");
    MisalignedV_vloxseg5ei32_v_cg = new(); MisalignedV_vloxseg5ei32_v_cg.set_inst_name("obj_MisalignedV_vloxseg5ei32_v");
`ifdef XLEN64
    MisalignedV_vloxseg5ei64_v_cg = new(); MisalignedV_vloxseg5ei64_v_cg.set_inst_name("obj_MisalignedV_vloxseg5ei64_v");
`endif
    MisalignedV_vloxseg5ei8_v_cg = new(); MisalignedV_vloxseg5ei8_v_cg.set_inst_name("obj_MisalignedV_vloxseg5ei8_v");
    MisalignedV_vloxseg6ei16_v_cg = new(); MisalignedV_vloxseg6ei16_v_cg.set_inst_name("obj_MisalignedV_vloxseg6ei16_v");
    MisalignedV_vloxseg6ei32_v_cg = new(); MisalignedV_vloxseg6ei32_v_cg.set_inst_name("obj_MisalignedV_vloxseg6ei32_v");
`ifdef XLEN64
    MisalignedV_vloxseg6ei64_v_cg = new(); MisalignedV_vloxseg6ei64_v_cg.set_inst_name("obj_MisalignedV_vloxseg6ei64_v");
`endif
    MisalignedV_vloxseg6ei8_v_cg = new(); MisalignedV_vloxseg6ei8_v_cg.set_inst_name("obj_MisalignedV_vloxseg6ei8_v");
    MisalignedV_vloxseg7ei16_v_cg = new(); MisalignedV_vloxseg7ei16_v_cg.set_inst_name("obj_MisalignedV_vloxseg7ei16_v");
    MisalignedV_vloxseg7ei32_v_cg = new(); MisalignedV_vloxseg7ei32_v_cg.set_inst_name("obj_MisalignedV_vloxseg7ei32_v");
`ifdef XLEN64
    MisalignedV_vloxseg7ei64_v_cg = new(); MisalignedV_vloxseg7ei64_v_cg.set_inst_name("obj_MisalignedV_vloxseg7ei64_v");
`endif
    MisalignedV_vloxseg7ei8_v_cg = new(); MisalignedV_vloxseg7ei8_v_cg.set_inst_name("obj_MisalignedV_vloxseg7ei8_v");
    MisalignedV_vloxseg8ei16_v_cg = new(); MisalignedV_vloxseg8ei16_v_cg.set_inst_name("obj_MisalignedV_vloxseg8ei16_v");
    MisalignedV_vloxseg8ei32_v_cg = new(); MisalignedV_vloxseg8ei32_v_cg.set_inst_name("obj_MisalignedV_vloxseg8ei32_v");
`ifdef XLEN64
    MisalignedV_vloxseg8ei64_v_cg = new(); MisalignedV_vloxseg8ei64_v_cg.set_inst_name("obj_MisalignedV_vloxseg8ei64_v");
`endif
    MisalignedV_vloxseg8ei8_v_cg = new(); MisalignedV_vloxseg8ei8_v_cg.set_inst_name("obj_MisalignedV_vloxseg8ei8_v");
    MisalignedV_vlse16_v_cg = new(); MisalignedV_vlse16_v_cg.set_inst_name("obj_MisalignedV_vlse16_v");
    MisalignedV_vlse32_v_cg = new(); MisalignedV_vlse32_v_cg.set_inst_name("obj_MisalignedV_vlse32_v");
    MisalignedV_vlse64_v_cg = new(); MisalignedV_vlse64_v_cg.set_inst_name("obj_MisalignedV_vlse64_v");
    MisalignedV_vlse8_v_cg = new(); MisalignedV_vlse8_v_cg.set_inst_name("obj_MisalignedV_vlse8_v");
    MisalignedV_vlseg2e16_v_cg = new(); MisalignedV_vlseg2e16_v_cg.set_inst_name("obj_MisalignedV_vlseg2e16_v");
    MisalignedV_vlseg2e16ff_v_cg = new(); MisalignedV_vlseg2e16ff_v_cg.set_inst_name("obj_MisalignedV_vlseg2e16ff_v");
    MisalignedV_vlseg2e32_v_cg = new(); MisalignedV_vlseg2e32_v_cg.set_inst_name("obj_MisalignedV_vlseg2e32_v");
    MisalignedV_vlseg2e32ff_v_cg = new(); MisalignedV_vlseg2e32ff_v_cg.set_inst_name("obj_MisalignedV_vlseg2e32ff_v");
    MisalignedV_vlseg2e64_v_cg = new(); MisalignedV_vlseg2e64_v_cg.set_inst_name("obj_MisalignedV_vlseg2e64_v");
    MisalignedV_vlseg2e64ff_v_cg = new(); MisalignedV_vlseg2e64ff_v_cg.set_inst_name("obj_MisalignedV_vlseg2e64ff_v");
    MisalignedV_vlseg2e8_v_cg = new(); MisalignedV_vlseg2e8_v_cg.set_inst_name("obj_MisalignedV_vlseg2e8_v");
    MisalignedV_vlseg2e8ff_v_cg = new(); MisalignedV_vlseg2e8ff_v_cg.set_inst_name("obj_MisalignedV_vlseg2e8ff_v");
    MisalignedV_vlseg3e16_v_cg = new(); MisalignedV_vlseg3e16_v_cg.set_inst_name("obj_MisalignedV_vlseg3e16_v");
    MisalignedV_vlseg3e16ff_v_cg = new(); MisalignedV_vlseg3e16ff_v_cg.set_inst_name("obj_MisalignedV_vlseg3e16ff_v");
    MisalignedV_vlseg3e32_v_cg = new(); MisalignedV_vlseg3e32_v_cg.set_inst_name("obj_MisalignedV_vlseg3e32_v");
    MisalignedV_vlseg3e32ff_v_cg = new(); MisalignedV_vlseg3e32ff_v_cg.set_inst_name("obj_MisalignedV_vlseg3e32ff_v");
    MisalignedV_vlseg3e64_v_cg = new(); MisalignedV_vlseg3e64_v_cg.set_inst_name("obj_MisalignedV_vlseg3e64_v");
    MisalignedV_vlseg3e64ff_v_cg = new(); MisalignedV_vlseg3e64ff_v_cg.set_inst_name("obj_MisalignedV_vlseg3e64ff_v");
    MisalignedV_vlseg3e8_v_cg = new(); MisalignedV_vlseg3e8_v_cg.set_inst_name("obj_MisalignedV_vlseg3e8_v");
    MisalignedV_vlseg3e8ff_v_cg = new(); MisalignedV_vlseg3e8ff_v_cg.set_inst_name("obj_MisalignedV_vlseg3e8ff_v");
    MisalignedV_vlseg4e16_v_cg = new(); MisalignedV_vlseg4e16_v_cg.set_inst_name("obj_MisalignedV_vlseg4e16_v");
    MisalignedV_vlseg4e16ff_v_cg = new(); MisalignedV_vlseg4e16ff_v_cg.set_inst_name("obj_MisalignedV_vlseg4e16ff_v");
    MisalignedV_vlseg4e32_v_cg = new(); MisalignedV_vlseg4e32_v_cg.set_inst_name("obj_MisalignedV_vlseg4e32_v");
    MisalignedV_vlseg4e32ff_v_cg = new(); MisalignedV_vlseg4e32ff_v_cg.set_inst_name("obj_MisalignedV_vlseg4e32ff_v");
    MisalignedV_vlseg4e64_v_cg = new(); MisalignedV_vlseg4e64_v_cg.set_inst_name("obj_MisalignedV_vlseg4e64_v");
    MisalignedV_vlseg4e64ff_v_cg = new(); MisalignedV_vlseg4e64ff_v_cg.set_inst_name("obj_MisalignedV_vlseg4e64ff_v");
    MisalignedV_vlseg4e8_v_cg = new(); MisalignedV_vlseg4e8_v_cg.set_inst_name("obj_MisalignedV_vlseg4e8_v");
    MisalignedV_vlseg4e8ff_v_cg = new(); MisalignedV_vlseg4e8ff_v_cg.set_inst_name("obj_MisalignedV_vlseg4e8ff_v");
    MisalignedV_vlseg5e16_v_cg = new(); MisalignedV_vlseg5e16_v_cg.set_inst_name("obj_MisalignedV_vlseg5e16_v");
    MisalignedV_vlseg5e16ff_v_cg = new(); MisalignedV_vlseg5e16ff_v_cg.set_inst_name("obj_MisalignedV_vlseg5e16ff_v");
    MisalignedV_vlseg5e32_v_cg = new(); MisalignedV_vlseg5e32_v_cg.set_inst_name("obj_MisalignedV_vlseg5e32_v");
    MisalignedV_vlseg5e32ff_v_cg = new(); MisalignedV_vlseg5e32ff_v_cg.set_inst_name("obj_MisalignedV_vlseg5e32ff_v");
    MisalignedV_vlseg5e64_v_cg = new(); MisalignedV_vlseg5e64_v_cg.set_inst_name("obj_MisalignedV_vlseg5e64_v");
    MisalignedV_vlseg5e64ff_v_cg = new(); MisalignedV_vlseg5e64ff_v_cg.set_inst_name("obj_MisalignedV_vlseg5e64ff_v");
    MisalignedV_vlseg5e8_v_cg = new(); MisalignedV_vlseg5e8_v_cg.set_inst_name("obj_MisalignedV_vlseg5e8_v");
    MisalignedV_vlseg5e8ff_v_cg = new(); MisalignedV_vlseg5e8ff_v_cg.set_inst_name("obj_MisalignedV_vlseg5e8ff_v");
    MisalignedV_vlseg6e16_v_cg = new(); MisalignedV_vlseg6e16_v_cg.set_inst_name("obj_MisalignedV_vlseg6e16_v");
    MisalignedV_vlseg6e16ff_v_cg = new(); MisalignedV_vlseg6e16ff_v_cg.set_inst_name("obj_MisalignedV_vlseg6e16ff_v");
    MisalignedV_vlseg6e32_v_cg = new(); MisalignedV_vlseg6e32_v_cg.set_inst_name("obj_MisalignedV_vlseg6e32_v");
    MisalignedV_vlseg6e32ff_v_cg = new(); MisalignedV_vlseg6e32ff_v_cg.set_inst_name("obj_MisalignedV_vlseg6e32ff_v");
    MisalignedV_vlseg6e64_v_cg = new(); MisalignedV_vlseg6e64_v_cg.set_inst_name("obj_MisalignedV_vlseg6e64_v");
    MisalignedV_vlseg6e64ff_v_cg = new(); MisalignedV_vlseg6e64ff_v_cg.set_inst_name("obj_MisalignedV_vlseg6e64ff_v");
    MisalignedV_vlseg6e8_v_cg = new(); MisalignedV_vlseg6e8_v_cg.set_inst_name("obj_MisalignedV_vlseg6e8_v");
    MisalignedV_vlseg6e8ff_v_cg = new(); MisalignedV_vlseg6e8ff_v_cg.set_inst_name("obj_MisalignedV_vlseg6e8ff_v");
    MisalignedV_vlseg7e16_v_cg = new(); MisalignedV_vlseg7e16_v_cg.set_inst_name("obj_MisalignedV_vlseg7e16_v");
    MisalignedV_vlseg7e16ff_v_cg = new(); MisalignedV_vlseg7e16ff_v_cg.set_inst_name("obj_MisalignedV_vlseg7e16ff_v");
    MisalignedV_vlseg7e32_v_cg = new(); MisalignedV_vlseg7e32_v_cg.set_inst_name("obj_MisalignedV_vlseg7e32_v");
    MisalignedV_vlseg7e32ff_v_cg = new(); MisalignedV_vlseg7e32ff_v_cg.set_inst_name("obj_MisalignedV_vlseg7e32ff_v");
    MisalignedV_vlseg7e64_v_cg = new(); MisalignedV_vlseg7e64_v_cg.set_inst_name("obj_MisalignedV_vlseg7e64_v");
    MisalignedV_vlseg7e64ff_v_cg = new(); MisalignedV_vlseg7e64ff_v_cg.set_inst_name("obj_MisalignedV_vlseg7e64ff_v");
    MisalignedV_vlseg7e8_v_cg = new(); MisalignedV_vlseg7e8_v_cg.set_inst_name("obj_MisalignedV_vlseg7e8_v");
    MisalignedV_vlseg7e8ff_v_cg = new(); MisalignedV_vlseg7e8ff_v_cg.set_inst_name("obj_MisalignedV_vlseg7e8ff_v");
    MisalignedV_vlseg8e16_v_cg = new(); MisalignedV_vlseg8e16_v_cg.set_inst_name("obj_MisalignedV_vlseg8e16_v");
    MisalignedV_vlseg8e16ff_v_cg = new(); MisalignedV_vlseg8e16ff_v_cg.set_inst_name("obj_MisalignedV_vlseg8e16ff_v");
    MisalignedV_vlseg8e32_v_cg = new(); MisalignedV_vlseg8e32_v_cg.set_inst_name("obj_MisalignedV_vlseg8e32_v");
    MisalignedV_vlseg8e32ff_v_cg = new(); MisalignedV_vlseg8e32ff_v_cg.set_inst_name("obj_MisalignedV_vlseg8e32ff_v");
    MisalignedV_vlseg8e64_v_cg = new(); MisalignedV_vlseg8e64_v_cg.set_inst_name("obj_MisalignedV_vlseg8e64_v");
    MisalignedV_vlseg8e64ff_v_cg = new(); MisalignedV_vlseg8e64ff_v_cg.set_inst_name("obj_MisalignedV_vlseg8e64ff_v");
    MisalignedV_vlseg8e8_v_cg = new(); MisalignedV_vlseg8e8_v_cg.set_inst_name("obj_MisalignedV_vlseg8e8_v");
    MisalignedV_vlseg8e8ff_v_cg = new(); MisalignedV_vlseg8e8ff_v_cg.set_inst_name("obj_MisalignedV_vlseg8e8ff_v");
    MisalignedV_vlsseg2e16_v_cg = new(); MisalignedV_vlsseg2e16_v_cg.set_inst_name("obj_MisalignedV_vlsseg2e16_v");
    MisalignedV_vlsseg2e32_v_cg = new(); MisalignedV_vlsseg2e32_v_cg.set_inst_name("obj_MisalignedV_vlsseg2e32_v");
    MisalignedV_vlsseg2e64_v_cg = new(); MisalignedV_vlsseg2e64_v_cg.set_inst_name("obj_MisalignedV_vlsseg2e64_v");
    MisalignedV_vlsseg2e8_v_cg = new(); MisalignedV_vlsseg2e8_v_cg.set_inst_name("obj_MisalignedV_vlsseg2e8_v");
    MisalignedV_vlsseg3e16_v_cg = new(); MisalignedV_vlsseg3e16_v_cg.set_inst_name("obj_MisalignedV_vlsseg3e16_v");
    MisalignedV_vlsseg3e32_v_cg = new(); MisalignedV_vlsseg3e32_v_cg.set_inst_name("obj_MisalignedV_vlsseg3e32_v");
    MisalignedV_vlsseg3e64_v_cg = new(); MisalignedV_vlsseg3e64_v_cg.set_inst_name("obj_MisalignedV_vlsseg3e64_v");
    MisalignedV_vlsseg3e8_v_cg = new(); MisalignedV_vlsseg3e8_v_cg.set_inst_name("obj_MisalignedV_vlsseg3e8_v");
    MisalignedV_vlsseg4e16_v_cg = new(); MisalignedV_vlsseg4e16_v_cg.set_inst_name("obj_MisalignedV_vlsseg4e16_v");
    MisalignedV_vlsseg4e32_v_cg = new(); MisalignedV_vlsseg4e32_v_cg.set_inst_name("obj_MisalignedV_vlsseg4e32_v");
    MisalignedV_vlsseg4e64_v_cg = new(); MisalignedV_vlsseg4e64_v_cg.set_inst_name("obj_MisalignedV_vlsseg4e64_v");
    MisalignedV_vlsseg4e8_v_cg = new(); MisalignedV_vlsseg4e8_v_cg.set_inst_name("obj_MisalignedV_vlsseg4e8_v");
    MisalignedV_vlsseg5e16_v_cg = new(); MisalignedV_vlsseg5e16_v_cg.set_inst_name("obj_MisalignedV_vlsseg5e16_v");
    MisalignedV_vlsseg5e32_v_cg = new(); MisalignedV_vlsseg5e32_v_cg.set_inst_name("obj_MisalignedV_vlsseg5e32_v");
    MisalignedV_vlsseg5e64_v_cg = new(); MisalignedV_vlsseg5e64_v_cg.set_inst_name("obj_MisalignedV_vlsseg5e64_v");
    MisalignedV_vlsseg5e8_v_cg = new(); MisalignedV_vlsseg5e8_v_cg.set_inst_name("obj_MisalignedV_vlsseg5e8_v");
    MisalignedV_vlsseg6e16_v_cg = new(); MisalignedV_vlsseg6e16_v_cg.set_inst_name("obj_MisalignedV_vlsseg6e16_v");
    MisalignedV_vlsseg6e32_v_cg = new(); MisalignedV_vlsseg6e32_v_cg.set_inst_name("obj_MisalignedV_vlsseg6e32_v");
    MisalignedV_vlsseg6e64_v_cg = new(); MisalignedV_vlsseg6e64_v_cg.set_inst_name("obj_MisalignedV_vlsseg6e64_v");
    MisalignedV_vlsseg6e8_v_cg = new(); MisalignedV_vlsseg6e8_v_cg.set_inst_name("obj_MisalignedV_vlsseg6e8_v");
    MisalignedV_vlsseg7e16_v_cg = new(); MisalignedV_vlsseg7e16_v_cg.set_inst_name("obj_MisalignedV_vlsseg7e16_v");
    MisalignedV_vlsseg7e32_v_cg = new(); MisalignedV_vlsseg7e32_v_cg.set_inst_name("obj_MisalignedV_vlsseg7e32_v");
    MisalignedV_vlsseg7e64_v_cg = new(); MisalignedV_vlsseg7e64_v_cg.set_inst_name("obj_MisalignedV_vlsseg7e64_v");
    MisalignedV_vlsseg7e8_v_cg = new(); MisalignedV_vlsseg7e8_v_cg.set_inst_name("obj_MisalignedV_vlsseg7e8_v");
    MisalignedV_vlsseg8e16_v_cg = new(); MisalignedV_vlsseg8e16_v_cg.set_inst_name("obj_MisalignedV_vlsseg8e16_v");
    MisalignedV_vlsseg8e32_v_cg = new(); MisalignedV_vlsseg8e32_v_cg.set_inst_name("obj_MisalignedV_vlsseg8e32_v");
    MisalignedV_vlsseg8e64_v_cg = new(); MisalignedV_vlsseg8e64_v_cg.set_inst_name("obj_MisalignedV_vlsseg8e64_v");
    MisalignedV_vlsseg8e8_v_cg = new(); MisalignedV_vlsseg8e8_v_cg.set_inst_name("obj_MisalignedV_vlsseg8e8_v");
    MisalignedV_vluxei16_v_cg = new(); MisalignedV_vluxei16_v_cg.set_inst_name("obj_MisalignedV_vluxei16_v");
    MisalignedV_vluxei32_v_cg = new(); MisalignedV_vluxei32_v_cg.set_inst_name("obj_MisalignedV_vluxei32_v");
`ifdef XLEN64
    MisalignedV_vluxei64_v_cg = new(); MisalignedV_vluxei64_v_cg.set_inst_name("obj_MisalignedV_vluxei64_v");
`endif
    MisalignedV_vluxei8_v_cg = new(); MisalignedV_vluxei8_v_cg.set_inst_name("obj_MisalignedV_vluxei8_v");
    MisalignedV_vluxseg2ei16_v_cg = new(); MisalignedV_vluxseg2ei16_v_cg.set_inst_name("obj_MisalignedV_vluxseg2ei16_v");
    MisalignedV_vluxseg2ei32_v_cg = new(); MisalignedV_vluxseg2ei32_v_cg.set_inst_name("obj_MisalignedV_vluxseg2ei32_v");
`ifdef XLEN64
    MisalignedV_vluxseg2ei64_v_cg = new(); MisalignedV_vluxseg2ei64_v_cg.set_inst_name("obj_MisalignedV_vluxseg2ei64_v");
`endif
    MisalignedV_vluxseg2ei8_v_cg = new(); MisalignedV_vluxseg2ei8_v_cg.set_inst_name("obj_MisalignedV_vluxseg2ei8_v");
    MisalignedV_vluxseg3ei16_v_cg = new(); MisalignedV_vluxseg3ei16_v_cg.set_inst_name("obj_MisalignedV_vluxseg3ei16_v");
    MisalignedV_vluxseg3ei32_v_cg = new(); MisalignedV_vluxseg3ei32_v_cg.set_inst_name("obj_MisalignedV_vluxseg3ei32_v");
`ifdef XLEN64
    MisalignedV_vluxseg3ei64_v_cg = new(); MisalignedV_vluxseg3ei64_v_cg.set_inst_name("obj_MisalignedV_vluxseg3ei64_v");
`endif
    MisalignedV_vluxseg3ei8_v_cg = new(); MisalignedV_vluxseg3ei8_v_cg.set_inst_name("obj_MisalignedV_vluxseg3ei8_v");
    MisalignedV_vluxseg4ei16_v_cg = new(); MisalignedV_vluxseg4ei16_v_cg.set_inst_name("obj_MisalignedV_vluxseg4ei16_v");
    MisalignedV_vluxseg4ei32_v_cg = new(); MisalignedV_vluxseg4ei32_v_cg.set_inst_name("obj_MisalignedV_vluxseg4ei32_v");
`ifdef XLEN64
    MisalignedV_vluxseg4ei64_v_cg = new(); MisalignedV_vluxseg4ei64_v_cg.set_inst_name("obj_MisalignedV_vluxseg4ei64_v");
`endif
    MisalignedV_vluxseg4ei8_v_cg = new(); MisalignedV_vluxseg4ei8_v_cg.set_inst_name("obj_MisalignedV_vluxseg4ei8_v");
    MisalignedV_vluxseg5ei16_v_cg = new(); MisalignedV_vluxseg5ei16_v_cg.set_inst_name("obj_MisalignedV_vluxseg5ei16_v");
    MisalignedV_vluxseg5ei32_v_cg = new(); MisalignedV_vluxseg5ei32_v_cg.set_inst_name("obj_MisalignedV_vluxseg5ei32_v");
`ifdef XLEN64
    MisalignedV_vluxseg5ei64_v_cg = new(); MisalignedV_vluxseg5ei64_v_cg.set_inst_name("obj_MisalignedV_vluxseg5ei64_v");
`endif
    MisalignedV_vluxseg5ei8_v_cg = new(); MisalignedV_vluxseg5ei8_v_cg.set_inst_name("obj_MisalignedV_vluxseg5ei8_v");
    MisalignedV_vluxseg6ei16_v_cg = new(); MisalignedV_vluxseg6ei16_v_cg.set_inst_name("obj_MisalignedV_vluxseg6ei16_v");
    MisalignedV_vluxseg6ei32_v_cg = new(); MisalignedV_vluxseg6ei32_v_cg.set_inst_name("obj_MisalignedV_vluxseg6ei32_v");
`ifdef XLEN64
    MisalignedV_vluxseg6ei64_v_cg = new(); MisalignedV_vluxseg6ei64_v_cg.set_inst_name("obj_MisalignedV_vluxseg6ei64_v");
`endif
    MisalignedV_vluxseg6ei8_v_cg = new(); MisalignedV_vluxseg6ei8_v_cg.set_inst_name("obj_MisalignedV_vluxseg6ei8_v");
    MisalignedV_vluxseg7ei16_v_cg = new(); MisalignedV_vluxseg7ei16_v_cg.set_inst_name("obj_MisalignedV_vluxseg7ei16_v");
    MisalignedV_vluxseg7ei32_v_cg = new(); MisalignedV_vluxseg7ei32_v_cg.set_inst_name("obj_MisalignedV_vluxseg7ei32_v");
`ifdef XLEN64
    MisalignedV_vluxseg7ei64_v_cg = new(); MisalignedV_vluxseg7ei64_v_cg.set_inst_name("obj_MisalignedV_vluxseg7ei64_v");
`endif
    MisalignedV_vluxseg7ei8_v_cg = new(); MisalignedV_vluxseg7ei8_v_cg.set_inst_name("obj_MisalignedV_vluxseg7ei8_v");
    MisalignedV_vluxseg8ei16_v_cg = new(); MisalignedV_vluxseg8ei16_v_cg.set_inst_name("obj_MisalignedV_vluxseg8ei16_v");
    MisalignedV_vluxseg8ei32_v_cg = new(); MisalignedV_vluxseg8ei32_v_cg.set_inst_name("obj_MisalignedV_vluxseg8ei32_v");
`ifdef XLEN64
    MisalignedV_vluxseg8ei64_v_cg = new(); MisalignedV_vluxseg8ei64_v_cg.set_inst_name("obj_MisalignedV_vluxseg8ei64_v");
`endif
    MisalignedV_vluxseg8ei8_v_cg = new(); MisalignedV_vluxseg8ei8_v_cg.set_inst_name("obj_MisalignedV_vluxseg8ei8_v");
    MisalignedV_vs1r_v_cg = new(); MisalignedV_vs1r_v_cg.set_inst_name("obj_MisalignedV_vs1r_v");
    MisalignedV_vs2r_v_cg = new(); MisalignedV_vs2r_v_cg.set_inst_name("obj_MisalignedV_vs2r_v");
    MisalignedV_vs4r_v_cg = new(); MisalignedV_vs4r_v_cg.set_inst_name("obj_MisalignedV_vs4r_v");
    MisalignedV_vs8r_v_cg = new(); MisalignedV_vs8r_v_cg.set_inst_name("obj_MisalignedV_vs8r_v");
    MisalignedV_vse16_v_cg = new(); MisalignedV_vse16_v_cg.set_inst_name("obj_MisalignedV_vse16_v");
    MisalignedV_vse32_v_cg = new(); MisalignedV_vse32_v_cg.set_inst_name("obj_MisalignedV_vse32_v");
    MisalignedV_vse64_v_cg = new(); MisalignedV_vse64_v_cg.set_inst_name("obj_MisalignedV_vse64_v");
    MisalignedV_vse8_v_cg = new(); MisalignedV_vse8_v_cg.set_inst_name("obj_MisalignedV_vse8_v");
    MisalignedV_vsm_v_cg = new(); MisalignedV_vsm_v_cg.set_inst_name("obj_MisalignedV_vsm_v");
    MisalignedV_vsoxei16_v_cg = new(); MisalignedV_vsoxei16_v_cg.set_inst_name("obj_MisalignedV_vsoxei16_v");
    MisalignedV_vsoxei32_v_cg = new(); MisalignedV_vsoxei32_v_cg.set_inst_name("obj_MisalignedV_vsoxei32_v");
`ifdef XLEN64
    MisalignedV_vsoxei64_v_cg = new(); MisalignedV_vsoxei64_v_cg.set_inst_name("obj_MisalignedV_vsoxei64_v");
`endif
    MisalignedV_vsoxei8_v_cg = new(); MisalignedV_vsoxei8_v_cg.set_inst_name("obj_MisalignedV_vsoxei8_v");
    MisalignedV_vsoxseg2ei16_v_cg = new(); MisalignedV_vsoxseg2ei16_v_cg.set_inst_name("obj_MisalignedV_vsoxseg2ei16_v");
    MisalignedV_vsoxseg2ei32_v_cg = new(); MisalignedV_vsoxseg2ei32_v_cg.set_inst_name("obj_MisalignedV_vsoxseg2ei32_v");
`ifdef XLEN64
    MisalignedV_vsoxseg2ei64_v_cg = new(); MisalignedV_vsoxseg2ei64_v_cg.set_inst_name("obj_MisalignedV_vsoxseg2ei64_v");
`endif
    MisalignedV_vsoxseg2ei8_v_cg = new(); MisalignedV_vsoxseg2ei8_v_cg.set_inst_name("obj_MisalignedV_vsoxseg2ei8_v");
    MisalignedV_vsoxseg3ei16_v_cg = new(); MisalignedV_vsoxseg3ei16_v_cg.set_inst_name("obj_MisalignedV_vsoxseg3ei16_v");
    MisalignedV_vsoxseg3ei32_v_cg = new(); MisalignedV_vsoxseg3ei32_v_cg.set_inst_name("obj_MisalignedV_vsoxseg3ei32_v");
`ifdef XLEN64
    MisalignedV_vsoxseg3ei64_v_cg = new(); MisalignedV_vsoxseg3ei64_v_cg.set_inst_name("obj_MisalignedV_vsoxseg3ei64_v");
`endif
    MisalignedV_vsoxseg3ei8_v_cg = new(); MisalignedV_vsoxseg3ei8_v_cg.set_inst_name("obj_MisalignedV_vsoxseg3ei8_v");
    MisalignedV_vsoxseg4ei16_v_cg = new(); MisalignedV_vsoxseg4ei16_v_cg.set_inst_name("obj_MisalignedV_vsoxseg4ei16_v");
    MisalignedV_vsoxseg4ei32_v_cg = new(); MisalignedV_vsoxseg4ei32_v_cg.set_inst_name("obj_MisalignedV_vsoxseg4ei32_v");
`ifdef XLEN64
    MisalignedV_vsoxseg4ei64_v_cg = new(); MisalignedV_vsoxseg4ei64_v_cg.set_inst_name("obj_MisalignedV_vsoxseg4ei64_v");
`endif
    MisalignedV_vsoxseg4ei8_v_cg = new(); MisalignedV_vsoxseg4ei8_v_cg.set_inst_name("obj_MisalignedV_vsoxseg4ei8_v");
    MisalignedV_vsoxseg5ei16_v_cg = new(); MisalignedV_vsoxseg5ei16_v_cg.set_inst_name("obj_MisalignedV_vsoxseg5ei16_v");
    MisalignedV_vsoxseg5ei32_v_cg = new(); MisalignedV_vsoxseg5ei32_v_cg.set_inst_name("obj_MisalignedV_vsoxseg5ei32_v");
`ifdef XLEN64
    MisalignedV_vsoxseg5ei64_v_cg = new(); MisalignedV_vsoxseg5ei64_v_cg.set_inst_name("obj_MisalignedV_vsoxseg5ei64_v");
`endif
    MisalignedV_vsoxseg5ei8_v_cg = new(); MisalignedV_vsoxseg5ei8_v_cg.set_inst_name("obj_MisalignedV_vsoxseg5ei8_v");
    MisalignedV_vsoxseg6ei16_v_cg = new(); MisalignedV_vsoxseg6ei16_v_cg.set_inst_name("obj_MisalignedV_vsoxseg6ei16_v");
    MisalignedV_vsoxseg6ei32_v_cg = new(); MisalignedV_vsoxseg6ei32_v_cg.set_inst_name("obj_MisalignedV_vsoxseg6ei32_v");
`ifdef XLEN64
    MisalignedV_vsoxseg6ei64_v_cg = new(); MisalignedV_vsoxseg6ei64_v_cg.set_inst_name("obj_MisalignedV_vsoxseg6ei64_v");
`endif
    MisalignedV_vsoxseg6ei8_v_cg = new(); MisalignedV_vsoxseg6ei8_v_cg.set_inst_name("obj_MisalignedV_vsoxseg6ei8_v");
    MisalignedV_vsoxseg7ei16_v_cg = new(); MisalignedV_vsoxseg7ei16_v_cg.set_inst_name("obj_MisalignedV_vsoxseg7ei16_v");
    MisalignedV_vsoxseg7ei32_v_cg = new(); MisalignedV_vsoxseg7ei32_v_cg.set_inst_name("obj_MisalignedV_vsoxseg7ei32_v");
`ifdef XLEN64
    MisalignedV_vsoxseg7ei64_v_cg = new(); MisalignedV_vsoxseg7ei64_v_cg.set_inst_name("obj_MisalignedV_vsoxseg7ei64_v");
`endif
    MisalignedV_vsoxseg7ei8_v_cg = new(); MisalignedV_vsoxseg7ei8_v_cg.set_inst_name("obj_MisalignedV_vsoxseg7ei8_v");
    MisalignedV_vsoxseg8ei16_v_cg = new(); MisalignedV_vsoxseg8ei16_v_cg.set_inst_name("obj_MisalignedV_vsoxseg8ei16_v");
    MisalignedV_vsoxseg8ei32_v_cg = new(); MisalignedV_vsoxseg8ei32_v_cg.set_inst_name("obj_MisalignedV_vsoxseg8ei32_v");
`ifdef XLEN64
    MisalignedV_vsoxseg8ei64_v_cg = new(); MisalignedV_vsoxseg8ei64_v_cg.set_inst_name("obj_MisalignedV_vsoxseg8ei64_v");
`endif
    MisalignedV_vsoxseg8ei8_v_cg = new(); MisalignedV_vsoxseg8ei8_v_cg.set_inst_name("obj_MisalignedV_vsoxseg8ei8_v");
    MisalignedV_vsse16_v_cg = new(); MisalignedV_vsse16_v_cg.set_inst_name("obj_MisalignedV_vsse16_v");
    MisalignedV_vsse32_v_cg = new(); MisalignedV_vsse32_v_cg.set_inst_name("obj_MisalignedV_vsse32_v");
    MisalignedV_vsse64_v_cg = new(); MisalignedV_vsse64_v_cg.set_inst_name("obj_MisalignedV_vsse64_v");
    MisalignedV_vsse8_v_cg = new(); MisalignedV_vsse8_v_cg.set_inst_name("obj_MisalignedV_vsse8_v");
    MisalignedV_vsseg2e16_v_cg = new(); MisalignedV_vsseg2e16_v_cg.set_inst_name("obj_MisalignedV_vsseg2e16_v");
    MisalignedV_vsseg2e32_v_cg = new(); MisalignedV_vsseg2e32_v_cg.set_inst_name("obj_MisalignedV_vsseg2e32_v");
    MisalignedV_vsseg2e64_v_cg = new(); MisalignedV_vsseg2e64_v_cg.set_inst_name("obj_MisalignedV_vsseg2e64_v");
    MisalignedV_vsseg2e8_v_cg = new(); MisalignedV_vsseg2e8_v_cg.set_inst_name("obj_MisalignedV_vsseg2e8_v");
    MisalignedV_vsseg3e16_v_cg = new(); MisalignedV_vsseg3e16_v_cg.set_inst_name("obj_MisalignedV_vsseg3e16_v");
    MisalignedV_vsseg3e32_v_cg = new(); MisalignedV_vsseg3e32_v_cg.set_inst_name("obj_MisalignedV_vsseg3e32_v");
    MisalignedV_vsseg3e64_v_cg = new(); MisalignedV_vsseg3e64_v_cg.set_inst_name("obj_MisalignedV_vsseg3e64_v");
    MisalignedV_vsseg3e8_v_cg = new(); MisalignedV_vsseg3e8_v_cg.set_inst_name("obj_MisalignedV_vsseg3e8_v");
    MisalignedV_vsseg4e16_v_cg = new(); MisalignedV_vsseg4e16_v_cg.set_inst_name("obj_MisalignedV_vsseg4e16_v");
    MisalignedV_vsseg4e32_v_cg = new(); MisalignedV_vsseg4e32_v_cg.set_inst_name("obj_MisalignedV_vsseg4e32_v");
    MisalignedV_vsseg4e64_v_cg = new(); MisalignedV_vsseg4e64_v_cg.set_inst_name("obj_MisalignedV_vsseg4e64_v");
    MisalignedV_vsseg4e8_v_cg = new(); MisalignedV_vsseg4e8_v_cg.set_inst_name("obj_MisalignedV_vsseg4e8_v");
    MisalignedV_vsseg5e16_v_cg = new(); MisalignedV_vsseg5e16_v_cg.set_inst_name("obj_MisalignedV_vsseg5e16_v");
    MisalignedV_vsseg5e32_v_cg = new(); MisalignedV_vsseg5e32_v_cg.set_inst_name("obj_MisalignedV_vsseg5e32_v");
    MisalignedV_vsseg5e64_v_cg = new(); MisalignedV_vsseg5e64_v_cg.set_inst_name("obj_MisalignedV_vsseg5e64_v");
    MisalignedV_vsseg5e8_v_cg = new(); MisalignedV_vsseg5e8_v_cg.set_inst_name("obj_MisalignedV_vsseg5e8_v");
    MisalignedV_vsseg6e16_v_cg = new(); MisalignedV_vsseg6e16_v_cg.set_inst_name("obj_MisalignedV_vsseg6e16_v");
    MisalignedV_vsseg6e32_v_cg = new(); MisalignedV_vsseg6e32_v_cg.set_inst_name("obj_MisalignedV_vsseg6e32_v");
    MisalignedV_vsseg6e64_v_cg = new(); MisalignedV_vsseg6e64_v_cg.set_inst_name("obj_MisalignedV_vsseg6e64_v");
    MisalignedV_vsseg6e8_v_cg = new(); MisalignedV_vsseg6e8_v_cg.set_inst_name("obj_MisalignedV_vsseg6e8_v");
    MisalignedV_vsseg7e16_v_cg = new(); MisalignedV_vsseg7e16_v_cg.set_inst_name("obj_MisalignedV_vsseg7e16_v");
    MisalignedV_vsseg7e32_v_cg = new(); MisalignedV_vsseg7e32_v_cg.set_inst_name("obj_MisalignedV_vsseg7e32_v");
    MisalignedV_vsseg7e64_v_cg = new(); MisalignedV_vsseg7e64_v_cg.set_inst_name("obj_MisalignedV_vsseg7e64_v");
    MisalignedV_vsseg7e8_v_cg = new(); MisalignedV_vsseg7e8_v_cg.set_inst_name("obj_MisalignedV_vsseg7e8_v");
    MisalignedV_vsseg8e16_v_cg = new(); MisalignedV_vsseg8e16_v_cg.set_inst_name("obj_MisalignedV_vsseg8e16_v");
    MisalignedV_vsseg8e32_v_cg = new(); MisalignedV_vsseg8e32_v_cg.set_inst_name("obj_MisalignedV_vsseg8e32_v");
    MisalignedV_vsseg8e64_v_cg = new(); MisalignedV_vsseg8e64_v_cg.set_inst_name("obj_MisalignedV_vsseg8e64_v");
    MisalignedV_vsseg8e8_v_cg = new(); MisalignedV_vsseg8e8_v_cg.set_inst_name("obj_MisalignedV_vsseg8e8_v");
    MisalignedV_vssseg2e16_v_cg = new(); MisalignedV_vssseg2e16_v_cg.set_inst_name("obj_MisalignedV_vssseg2e16_v");
    MisalignedV_vssseg2e32_v_cg = new(); MisalignedV_vssseg2e32_v_cg.set_inst_name("obj_MisalignedV_vssseg2e32_v");
    MisalignedV_vssseg2e64_v_cg = new(); MisalignedV_vssseg2e64_v_cg.set_inst_name("obj_MisalignedV_vssseg2e64_v");
    MisalignedV_vssseg2e8_v_cg = new(); MisalignedV_vssseg2e8_v_cg.set_inst_name("obj_MisalignedV_vssseg2e8_v");
    MisalignedV_vssseg3e16_v_cg = new(); MisalignedV_vssseg3e16_v_cg.set_inst_name("obj_MisalignedV_vssseg3e16_v");
    MisalignedV_vssseg3e32_v_cg = new(); MisalignedV_vssseg3e32_v_cg.set_inst_name("obj_MisalignedV_vssseg3e32_v");
    MisalignedV_vssseg3e64_v_cg = new(); MisalignedV_vssseg3e64_v_cg.set_inst_name("obj_MisalignedV_vssseg3e64_v");
    MisalignedV_vssseg3e8_v_cg = new(); MisalignedV_vssseg3e8_v_cg.set_inst_name("obj_MisalignedV_vssseg3e8_v");
    MisalignedV_vssseg4e16_v_cg = new(); MisalignedV_vssseg4e16_v_cg.set_inst_name("obj_MisalignedV_vssseg4e16_v");
    MisalignedV_vssseg4e32_v_cg = new(); MisalignedV_vssseg4e32_v_cg.set_inst_name("obj_MisalignedV_vssseg4e32_v");
    MisalignedV_vssseg4e64_v_cg = new(); MisalignedV_vssseg4e64_v_cg.set_inst_name("obj_MisalignedV_vssseg4e64_v");
    MisalignedV_vssseg4e8_v_cg = new(); MisalignedV_vssseg4e8_v_cg.set_inst_name("obj_MisalignedV_vssseg4e8_v");
    MisalignedV_vssseg5e16_v_cg = new(); MisalignedV_vssseg5e16_v_cg.set_inst_name("obj_MisalignedV_vssseg5e16_v");
    MisalignedV_vssseg5e32_v_cg = new(); MisalignedV_vssseg5e32_v_cg.set_inst_name("obj_MisalignedV_vssseg5e32_v");
    MisalignedV_vssseg5e64_v_cg = new(); MisalignedV_vssseg5e64_v_cg.set_inst_name("obj_MisalignedV_vssseg5e64_v");
    MisalignedV_vssseg5e8_v_cg = new(); MisalignedV_vssseg5e8_v_cg.set_inst_name("obj_MisalignedV_vssseg5e8_v");
    MisalignedV_vssseg6e16_v_cg = new(); MisalignedV_vssseg6e16_v_cg.set_inst_name("obj_MisalignedV_vssseg6e16_v");
    MisalignedV_vssseg6e32_v_cg = new(); MisalignedV_vssseg6e32_v_cg.set_inst_name("obj_MisalignedV_vssseg6e32_v");
    MisalignedV_vssseg6e64_v_cg = new(); MisalignedV_vssseg6e64_v_cg.set_inst_name("obj_MisalignedV_vssseg6e64_v");
    MisalignedV_vssseg6e8_v_cg = new(); MisalignedV_vssseg6e8_v_cg.set_inst_name("obj_MisalignedV_vssseg6e8_v");
    MisalignedV_vssseg7e16_v_cg = new(); MisalignedV_vssseg7e16_v_cg.set_inst_name("obj_MisalignedV_vssseg7e16_v");
    MisalignedV_vssseg7e32_v_cg = new(); MisalignedV_vssseg7e32_v_cg.set_inst_name("obj_MisalignedV_vssseg7e32_v");
    MisalignedV_vssseg7e64_v_cg = new(); MisalignedV_vssseg7e64_v_cg.set_inst_name("obj_MisalignedV_vssseg7e64_v");
    MisalignedV_vssseg7e8_v_cg = new(); MisalignedV_vssseg7e8_v_cg.set_inst_name("obj_MisalignedV_vssseg7e8_v");
    MisalignedV_vssseg8e16_v_cg = new(); MisalignedV_vssseg8e16_v_cg.set_inst_name("obj_MisalignedV_vssseg8e16_v");
    MisalignedV_vssseg8e32_v_cg = new(); MisalignedV_vssseg8e32_v_cg.set_inst_name("obj_MisalignedV_vssseg8e32_v");
    MisalignedV_vssseg8e64_v_cg = new(); MisalignedV_vssseg8e64_v_cg.set_inst_name("obj_MisalignedV_vssseg8e64_v");
    MisalignedV_vssseg8e8_v_cg = new(); MisalignedV_vssseg8e8_v_cg.set_inst_name("obj_MisalignedV_vssseg8e8_v");
    MisalignedV_vsuxei16_v_cg = new(); MisalignedV_vsuxei16_v_cg.set_inst_name("obj_MisalignedV_vsuxei16_v");
    MisalignedV_vsuxei32_v_cg = new(); MisalignedV_vsuxei32_v_cg.set_inst_name("obj_MisalignedV_vsuxei32_v");
`ifdef XLEN64
    MisalignedV_vsuxei64_v_cg = new(); MisalignedV_vsuxei64_v_cg.set_inst_name("obj_MisalignedV_vsuxei64_v");
`endif
    MisalignedV_vsuxei8_v_cg = new(); MisalignedV_vsuxei8_v_cg.set_inst_name("obj_MisalignedV_vsuxei8_v");
    MisalignedV_vsuxseg2ei16_v_cg = new(); MisalignedV_vsuxseg2ei16_v_cg.set_inst_name("obj_MisalignedV_vsuxseg2ei16_v");
    MisalignedV_vsuxseg2ei32_v_cg = new(); MisalignedV_vsuxseg2ei32_v_cg.set_inst_name("obj_MisalignedV_vsuxseg2ei32_v");
`ifdef XLEN64
    MisalignedV_vsuxseg2ei64_v_cg = new(); MisalignedV_vsuxseg2ei64_v_cg.set_inst_name("obj_MisalignedV_vsuxseg2ei64_v");
`endif
    MisalignedV_vsuxseg2ei8_v_cg = new(); MisalignedV_vsuxseg2ei8_v_cg.set_inst_name("obj_MisalignedV_vsuxseg2ei8_v");
    MisalignedV_vsuxseg3ei16_v_cg = new(); MisalignedV_vsuxseg3ei16_v_cg.set_inst_name("obj_MisalignedV_vsuxseg3ei16_v");
    MisalignedV_vsuxseg3ei32_v_cg = new(); MisalignedV_vsuxseg3ei32_v_cg.set_inst_name("obj_MisalignedV_vsuxseg3ei32_v");
`ifdef XLEN64
    MisalignedV_vsuxseg3ei64_v_cg = new(); MisalignedV_vsuxseg3ei64_v_cg.set_inst_name("obj_MisalignedV_vsuxseg3ei64_v");
`endif
    MisalignedV_vsuxseg3ei8_v_cg = new(); MisalignedV_vsuxseg3ei8_v_cg.set_inst_name("obj_MisalignedV_vsuxseg3ei8_v");
    MisalignedV_vsuxseg4ei16_v_cg = new(); MisalignedV_vsuxseg4ei16_v_cg.set_inst_name("obj_MisalignedV_vsuxseg4ei16_v");
    MisalignedV_vsuxseg4ei32_v_cg = new(); MisalignedV_vsuxseg4ei32_v_cg.set_inst_name("obj_MisalignedV_vsuxseg4ei32_v");
`ifdef XLEN64
    MisalignedV_vsuxseg4ei64_v_cg = new(); MisalignedV_vsuxseg4ei64_v_cg.set_inst_name("obj_MisalignedV_vsuxseg4ei64_v");
`endif
    MisalignedV_vsuxseg4ei8_v_cg = new(); MisalignedV_vsuxseg4ei8_v_cg.set_inst_name("obj_MisalignedV_vsuxseg4ei8_v");
    MisalignedV_vsuxseg5ei16_v_cg = new(); MisalignedV_vsuxseg5ei16_v_cg.set_inst_name("obj_MisalignedV_vsuxseg5ei16_v");
    MisalignedV_vsuxseg5ei32_v_cg = new(); MisalignedV_vsuxseg5ei32_v_cg.set_inst_name("obj_MisalignedV_vsuxseg5ei32_v");
`ifdef XLEN64
    MisalignedV_vsuxseg5ei64_v_cg = new(); MisalignedV_vsuxseg5ei64_v_cg.set_inst_name("obj_MisalignedV_vsuxseg5ei64_v");
`endif
    MisalignedV_vsuxseg5ei8_v_cg = new(); MisalignedV_vsuxseg5ei8_v_cg.set_inst_name("obj_MisalignedV_vsuxseg5ei8_v");
    MisalignedV_vsuxseg6ei16_v_cg = new(); MisalignedV_vsuxseg6ei16_v_cg.set_inst_name("obj_MisalignedV_vsuxseg6ei16_v");
    MisalignedV_vsuxseg6ei32_v_cg = new(); MisalignedV_vsuxseg6ei32_v_cg.set_inst_name("obj_MisalignedV_vsuxseg6ei32_v");
`ifdef XLEN64
    MisalignedV_vsuxseg6ei64_v_cg = new(); MisalignedV_vsuxseg6ei64_v_cg.set_inst_name("obj_MisalignedV_vsuxseg6ei64_v");
`endif
    MisalignedV_vsuxseg6ei8_v_cg = new(); MisalignedV_vsuxseg6ei8_v_cg.set_inst_name("obj_MisalignedV_vsuxseg6ei8_v");
    MisalignedV_vsuxseg7ei16_v_cg = new(); MisalignedV_vsuxseg7ei16_v_cg.set_inst_name("obj_MisalignedV_vsuxseg7ei16_v");
    MisalignedV_vsuxseg7ei32_v_cg = new(); MisalignedV_vsuxseg7ei32_v_cg.set_inst_name("obj_MisalignedV_vsuxseg7ei32_v");
`ifdef XLEN64
    MisalignedV_vsuxseg7ei64_v_cg = new(); MisalignedV_vsuxseg7ei64_v_cg.set_inst_name("obj_MisalignedV_vsuxseg7ei64_v");
`endif
    MisalignedV_vsuxseg7ei8_v_cg = new(); MisalignedV_vsuxseg7ei8_v_cg.set_inst_name("obj_MisalignedV_vsuxseg7ei8_v");
    MisalignedV_vsuxseg8ei16_v_cg = new(); MisalignedV_vsuxseg8ei16_v_cg.set_inst_name("obj_MisalignedV_vsuxseg8ei16_v");
    MisalignedV_vsuxseg8ei32_v_cg = new(); MisalignedV_vsuxseg8ei32_v_cg.set_inst_name("obj_MisalignedV_vsuxseg8ei32_v");
`ifdef XLEN64
    MisalignedV_vsuxseg8ei64_v_cg = new(); MisalignedV_vsuxseg8ei64_v_cg.set_inst_name("obj_MisalignedV_vsuxseg8ei64_v");
`endif
    MisalignedV_vsuxseg8ei8_v_cg = new(); MisalignedV_vsuxseg8ei8_v_cg.set_inst_name("obj_MisalignedV_vsuxseg8ei8_v");
