///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    F_fadd_s_cg = new(); F_fadd_s_cg.set_inst_name("obj_F_fadd_s");
    F_fclass_s_cg = new(); F_fclass_s_cg.set_inst_name("obj_F_fclass_s");
    F_fcvt_s_w_cg = new(); F_fcvt_s_w_cg.set_inst_name("obj_F_fcvt_s_w");
    F_fcvt_s_wu_cg = new(); F_fcvt_s_wu_cg.set_inst_name("obj_F_fcvt_s_wu");
    F_fcvt_w_s_cg = new(); F_fcvt_w_s_cg.set_inst_name("obj_F_fcvt_w_s");
    F_fcvt_wu_s_cg = new(); F_fcvt_wu_s_cg.set_inst_name("obj_F_fcvt_wu_s");
    F_fdiv_s_cg = new(); F_fdiv_s_cg.set_inst_name("obj_F_fdiv_s");
    F_feq_s_cg = new(); F_feq_s_cg.set_inst_name("obj_F_feq_s");
    F_fle_s_cg = new(); F_fle_s_cg.set_inst_name("obj_F_fle_s");
    F_flt_s_cg = new(); F_flt_s_cg.set_inst_name("obj_F_flt_s");
    F_flw_cg = new(); F_flw_cg.set_inst_name("obj_F_flw");
    F_fmadd_s_cg = new(); F_fmadd_s_cg.set_inst_name("obj_F_fmadd_s");
    F_fmax_s_cg = new(); F_fmax_s_cg.set_inst_name("obj_F_fmax_s");
    F_fmin_s_cg = new(); F_fmin_s_cg.set_inst_name("obj_F_fmin_s");
    F_fmsub_s_cg = new(); F_fmsub_s_cg.set_inst_name("obj_F_fmsub_s");
    F_fmul_s_cg = new(); F_fmul_s_cg.set_inst_name("obj_F_fmul_s");
    F_fmv_w_x_cg = new(); F_fmv_w_x_cg.set_inst_name("obj_F_fmv_w_x");
    F_fmv_x_w_cg = new(); F_fmv_x_w_cg.set_inst_name("obj_F_fmv_x_w");
    F_fnmadd_s_cg = new(); F_fnmadd_s_cg.set_inst_name("obj_F_fnmadd_s");
    F_fnmsub_s_cg = new(); F_fnmsub_s_cg.set_inst_name("obj_F_fnmsub_s");
    F_fsgnj_s_cg = new(); F_fsgnj_s_cg.set_inst_name("obj_F_fsgnj_s");
    F_fsgnjn_s_cg = new(); F_fsgnjn_s_cg.set_inst_name("obj_F_fsgnjn_s");
    F_fsgnjx_s_cg = new(); F_fsgnjx_s_cg.set_inst_name("obj_F_fsgnjx_s");
    F_fsqrt_s_cg = new(); F_fsqrt_s_cg.set_inst_name("obj_F_fsqrt_s");
    F_fsub_s_cg = new(); F_fsub_s_cg.set_inst_name("obj_F_fsub_s");
    F_fsw_cg = new(); F_fsw_cg.set_inst_name("obj_F_fsw");
`ifdef UDB_MXLEN_64
    F_fcvt_l_s_cg = new(); F_fcvt_l_s_cg.set_inst_name("obj_F_fcvt_l_s");
    F_fcvt_lu_s_cg = new(); F_fcvt_lu_s_cg.set_inst_name("obj_F_fcvt_lu_s");
    F_fcvt_s_l_cg = new(); F_fcvt_s_l_cg.set_inst_name("obj_F_fcvt_s_l");
    F_fcvt_s_lu_cg = new(); F_fcvt_s_lu_cg.set_inst_name("obj_F_fcvt_s_lu");
`endif
