///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    MisalignZca_c_lw_cg = new(); MisalignZca_c_lw_cg.set_inst_name("obj_MisalignZca_c_lw");
    MisalignZca_c_lwsp_cg = new(); MisalignZca_c_lwsp_cg.set_inst_name("obj_MisalignZca_c_lwsp");
    MisalignZca_c_sw_cg = new(); MisalignZca_c_sw_cg.set_inst_name("obj_MisalignZca_c_sw");
    MisalignZca_c_swsp_cg = new(); MisalignZca_c_swsp_cg.set_inst_name("obj_MisalignZca_c_swsp");
`ifdef UDB_MXLEN_64
    MisalignZca_c_ld_cg = new(); MisalignZca_c_ld_cg.set_inst_name("obj_MisalignZca_c_ld");
    MisalignZca_c_ldsp_cg = new(); MisalignZca_c_ldsp_cg.set_inst_name("obj_MisalignZca_c_ldsp");
    MisalignZca_c_sd_cg = new(); MisalignZca_c_sd_cg.set_inst_name("obj_MisalignZca_c_sd");
    MisalignZca_c_sdsp_cg = new(); MisalignZca_c_sdsp_cg.set_inst_name("obj_MisalignZca_c_sdsp");
`endif
