///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Misalign_lh_cg = new(); Misalign_lh_cg.set_inst_name("obj_Misalign_lh");
    Misalign_lhu_cg = new(); Misalign_lhu_cg.set_inst_name("obj_Misalign_lhu");
    Misalign_lw_cg = new(); Misalign_lw_cg.set_inst_name("obj_Misalign_lw");
    Misalign_sh_cg = new(); Misalign_sh_cg.set_inst_name("obj_Misalign_sh");
    Misalign_sw_cg = new(); Misalign_sw_cg.set_inst_name("obj_Misalign_sw");
`ifdef UDB_MXLEN_64
    Misalign_ld_cg = new(); Misalign_ld_cg.set_inst_name("obj_Misalign_ld");
    Misalign_lwu_cg = new(); Misalign_lwu_cg.set_inst_name("obj_Misalign_lwu");
    Misalign_sd_cg = new(); Misalign_sd_cg.set_inst_name("obj_Misalign_sd");
`endif
