///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Vf16_vfadd_vf_cg = new(); Vf16_vfadd_vf_cg.set_inst_name("obj_Vf16_vfadd_vf");
    Vf16_vfadd_vv_cg = new(); Vf16_vfadd_vv_cg.set_inst_name("obj_Vf16_vfadd_vv");
    Vf16_vfclass_v_cg = new(); Vf16_vfclass_v_cg.set_inst_name("obj_Vf16_vfclass_v");
    Vf16_vfcvt_f_x_v_cg = new(); Vf16_vfcvt_f_x_v_cg.set_inst_name("obj_Vf16_vfcvt_f_x_v");
    Vf16_vfcvt_f_xu_v_cg = new(); Vf16_vfcvt_f_xu_v_cg.set_inst_name("obj_Vf16_vfcvt_f_xu_v");
    Vf16_vfcvt_rtz_x_f_v_cg = new(); Vf16_vfcvt_rtz_x_f_v_cg.set_inst_name("obj_Vf16_vfcvt_rtz_x_f_v");
    Vf16_vfcvt_rtz_xu_f_v_cg = new(); Vf16_vfcvt_rtz_xu_f_v_cg.set_inst_name("obj_Vf16_vfcvt_rtz_xu_f_v");
    Vf16_vfcvt_x_f_v_cg = new(); Vf16_vfcvt_x_f_v_cg.set_inst_name("obj_Vf16_vfcvt_x_f_v");
    Vf16_vfcvt_xu_f_v_cg = new(); Vf16_vfcvt_xu_f_v_cg.set_inst_name("obj_Vf16_vfcvt_xu_f_v");
    Vf16_vfdiv_vf_cg = new(); Vf16_vfdiv_vf_cg.set_inst_name("obj_Vf16_vfdiv_vf");
    Vf16_vfdiv_vv_cg = new(); Vf16_vfdiv_vv_cg.set_inst_name("obj_Vf16_vfdiv_vv");
    Vf16_vfmacc_vf_cg = new(); Vf16_vfmacc_vf_cg.set_inst_name("obj_Vf16_vfmacc_vf");
    Vf16_vfmacc_vv_cg = new(); Vf16_vfmacc_vv_cg.set_inst_name("obj_Vf16_vfmacc_vv");
    Vf16_vfmadd_vf_cg = new(); Vf16_vfmadd_vf_cg.set_inst_name("obj_Vf16_vfmadd_vf");
    Vf16_vfmadd_vv_cg = new(); Vf16_vfmadd_vv_cg.set_inst_name("obj_Vf16_vfmadd_vv");
    Vf16_vfmax_vf_cg = new(); Vf16_vfmax_vf_cg.set_inst_name("obj_Vf16_vfmax_vf");
    Vf16_vfmax_vv_cg = new(); Vf16_vfmax_vv_cg.set_inst_name("obj_Vf16_vfmax_vv");
    Vf16_vfmerge_vfm_cg = new(); Vf16_vfmerge_vfm_cg.set_inst_name("obj_Vf16_vfmerge_vfm");
    Vf16_vfmin_vf_cg = new(); Vf16_vfmin_vf_cg.set_inst_name("obj_Vf16_vfmin_vf");
    Vf16_vfmin_vv_cg = new(); Vf16_vfmin_vv_cg.set_inst_name("obj_Vf16_vfmin_vv");
    Vf16_vfmsac_vf_cg = new(); Vf16_vfmsac_vf_cg.set_inst_name("obj_Vf16_vfmsac_vf");
    Vf16_vfmsac_vv_cg = new(); Vf16_vfmsac_vv_cg.set_inst_name("obj_Vf16_vfmsac_vv");
    Vf16_vfmsub_vf_cg = new(); Vf16_vfmsub_vf_cg.set_inst_name("obj_Vf16_vfmsub_vf");
    Vf16_vfmsub_vv_cg = new(); Vf16_vfmsub_vv_cg.set_inst_name("obj_Vf16_vfmsub_vv");
    Vf16_vfmul_vf_cg = new(); Vf16_vfmul_vf_cg.set_inst_name("obj_Vf16_vfmul_vf");
    Vf16_vfmul_vv_cg = new(); Vf16_vfmul_vv_cg.set_inst_name("obj_Vf16_vfmul_vv");
    Vf16_vfmv_f_s_cg = new(); Vf16_vfmv_f_s_cg.set_inst_name("obj_Vf16_vfmv_f_s");
    Vf16_vfmv_s_f_cg = new(); Vf16_vfmv_s_f_cg.set_inst_name("obj_Vf16_vfmv_s_f");
    Vf16_vfmv_v_f_cg = new(); Vf16_vfmv_v_f_cg.set_inst_name("obj_Vf16_vfmv_v_f");
    Vf16_vfncvt_f_x_w_cg = new(); Vf16_vfncvt_f_x_w_cg.set_inst_name("obj_Vf16_vfncvt_f_x_w");
    Vf16_vfncvt_f_xu_w_cg = new(); Vf16_vfncvt_f_xu_w_cg.set_inst_name("obj_Vf16_vfncvt_f_xu_w");
    Vf16_vfncvt_rod_f_f_w_cg = new(); Vf16_vfncvt_rod_f_f_w_cg.set_inst_name("obj_Vf16_vfncvt_rod_f_f_w");
    Vf16_vfncvt_rtz_x_f_w_cg = new(); Vf16_vfncvt_rtz_x_f_w_cg.set_inst_name("obj_Vf16_vfncvt_rtz_x_f_w");
    Vf16_vfncvt_rtz_xu_f_w_cg = new(); Vf16_vfncvt_rtz_xu_f_w_cg.set_inst_name("obj_Vf16_vfncvt_rtz_xu_f_w");
    Vf16_vfncvt_x_f_w_cg = new(); Vf16_vfncvt_x_f_w_cg.set_inst_name("obj_Vf16_vfncvt_x_f_w");
    Vf16_vfncvt_xu_f_w_cg = new(); Vf16_vfncvt_xu_f_w_cg.set_inst_name("obj_Vf16_vfncvt_xu_f_w");
    Vf16_vfnmacc_vf_cg = new(); Vf16_vfnmacc_vf_cg.set_inst_name("obj_Vf16_vfnmacc_vf");
    Vf16_vfnmacc_vv_cg = new(); Vf16_vfnmacc_vv_cg.set_inst_name("obj_Vf16_vfnmacc_vv");
    Vf16_vfnmadd_vf_cg = new(); Vf16_vfnmadd_vf_cg.set_inst_name("obj_Vf16_vfnmadd_vf");
    Vf16_vfnmadd_vv_cg = new(); Vf16_vfnmadd_vv_cg.set_inst_name("obj_Vf16_vfnmadd_vv");
    Vf16_vfnmsac_vf_cg = new(); Vf16_vfnmsac_vf_cg.set_inst_name("obj_Vf16_vfnmsac_vf");
    Vf16_vfnmsac_vv_cg = new(); Vf16_vfnmsac_vv_cg.set_inst_name("obj_Vf16_vfnmsac_vv");
    Vf16_vfnmsub_vf_cg = new(); Vf16_vfnmsub_vf_cg.set_inst_name("obj_Vf16_vfnmsub_vf");
    Vf16_vfnmsub_vv_cg = new(); Vf16_vfnmsub_vv_cg.set_inst_name("obj_Vf16_vfnmsub_vv");
    Vf16_vfrdiv_vf_cg = new(); Vf16_vfrdiv_vf_cg.set_inst_name("obj_Vf16_vfrdiv_vf");
    Vf16_vfrec7_v_cg = new(); Vf16_vfrec7_v_cg.set_inst_name("obj_Vf16_vfrec7_v");
    Vf16_vfredmax_vs_cg = new(); Vf16_vfredmax_vs_cg.set_inst_name("obj_Vf16_vfredmax_vs");
    Vf16_vfredmin_vs_cg = new(); Vf16_vfredmin_vs_cg.set_inst_name("obj_Vf16_vfredmin_vs");
    Vf16_vfredosum_vs_cg = new(); Vf16_vfredosum_vs_cg.set_inst_name("obj_Vf16_vfredosum_vs");
    Vf16_vfredusum_vs_cg = new(); Vf16_vfredusum_vs_cg.set_inst_name("obj_Vf16_vfredusum_vs");
    Vf16_vfrsqrt7_v_cg = new(); Vf16_vfrsqrt7_v_cg.set_inst_name("obj_Vf16_vfrsqrt7_v");
    Vf16_vfrsub_vf_cg = new(); Vf16_vfrsub_vf_cg.set_inst_name("obj_Vf16_vfrsub_vf");
    Vf16_vfsgnj_vf_cg = new(); Vf16_vfsgnj_vf_cg.set_inst_name("obj_Vf16_vfsgnj_vf");
    Vf16_vfsgnj_vv_cg = new(); Vf16_vfsgnj_vv_cg.set_inst_name("obj_Vf16_vfsgnj_vv");
    Vf16_vfsgnjn_vf_cg = new(); Vf16_vfsgnjn_vf_cg.set_inst_name("obj_Vf16_vfsgnjn_vf");
    Vf16_vfsgnjn_vv_cg = new(); Vf16_vfsgnjn_vv_cg.set_inst_name("obj_Vf16_vfsgnjn_vv");
    Vf16_vfsgnjx_vf_cg = new(); Vf16_vfsgnjx_vf_cg.set_inst_name("obj_Vf16_vfsgnjx_vf");
    Vf16_vfsgnjx_vv_cg = new(); Vf16_vfsgnjx_vv_cg.set_inst_name("obj_Vf16_vfsgnjx_vv");
    Vf16_vfslide1down_vf_cg = new(); Vf16_vfslide1down_vf_cg.set_inst_name("obj_Vf16_vfslide1down_vf");
    Vf16_vfslide1up_vf_cg = new(); Vf16_vfslide1up_vf_cg.set_inst_name("obj_Vf16_vfslide1up_vf");
    Vf16_vfsqrt_v_cg = new(); Vf16_vfsqrt_v_cg.set_inst_name("obj_Vf16_vfsqrt_v");
    Vf16_vfsub_vf_cg = new(); Vf16_vfsub_vf_cg.set_inst_name("obj_Vf16_vfsub_vf");
    Vf16_vfsub_vv_cg = new(); Vf16_vfsub_vv_cg.set_inst_name("obj_Vf16_vfsub_vv");
    Vf16_vfwadd_vf_cg = new(); Vf16_vfwadd_vf_cg.set_inst_name("obj_Vf16_vfwadd_vf");
    Vf16_vfwadd_vv_cg = new(); Vf16_vfwadd_vv_cg.set_inst_name("obj_Vf16_vfwadd_vv");
    Vf16_vfwadd_wf_cg = new(); Vf16_vfwadd_wf_cg.set_inst_name("obj_Vf16_vfwadd_wf");
    Vf16_vfwadd_wv_cg = new(); Vf16_vfwadd_wv_cg.set_inst_name("obj_Vf16_vfwadd_wv");
    Vf16_vfwcvt_f_f_v_cg = new(); Vf16_vfwcvt_f_f_v_cg.set_inst_name("obj_Vf16_vfwcvt_f_f_v");
    Vf16_vfwcvt_f_x_v_cg = new(); Vf16_vfwcvt_f_x_v_cg.set_inst_name("obj_Vf16_vfwcvt_f_x_v");
    Vf16_vfwcvt_f_xu_v_cg = new(); Vf16_vfwcvt_f_xu_v_cg.set_inst_name("obj_Vf16_vfwcvt_f_xu_v");
    Vf16_vfwcvt_rtz_x_f_v_cg = new(); Vf16_vfwcvt_rtz_x_f_v_cg.set_inst_name("obj_Vf16_vfwcvt_rtz_x_f_v");
    Vf16_vfwcvt_rtz_xu_f_v_cg = new(); Vf16_vfwcvt_rtz_xu_f_v_cg.set_inst_name("obj_Vf16_vfwcvt_rtz_xu_f_v");
    Vf16_vfwcvt_x_f_v_cg = new(); Vf16_vfwcvt_x_f_v_cg.set_inst_name("obj_Vf16_vfwcvt_x_f_v");
    Vf16_vfwcvt_xu_f_v_cg = new(); Vf16_vfwcvt_xu_f_v_cg.set_inst_name("obj_Vf16_vfwcvt_xu_f_v");
    Vf16_vfwmacc_vf_cg = new(); Vf16_vfwmacc_vf_cg.set_inst_name("obj_Vf16_vfwmacc_vf");
    Vf16_vfwmacc_vv_cg = new(); Vf16_vfwmacc_vv_cg.set_inst_name("obj_Vf16_vfwmacc_vv");
    Vf16_vfwmsac_vf_cg = new(); Vf16_vfwmsac_vf_cg.set_inst_name("obj_Vf16_vfwmsac_vf");
    Vf16_vfwmsac_vv_cg = new(); Vf16_vfwmsac_vv_cg.set_inst_name("obj_Vf16_vfwmsac_vv");
    Vf16_vfwmul_vf_cg = new(); Vf16_vfwmul_vf_cg.set_inst_name("obj_Vf16_vfwmul_vf");
    Vf16_vfwmul_vv_cg = new(); Vf16_vfwmul_vv_cg.set_inst_name("obj_Vf16_vfwmul_vv");
    Vf16_vfwnmacc_vf_cg = new(); Vf16_vfwnmacc_vf_cg.set_inst_name("obj_Vf16_vfwnmacc_vf");
    Vf16_vfwnmacc_vv_cg = new(); Vf16_vfwnmacc_vv_cg.set_inst_name("obj_Vf16_vfwnmacc_vv");
    Vf16_vfwnmsac_vf_cg = new(); Vf16_vfwnmsac_vf_cg.set_inst_name("obj_Vf16_vfwnmsac_vf");
    Vf16_vfwnmsac_vv_cg = new(); Vf16_vfwnmsac_vv_cg.set_inst_name("obj_Vf16_vfwnmsac_vv");
    Vf16_vfwredosum_vs_cg = new(); Vf16_vfwredosum_vs_cg.set_inst_name("obj_Vf16_vfwredosum_vs");
    Vf16_vfwredusum_vs_cg = new(); Vf16_vfwredusum_vs_cg.set_inst_name("obj_Vf16_vfwredusum_vs");
    Vf16_vfwsub_vf_cg = new(); Vf16_vfwsub_vf_cg.set_inst_name("obj_Vf16_vfwsub_vf");
    Vf16_vfwsub_vv_cg = new(); Vf16_vfwsub_vv_cg.set_inst_name("obj_Vf16_vfwsub_vv");
    Vf16_vfwsub_wf_cg = new(); Vf16_vfwsub_wf_cg.set_inst_name("obj_Vf16_vfwsub_wf");
    Vf16_vfwsub_wv_cg = new(); Vf16_vfwsub_wv_cg.set_inst_name("obj_Vf16_vfwsub_wv");
    Vf16_vmfeq_vf_cg = new(); Vf16_vmfeq_vf_cg.set_inst_name("obj_Vf16_vmfeq_vf");
    Vf16_vmfeq_vv_cg = new(); Vf16_vmfeq_vv_cg.set_inst_name("obj_Vf16_vmfeq_vv");
    Vf16_vmfge_vf_cg = new(); Vf16_vmfge_vf_cg.set_inst_name("obj_Vf16_vmfge_vf");
    Vf16_vmfgt_vf_cg = new(); Vf16_vmfgt_vf_cg.set_inst_name("obj_Vf16_vmfgt_vf");
    Vf16_vmfle_vf_cg = new(); Vf16_vmfle_vf_cg.set_inst_name("obj_Vf16_vmfle_vf");
    Vf16_vmfle_vv_cg = new(); Vf16_vmfle_vv_cg.set_inst_name("obj_Vf16_vmfle_vv");
    Vf16_vmflt_vf_cg = new(); Vf16_vmflt_vf_cg.set_inst_name("obj_Vf16_vmflt_vf");
    Vf16_vmflt_vv_cg = new(); Vf16_vmflt_vv_cg.set_inst_name("obj_Vf16_vmflt_vv");
    Vf16_vmfne_vf_cg = new(); Vf16_vmfne_vf_cg.set_inst_name("obj_Vf16_vmfne_vf");
    Vf16_vmfne_vv_cg = new(); Vf16_vmfne_vv_cg.set_inst_name("obj_Vf16_vmfne_vv");
