///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Vf32_vfadd_vf_cg = new(); Vf32_vfadd_vf_cg.set_inst_name("obj_Vf32_vfadd_vf");
    Vf32_vfadd_vv_cg = new(); Vf32_vfadd_vv_cg.set_inst_name("obj_Vf32_vfadd_vv");
    Vf32_vfclass_v_cg = new(); Vf32_vfclass_v_cg.set_inst_name("obj_Vf32_vfclass_v");
    Vf32_vfcvt_f_x_v_cg = new(); Vf32_vfcvt_f_x_v_cg.set_inst_name("obj_Vf32_vfcvt_f_x_v");
    Vf32_vfcvt_f_xu_v_cg = new(); Vf32_vfcvt_f_xu_v_cg.set_inst_name("obj_Vf32_vfcvt_f_xu_v");
    Vf32_vfcvt_rtz_x_f_v_cg = new(); Vf32_vfcvt_rtz_x_f_v_cg.set_inst_name("obj_Vf32_vfcvt_rtz_x_f_v");
    Vf32_vfcvt_rtz_xu_f_v_cg = new(); Vf32_vfcvt_rtz_xu_f_v_cg.set_inst_name("obj_Vf32_vfcvt_rtz_xu_f_v");
    Vf32_vfcvt_x_f_v_cg = new(); Vf32_vfcvt_x_f_v_cg.set_inst_name("obj_Vf32_vfcvt_x_f_v");
    Vf32_vfcvt_xu_f_v_cg = new(); Vf32_vfcvt_xu_f_v_cg.set_inst_name("obj_Vf32_vfcvt_xu_f_v");
    Vf32_vfdiv_vf_cg = new(); Vf32_vfdiv_vf_cg.set_inst_name("obj_Vf32_vfdiv_vf");
    Vf32_vfdiv_vv_cg = new(); Vf32_vfdiv_vv_cg.set_inst_name("obj_Vf32_vfdiv_vv");
    Vf32_vfmacc_vf_cg = new(); Vf32_vfmacc_vf_cg.set_inst_name("obj_Vf32_vfmacc_vf");
    Vf32_vfmacc_vv_cg = new(); Vf32_vfmacc_vv_cg.set_inst_name("obj_Vf32_vfmacc_vv");
    Vf32_vfmadd_vf_cg = new(); Vf32_vfmadd_vf_cg.set_inst_name("obj_Vf32_vfmadd_vf");
    Vf32_vfmadd_vv_cg = new(); Vf32_vfmadd_vv_cg.set_inst_name("obj_Vf32_vfmadd_vv");
    Vf32_vfmax_vf_cg = new(); Vf32_vfmax_vf_cg.set_inst_name("obj_Vf32_vfmax_vf");
    Vf32_vfmax_vv_cg = new(); Vf32_vfmax_vv_cg.set_inst_name("obj_Vf32_vfmax_vv");
    Vf32_vfmerge_vfm_cg = new(); Vf32_vfmerge_vfm_cg.set_inst_name("obj_Vf32_vfmerge_vfm");
    Vf32_vfmin_vf_cg = new(); Vf32_vfmin_vf_cg.set_inst_name("obj_Vf32_vfmin_vf");
    Vf32_vfmin_vv_cg = new(); Vf32_vfmin_vv_cg.set_inst_name("obj_Vf32_vfmin_vv");
    Vf32_vfmsac_vf_cg = new(); Vf32_vfmsac_vf_cg.set_inst_name("obj_Vf32_vfmsac_vf");
    Vf32_vfmsac_vv_cg = new(); Vf32_vfmsac_vv_cg.set_inst_name("obj_Vf32_vfmsac_vv");
    Vf32_vfmsub_vf_cg = new(); Vf32_vfmsub_vf_cg.set_inst_name("obj_Vf32_vfmsub_vf");
    Vf32_vfmsub_vv_cg = new(); Vf32_vfmsub_vv_cg.set_inst_name("obj_Vf32_vfmsub_vv");
    Vf32_vfmul_vf_cg = new(); Vf32_vfmul_vf_cg.set_inst_name("obj_Vf32_vfmul_vf");
    Vf32_vfmul_vv_cg = new(); Vf32_vfmul_vv_cg.set_inst_name("obj_Vf32_vfmul_vv");
    Vf32_vfmv_f_s_cg = new(); Vf32_vfmv_f_s_cg.set_inst_name("obj_Vf32_vfmv_f_s");
    Vf32_vfmv_s_f_cg = new(); Vf32_vfmv_s_f_cg.set_inst_name("obj_Vf32_vfmv_s_f");
    Vf32_vfmv_v_f_cg = new(); Vf32_vfmv_v_f_cg.set_inst_name("obj_Vf32_vfmv_v_f");
    Vf32_vfncvt_f_f_w_cg = new(); Vf32_vfncvt_f_f_w_cg.set_inst_name("obj_Vf32_vfncvt_f_f_w");
    Vf32_vfncvt_f_x_w_cg = new(); Vf32_vfncvt_f_x_w_cg.set_inst_name("obj_Vf32_vfncvt_f_x_w");
    Vf32_vfncvt_f_xu_w_cg = new(); Vf32_vfncvt_f_xu_w_cg.set_inst_name("obj_Vf32_vfncvt_f_xu_w");
    Vf32_vfncvt_rod_f_f_w_cg = new(); Vf32_vfncvt_rod_f_f_w_cg.set_inst_name("obj_Vf32_vfncvt_rod_f_f_w");
    Vf32_vfncvt_rtz_x_f_w_cg = new(); Vf32_vfncvt_rtz_x_f_w_cg.set_inst_name("obj_Vf32_vfncvt_rtz_x_f_w");
    Vf32_vfncvt_rtz_xu_f_w_cg = new(); Vf32_vfncvt_rtz_xu_f_w_cg.set_inst_name("obj_Vf32_vfncvt_rtz_xu_f_w");
    Vf32_vfncvt_x_f_w_cg = new(); Vf32_vfncvt_x_f_w_cg.set_inst_name("obj_Vf32_vfncvt_x_f_w");
    Vf32_vfncvt_xu_f_w_cg = new(); Vf32_vfncvt_xu_f_w_cg.set_inst_name("obj_Vf32_vfncvt_xu_f_w");
    Vf32_vfnmacc_vf_cg = new(); Vf32_vfnmacc_vf_cg.set_inst_name("obj_Vf32_vfnmacc_vf");
    Vf32_vfnmacc_vv_cg = new(); Vf32_vfnmacc_vv_cg.set_inst_name("obj_Vf32_vfnmacc_vv");
    Vf32_vfnmadd_vf_cg = new(); Vf32_vfnmadd_vf_cg.set_inst_name("obj_Vf32_vfnmadd_vf");
    Vf32_vfnmadd_vv_cg = new(); Vf32_vfnmadd_vv_cg.set_inst_name("obj_Vf32_vfnmadd_vv");
    Vf32_vfnmsac_vf_cg = new(); Vf32_vfnmsac_vf_cg.set_inst_name("obj_Vf32_vfnmsac_vf");
    Vf32_vfnmsac_vv_cg = new(); Vf32_vfnmsac_vv_cg.set_inst_name("obj_Vf32_vfnmsac_vv");
    Vf32_vfnmsub_vf_cg = new(); Vf32_vfnmsub_vf_cg.set_inst_name("obj_Vf32_vfnmsub_vf");
    Vf32_vfnmsub_vv_cg = new(); Vf32_vfnmsub_vv_cg.set_inst_name("obj_Vf32_vfnmsub_vv");
    Vf32_vfrdiv_vf_cg = new(); Vf32_vfrdiv_vf_cg.set_inst_name("obj_Vf32_vfrdiv_vf");
    Vf32_vfrec7_v_cg = new(); Vf32_vfrec7_v_cg.set_inst_name("obj_Vf32_vfrec7_v");
    Vf32_vfredmax_vs_cg = new(); Vf32_vfredmax_vs_cg.set_inst_name("obj_Vf32_vfredmax_vs");
    Vf32_vfredmin_vs_cg = new(); Vf32_vfredmin_vs_cg.set_inst_name("obj_Vf32_vfredmin_vs");
    Vf32_vfredosum_vs_cg = new(); Vf32_vfredosum_vs_cg.set_inst_name("obj_Vf32_vfredosum_vs");
    Vf32_vfredusum_vs_cg = new(); Vf32_vfredusum_vs_cg.set_inst_name("obj_Vf32_vfredusum_vs");
    Vf32_vfrsqrt7_v_cg = new(); Vf32_vfrsqrt7_v_cg.set_inst_name("obj_Vf32_vfrsqrt7_v");
    Vf32_vfrsub_vf_cg = new(); Vf32_vfrsub_vf_cg.set_inst_name("obj_Vf32_vfrsub_vf");
    Vf32_vfsgnj_vf_cg = new(); Vf32_vfsgnj_vf_cg.set_inst_name("obj_Vf32_vfsgnj_vf");
    Vf32_vfsgnj_vv_cg = new(); Vf32_vfsgnj_vv_cg.set_inst_name("obj_Vf32_vfsgnj_vv");
    Vf32_vfsgnjn_vf_cg = new(); Vf32_vfsgnjn_vf_cg.set_inst_name("obj_Vf32_vfsgnjn_vf");
    Vf32_vfsgnjn_vv_cg = new(); Vf32_vfsgnjn_vv_cg.set_inst_name("obj_Vf32_vfsgnjn_vv");
    Vf32_vfsgnjx_vf_cg = new(); Vf32_vfsgnjx_vf_cg.set_inst_name("obj_Vf32_vfsgnjx_vf");
    Vf32_vfsgnjx_vv_cg = new(); Vf32_vfsgnjx_vv_cg.set_inst_name("obj_Vf32_vfsgnjx_vv");
    Vf32_vfslide1down_vf_cg = new(); Vf32_vfslide1down_vf_cg.set_inst_name("obj_Vf32_vfslide1down_vf");
    Vf32_vfslide1up_vf_cg = new(); Vf32_vfslide1up_vf_cg.set_inst_name("obj_Vf32_vfslide1up_vf");
    Vf32_vfsqrt_v_cg = new(); Vf32_vfsqrt_v_cg.set_inst_name("obj_Vf32_vfsqrt_v");
    Vf32_vfsub_vf_cg = new(); Vf32_vfsub_vf_cg.set_inst_name("obj_Vf32_vfsub_vf");
    Vf32_vfsub_vv_cg = new(); Vf32_vfsub_vv_cg.set_inst_name("obj_Vf32_vfsub_vv");
    Vf32_vfwadd_vf_cg = new(); Vf32_vfwadd_vf_cg.set_inst_name("obj_Vf32_vfwadd_vf");
    Vf32_vfwadd_vv_cg = new(); Vf32_vfwadd_vv_cg.set_inst_name("obj_Vf32_vfwadd_vv");
    Vf32_vfwadd_wf_cg = new(); Vf32_vfwadd_wf_cg.set_inst_name("obj_Vf32_vfwadd_wf");
    Vf32_vfwadd_wv_cg = new(); Vf32_vfwadd_wv_cg.set_inst_name("obj_Vf32_vfwadd_wv");
    Vf32_vfwcvt_f_x_v_cg = new(); Vf32_vfwcvt_f_x_v_cg.set_inst_name("obj_Vf32_vfwcvt_f_x_v");
    Vf32_vfwcvt_f_xu_v_cg = new(); Vf32_vfwcvt_f_xu_v_cg.set_inst_name("obj_Vf32_vfwcvt_f_xu_v");
    Vf32_vfwcvt_rtz_x_f_v_cg = new(); Vf32_vfwcvt_rtz_x_f_v_cg.set_inst_name("obj_Vf32_vfwcvt_rtz_x_f_v");
    Vf32_vfwcvt_rtz_xu_f_v_cg = new(); Vf32_vfwcvt_rtz_xu_f_v_cg.set_inst_name("obj_Vf32_vfwcvt_rtz_xu_f_v");
    Vf32_vfwcvt_x_f_v_cg = new(); Vf32_vfwcvt_x_f_v_cg.set_inst_name("obj_Vf32_vfwcvt_x_f_v");
    Vf32_vfwcvt_xu_f_v_cg = new(); Vf32_vfwcvt_xu_f_v_cg.set_inst_name("obj_Vf32_vfwcvt_xu_f_v");
    Vf32_vfwmacc_vf_cg = new(); Vf32_vfwmacc_vf_cg.set_inst_name("obj_Vf32_vfwmacc_vf");
    Vf32_vfwmacc_vv_cg = new(); Vf32_vfwmacc_vv_cg.set_inst_name("obj_Vf32_vfwmacc_vv");
    Vf32_vfwmsac_vf_cg = new(); Vf32_vfwmsac_vf_cg.set_inst_name("obj_Vf32_vfwmsac_vf");
    Vf32_vfwmsac_vv_cg = new(); Vf32_vfwmsac_vv_cg.set_inst_name("obj_Vf32_vfwmsac_vv");
    Vf32_vfwmul_vf_cg = new(); Vf32_vfwmul_vf_cg.set_inst_name("obj_Vf32_vfwmul_vf");
    Vf32_vfwmul_vv_cg = new(); Vf32_vfwmul_vv_cg.set_inst_name("obj_Vf32_vfwmul_vv");
    Vf32_vfwnmacc_vf_cg = new(); Vf32_vfwnmacc_vf_cg.set_inst_name("obj_Vf32_vfwnmacc_vf");
    Vf32_vfwnmacc_vv_cg = new(); Vf32_vfwnmacc_vv_cg.set_inst_name("obj_Vf32_vfwnmacc_vv");
    Vf32_vfwnmsac_vf_cg = new(); Vf32_vfwnmsac_vf_cg.set_inst_name("obj_Vf32_vfwnmsac_vf");
    Vf32_vfwnmsac_vv_cg = new(); Vf32_vfwnmsac_vv_cg.set_inst_name("obj_Vf32_vfwnmsac_vv");
    Vf32_vfwredosum_vs_cg = new(); Vf32_vfwredosum_vs_cg.set_inst_name("obj_Vf32_vfwredosum_vs");
    Vf32_vfwredusum_vs_cg = new(); Vf32_vfwredusum_vs_cg.set_inst_name("obj_Vf32_vfwredusum_vs");
    Vf32_vfwsub_vf_cg = new(); Vf32_vfwsub_vf_cg.set_inst_name("obj_Vf32_vfwsub_vf");
    Vf32_vfwsub_vv_cg = new(); Vf32_vfwsub_vv_cg.set_inst_name("obj_Vf32_vfwsub_vv");
    Vf32_vfwsub_wf_cg = new(); Vf32_vfwsub_wf_cg.set_inst_name("obj_Vf32_vfwsub_wf");
    Vf32_vfwsub_wv_cg = new(); Vf32_vfwsub_wv_cg.set_inst_name("obj_Vf32_vfwsub_wv");
    Vf32_vmfeq_vf_cg = new(); Vf32_vmfeq_vf_cg.set_inst_name("obj_Vf32_vmfeq_vf");
    Vf32_vmfeq_vv_cg = new(); Vf32_vmfeq_vv_cg.set_inst_name("obj_Vf32_vmfeq_vv");
    Vf32_vmfge_vf_cg = new(); Vf32_vmfge_vf_cg.set_inst_name("obj_Vf32_vmfge_vf");
    Vf32_vmfgt_vf_cg = new(); Vf32_vmfgt_vf_cg.set_inst_name("obj_Vf32_vmfgt_vf");
    Vf32_vmfle_vf_cg = new(); Vf32_vmfle_vf_cg.set_inst_name("obj_Vf32_vmfle_vf");
    Vf32_vmfle_vv_cg = new(); Vf32_vmfle_vv_cg.set_inst_name("obj_Vf32_vmfle_vv");
    Vf32_vmflt_vf_cg = new(); Vf32_vmflt_vf_cg.set_inst_name("obj_Vf32_vmflt_vf");
    Vf32_vmflt_vv_cg = new(); Vf32_vmflt_vv_cg.set_inst_name("obj_Vf32_vmflt_vv");
    Vf32_vmfne_vf_cg = new(); Vf32_vmfne_vf_cg.set_inst_name("obj_Vf32_vmfne_vf");
    Vf32_vmfne_vv_cg = new(); Vf32_vmfne_vv_cg.set_inst_name("obj_Vf32_vmfne_vv");
