///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zaamo_amoadd_w_cg = new(); Zaamo_amoadd_w_cg.set_inst_name("obj_Zaamo_amoadd_w");
    Zaamo_amoand_w_cg = new(); Zaamo_amoand_w_cg.set_inst_name("obj_Zaamo_amoand_w");
    Zaamo_amomax_w_cg = new(); Zaamo_amomax_w_cg.set_inst_name("obj_Zaamo_amomax_w");
    Zaamo_amomaxu_w_cg = new(); Zaamo_amomaxu_w_cg.set_inst_name("obj_Zaamo_amomaxu_w");
    Zaamo_amomin_w_cg = new(); Zaamo_amomin_w_cg.set_inst_name("obj_Zaamo_amomin_w");
    Zaamo_amominu_w_cg = new(); Zaamo_amominu_w_cg.set_inst_name("obj_Zaamo_amominu_w");
    Zaamo_amoor_w_cg = new(); Zaamo_amoor_w_cg.set_inst_name("obj_Zaamo_amoor_w");
    Zaamo_amoswap_w_cg = new(); Zaamo_amoswap_w_cg.set_inst_name("obj_Zaamo_amoswap_w");
    Zaamo_amoxor_w_cg = new(); Zaamo_amoxor_w_cg.set_inst_name("obj_Zaamo_amoxor_w");
`ifdef UDB_MXLEN_64
    Zaamo_amoadd_d_cg = new(); Zaamo_amoadd_d_cg.set_inst_name("obj_Zaamo_amoadd_d");
    Zaamo_amoand_d_cg = new(); Zaamo_amoand_d_cg.set_inst_name("obj_Zaamo_amoand_d");
    Zaamo_amomax_d_cg = new(); Zaamo_amomax_d_cg.set_inst_name("obj_Zaamo_amomax_d");
    Zaamo_amomaxu_d_cg = new(); Zaamo_amomaxu_d_cg.set_inst_name("obj_Zaamo_amomaxu_d");
    Zaamo_amomin_d_cg = new(); Zaamo_amomin_d_cg.set_inst_name("obj_Zaamo_amomin_d");
    Zaamo_amominu_d_cg = new(); Zaamo_amominu_d_cg.set_inst_name("obj_Zaamo_amominu_d");
    Zaamo_amoor_d_cg = new(); Zaamo_amoor_d_cg.set_inst_name("obj_Zaamo_amoor_d");
    Zaamo_amoswap_d_cg = new(); Zaamo_amoswap_d_cg.set_inst_name("obj_Zaamo_amoswap_d");
    Zaamo_amoxor_d_cg = new(); Zaamo_amoxor_d_cg.set_inst_name("obj_Zaamo_amoxor_d");
`endif
