///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zacas_amocas_w_cg = new(); Zacas_amocas_w_cg.set_inst_name("obj_Zacas_amocas_w");
`ifdef UDB_MXLEN_32
    Zacas_amocas_d_cg = new(); Zacas_amocas_d_cg.set_inst_name("obj_Zacas_amocas_d");
`endif
`ifdef UDB_MXLEN_64
    Zacas_amocas_d_cg = new(); Zacas_amocas_d_cg.set_inst_name("obj_Zacas_amocas_d");
    Zacas_amocas_q_cg = new(); Zacas_amocas_q_cg.set_inst_name("obj_Zacas_amocas_q");
`endif
