///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zalrsc_lr_w_cg = new(); Zalrsc_lr_w_cg.set_inst_name("obj_Zalrsc_lr_w");
    Zalrsc_sc_w_cg = new(); Zalrsc_sc_w_cg.set_inst_name("obj_Zalrsc_sc_w");
`ifdef UDB_MXLEN_64
    Zalrsc_lr_d_cg = new(); Zalrsc_lr_d_cg.set_inst_name("obj_Zalrsc_lr_d");
    Zalrsc_sc_d_cg = new(); Zalrsc_sc_d_cg.set_inst_name("obj_Zalrsc_sc_d");
`endif
