///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zba_sh1add_cg = new(); Zba_sh1add_cg.set_inst_name("obj_Zba_sh1add");
    Zba_sh2add_cg = new(); Zba_sh2add_cg.set_inst_name("obj_Zba_sh2add");
    Zba_sh3add_cg = new(); Zba_sh3add_cg.set_inst_name("obj_Zba_sh3add");
`ifdef UDB_MXLEN_64
    Zba_add_uw_cg = new(); Zba_add_uw_cg.set_inst_name("obj_Zba_add_uw");
    Zba_sh1add_uw_cg = new(); Zba_sh1add_uw_cg.set_inst_name("obj_Zba_sh1add_uw");
    Zba_sh2add_uw_cg = new(); Zba_sh2add_uw_cg.set_inst_name("obj_Zba_sh2add_uw");
    Zba_sh3add_uw_cg = new(); Zba_sh3add_uw_cg.set_inst_name("obj_Zba_sh3add_uw");
    Zba_slli_uw_cg = new(); Zba_slli_uw_cg.set_inst_name("obj_Zba_slli_uw");
`endif
