///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zbb_andn_cg = new(); Zbb_andn_cg.set_inst_name("obj_Zbb_andn");
    Zbb_clz_cg = new(); Zbb_clz_cg.set_inst_name("obj_Zbb_clz");
    Zbb_cpop_cg = new(); Zbb_cpop_cg.set_inst_name("obj_Zbb_cpop");
    Zbb_ctz_cg = new(); Zbb_ctz_cg.set_inst_name("obj_Zbb_ctz");
    Zbb_max_cg = new(); Zbb_max_cg.set_inst_name("obj_Zbb_max");
    Zbb_maxu_cg = new(); Zbb_maxu_cg.set_inst_name("obj_Zbb_maxu");
    Zbb_min_cg = new(); Zbb_min_cg.set_inst_name("obj_Zbb_min");
    Zbb_minu_cg = new(); Zbb_minu_cg.set_inst_name("obj_Zbb_minu");
    Zbb_orc_b_cg = new(); Zbb_orc_b_cg.set_inst_name("obj_Zbb_orc_b");
    Zbb_orn_cg = new(); Zbb_orn_cg.set_inst_name("obj_Zbb_orn");
    Zbb_rev8_cg = new(); Zbb_rev8_cg.set_inst_name("obj_Zbb_rev8");
    Zbb_rol_cg = new(); Zbb_rol_cg.set_inst_name("obj_Zbb_rol");
    Zbb_ror_cg = new(); Zbb_ror_cg.set_inst_name("obj_Zbb_ror");
    Zbb_rori_cg = new(); Zbb_rori_cg.set_inst_name("obj_Zbb_rori");
    Zbb_sext_b_cg = new(); Zbb_sext_b_cg.set_inst_name("obj_Zbb_sext_b");
    Zbb_sext_h_cg = new(); Zbb_sext_h_cg.set_inst_name("obj_Zbb_sext_h");
    Zbb_xnor_cg = new(); Zbb_xnor_cg.set_inst_name("obj_Zbb_xnor");
    Zbb_zext_h_cg = new(); Zbb_zext_h_cg.set_inst_name("obj_Zbb_zext_h");
`ifdef UDB_MXLEN_64
    Zbb_clzw_cg = new(); Zbb_clzw_cg.set_inst_name("obj_Zbb_clzw");
    Zbb_cpopw_cg = new(); Zbb_cpopw_cg.set_inst_name("obj_Zbb_cpopw");
    Zbb_ctzw_cg = new(); Zbb_ctzw_cg.set_inst_name("obj_Zbb_ctzw");
    Zbb_rolw_cg = new(); Zbb_rolw_cg.set_inst_name("obj_Zbb_rolw");
    Zbb_roriw_cg = new(); Zbb_roriw_cg.set_inst_name("obj_Zbb_roriw");
    Zbb_rorw_cg = new(); Zbb_rorw_cg.set_inst_name("obj_Zbb_rorw");
`endif
