///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zca_c_add_cg = new(); Zca_c_add_cg.set_inst_name("obj_Zca_c_add");
    Zca_c_addi_cg = new(); Zca_c_addi_cg.set_inst_name("obj_Zca_c_addi");
    Zca_c_addi16sp_cg = new(); Zca_c_addi16sp_cg.set_inst_name("obj_Zca_c_addi16sp");
    Zca_c_addi4spn_cg = new(); Zca_c_addi4spn_cg.set_inst_name("obj_Zca_c_addi4spn");
    Zca_c_and_cg = new(); Zca_c_and_cg.set_inst_name("obj_Zca_c_and");
    Zca_c_andi_cg = new(); Zca_c_andi_cg.set_inst_name("obj_Zca_c_andi");
    Zca_c_beqz_cg = new(); Zca_c_beqz_cg.set_inst_name("obj_Zca_c_beqz");
    Zca_c_bnez_cg = new(); Zca_c_bnez_cg.set_inst_name("obj_Zca_c_bnez");
    Zca_c_j_cg = new(); Zca_c_j_cg.set_inst_name("obj_Zca_c_j");
    Zca_c_jalr_cg = new(); Zca_c_jalr_cg.set_inst_name("obj_Zca_c_jalr");
    Zca_c_jr_cg = new(); Zca_c_jr_cg.set_inst_name("obj_Zca_c_jr");
    Zca_c_li_cg = new(); Zca_c_li_cg.set_inst_name("obj_Zca_c_li");
    Zca_c_lui_cg = new(); Zca_c_lui_cg.set_inst_name("obj_Zca_c_lui");
    Zca_c_lw_cg = new(); Zca_c_lw_cg.set_inst_name("obj_Zca_c_lw");
    Zca_c_lwsp_cg = new(); Zca_c_lwsp_cg.set_inst_name("obj_Zca_c_lwsp");
    Zca_c_mv_cg = new(); Zca_c_mv_cg.set_inst_name("obj_Zca_c_mv");
    Zca_c_nop_cg = new(); Zca_c_nop_cg.set_inst_name("obj_Zca_c_nop");
    Zca_c_or_cg = new(); Zca_c_or_cg.set_inst_name("obj_Zca_c_or");
    Zca_c_slli_cg = new(); Zca_c_slli_cg.set_inst_name("obj_Zca_c_slli");
    Zca_c_srai_cg = new(); Zca_c_srai_cg.set_inst_name("obj_Zca_c_srai");
    Zca_c_srli_cg = new(); Zca_c_srli_cg.set_inst_name("obj_Zca_c_srli");
    Zca_c_sub_cg = new(); Zca_c_sub_cg.set_inst_name("obj_Zca_c_sub");
    Zca_c_sw_cg = new(); Zca_c_sw_cg.set_inst_name("obj_Zca_c_sw");
    Zca_c_swsp_cg = new(); Zca_c_swsp_cg.set_inst_name("obj_Zca_c_swsp");
    Zca_c_xor_cg = new(); Zca_c_xor_cg.set_inst_name("obj_Zca_c_xor");
`ifdef UDB_MXLEN_32
    Zca_c_jal_cg = new(); Zca_c_jal_cg.set_inst_name("obj_Zca_c_jal");
`endif
`ifdef UDB_MXLEN_64
    Zca_c_addiw_cg = new(); Zca_c_addiw_cg.set_inst_name("obj_Zca_c_addiw");
    Zca_c_addw_cg = new(); Zca_c_addw_cg.set_inst_name("obj_Zca_c_addw");
    Zca_c_ld_cg = new(); Zca_c_ld_cg.set_inst_name("obj_Zca_c_ld");
    Zca_c_ldsp_cg = new(); Zca_c_ldsp_cg.set_inst_name("obj_Zca_c_ldsp");
    Zca_c_sd_cg = new(); Zca_c_sd_cg.set_inst_name("obj_Zca_c_sd");
    Zca_c_sdsp_cg = new(); Zca_c_sdsp_cg.set_inst_name("obj_Zca_c_sdsp");
    Zca_c_subw_cg = new(); Zca_c_subw_cg.set_inst_name("obj_Zca_c_subw");
`endif
