///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
`ifdef UDB_MXLEN_64
    ZcbZba_c_zext_w_cg = new(); ZcbZba_c_zext_w_cg.set_inst_name("obj_ZcbZba_c_zext_w");
`endif
