///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
`ifdef UDB_MXLEN_32
    Zcf_c_flw_cg = new(); Zcf_c_flw_cg.set_inst_name("obj_Zcf_c_flw");
    Zcf_c_flwsp_cg = new(); Zcf_c_flwsp_cg.set_inst_name("obj_Zcf_c_flwsp");
    Zcf_c_fsw_cg = new(); Zcf_c_fsw_cg.set_inst_name("obj_Zcf_c_fsw");
    Zcf_c_fswsp_cg = new(); Zcf_c_fswsp_cg.set_inst_name("obj_Zcf_c_fswsp");
`endif
