///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZFAD
covergroup ZfaD_fcvtmod_w_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fcvtmod.w.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_vn : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
        wildcard bins NX   = (5'b????0 => 5'b????1);
        wildcard bins NX1  = (5'b????1 => 5'b????1);
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cp_rd : coverpoint ins.get_gpr_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

endgroup
// ---------------------
covergroup ZfaD_fleq_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fleq.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_edges_D : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cp_rd : coverpoint ins.get_gpr_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

    cr_fs1_fs2_edges_D : cross cp_fs1_edges_D,cp_fs2_edges_D  iff (ins.trap == 0 )  {
        // Cross coverage FS1, FS2 (double precision)
    }

endgroup
// ---------------------
covergroup ZfaD_fleq_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_S : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

    cp_fs2_badNB_D_S : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

endgroup
// ---------------------
covergroup ZfaD_fli_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fli.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_rs1_fli : coverpoint ins.current.insn[19:15]  iff (ins.trap == 0 )  {
        // FLI immediate encoding
    }

endgroup
// ---------------------
covergroup ZfaD_fli_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_S : coverpoint unsigned'(ins.current.fd_val[63:32])  iff (ins.trap == 0 )  {
        // NaNBoxing (float result in a double register)
        bins NaNBox = {32'hffffffff};
    }

endgroup
// ---------------------
covergroup ZfaD_fltq_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fltq.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_edges_D : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cp_rd : coverpoint ins.get_gpr_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

    cr_fs1_fs2_edges_D : cross cp_fs1_edges_D,cp_fs2_edges_D  iff (ins.trap == 0 )  {
        // Cross coverage FS1, FS2 (double precision)
    }

endgroup
// ---------------------
covergroup ZfaD_fltq_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_S : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

    cp_fs2_badNB_D_S : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

endgroup
// ---------------------
covergroup ZfaD_fmaxm_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cmp_fd_fs2 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs2 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint ins.ins_str == "fmaxm.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_edges_D : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cr_fs1_fs2_edges_D : cross cp_fs1_edges_D,cp_fs2_edges_D  iff (ins.trap == 0 )  {
        // Cross coverage FS1, FS2 (double precision)
    }

endgroup
// ---------------------
covergroup ZfaD_fmaxm_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_S : coverpoint unsigned'(ins.current.fd_val[63:32])  iff (ins.trap == 0 )  {
        // NaNBoxing (float result in a double register)
        bins NaNBox = {32'hffffffff};
    }

    cp_fs1_badNB_D_S : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

    cp_fs2_badNB_D_S : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

endgroup
// ---------------------
covergroup ZfaD_fminm_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cmp_fd_fs2 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs2 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint ins.ins_str == "fminm.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_edges_D : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cr_fs1_fs2_edges_D : cross cp_fs1_edges_D,cp_fs2_edges_D  iff (ins.trap == 0 )  {
        // Cross coverage FS1, FS2 (double precision)
    }

endgroup
// ---------------------
covergroup ZfaD_fminm_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_S : coverpoint unsigned'(ins.current.fd_val[63:32])  iff (ins.trap == 0 )  {
        // NaNBoxing (float result in a double register)
        bins NaNBox = {32'hffffffff};
    }

    cp_fs1_badNB_D_S : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

    cp_fs2_badNB_D_S : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

endgroup
// ---------------------
covergroup ZfaD_fround_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_frm_2 : coverpoint get_frm(ins.ops[2].val)  iff (ins.trap == 0 )  {
        // Floating-point rounding mode in instruction
    }

    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint ins.ins_str == "fround.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_csr_frm : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "frm", "frm")  iff (ins.trap == 0 & ins.current.insn[14:12] == 3'b111)  {
        // Value of FCSR.frm during dynamic rounding
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
        bins illegal  = default;
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

endgroup
// ---------------------
covergroup ZfaD_fround_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_S : coverpoint unsigned'(ins.current.fd_val[63:32])  iff (ins.trap == 0 )  {
        // NaNBoxing (float result in a double register)
        bins NaNBox = {32'hffffffff};
    }

    cp_fs1_badNB_D_S : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

endgroup
// ---------------------
covergroup ZfaD_froundnx_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_frm_2 : coverpoint get_frm(ins.ops[2].val)  iff (ins.trap == 0 )  {
        // Floating-point rounding mode in instruction
    }

    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint ins.ins_str == "froundnx.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_vn : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
        wildcard bins NX   = (5'b????0 => 5'b????1);
        wildcard bins NX1  = (5'b????1 => 5'b????1);
    }

    cp_csr_frm : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "frm", "frm")  iff (ins.trap == 0 & ins.current.insn[14:12] == 3'b111)  {
        // Value of FCSR.frm during dynamic rounding
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
        bins illegal  = default;
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

endgroup
// ---------------------
covergroup ZfaD_froundnx_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_S : coverpoint unsigned'(ins.current.fd_val[63:32])  iff (ins.trap == 0 )  {
        // NaNBoxing (float result in a double register)
        bins NaNBox = {32'hffffffff};
    }

    cp_fs1_badNB_D_S : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (single NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffefff_00000000};
        bins neg0             = {64'haaaaaaaa_80000000};
        bins pos1             = {64'h00000000_3f800000};
        bins neg1             = {64'hdeadbeef_bf800000};
        bins posminnorm       = {64'ha1b2c3d4_00800000};
        bins negminnorm       = {64'hffffffef_80800000};
        bins posmaxnorm       = {64'hfeffffef_7f7fffff};
        bins negmaxnorm       = {64'h7e7e7e7e_ff7fffff};
        bins posinfinity      = {64'h7fffffff_7f800000};
        bins neginfinity      = {64'hfffffffe_ff800000};
        bins posQNaN          = {[64'hfeedbee5_7fc00000:64'hffc0deff_7fffffff]};
        bins posSNaN          = {[64'hfeffffff_7f800001:64'hfffffeff_7fbfffff]};
    }

endgroup
// ---------------------
`ifdef UDB_MXLEN_32
covergroup ZfaD_fmvh_x_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fmvh.x.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cp_rd : coverpoint ins.get_gpr_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

endgroup
// ---------------------
covergroup ZfaD_fmvp_d_x_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fmvp.d.x"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_rs1 : coverpoint ins.get_gpr_reg(ins.current.rs1)  iff (ins.trap == 0 )  {
        // RS1 register assignment
    }

    cp_rs1_edges : coverpoint unsigned'(ins.current.rs1_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero  = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

    cp_rs2 : coverpoint ins.get_gpr_reg(ins.current.rs2)  iff (ins.trap == 0 )  {
        // RS2 register assignment
    }

    cp_rs2_edges : coverpoint unsigned'(ins.current.rs2_val)  iff (ins.trap == 0 )  {
        `ifdef UDB_MXLEN_32
            bins zero     = {0};
            bins one      = {32'b00000000000000000000000000000001};
            bins two      = {32'b00000000000000000000000000000010};
            bins min      = {32'b10000000000000000000000000000000};
            bins minp1    = {32'b10000000000000000000000000000001};
            bins max      = {32'b01111111111111111111111111111111};
            bins maxm1    = {32'b01111111111111111111111111111110};
            bins ones     = {32'b11111111111111111111111111111111};
            bins onesm1   = {32'b11111111111111111111111111111110};
            bins walkodd  = {32'b10101010101010101010101010101010};
            bins walkeven = {32'b01010101010101010101010101010101};
            wildcard bins random = {32'b01???????????????????????????010};
        `else
            bins zero     = {0};
            bins one      = {64'b0000000000000000000000000000000000000000000000000000000000000001};
            bins two      = {64'b0000000000000000000000000000000000000000000000000000000000000010};
            bins min      = {64'b1000000000000000000000000000000000000000000000000000000000000000};
            bins minp1    = {64'b1000000000000000000000000000000000000000000000000000000000000001};
            bins Wmax     = {64'b0000000000000000000000000000000011111111111111111111111111111111};
            bins Wmaxm1   = {64'b0000000000000000000000000000000011111111111111111111111111111110};
            bins Wmaxp1   = {64'b0000000000000000000000000000000100000000000000000000000000000000};
            bins Wmaxp2   = {64'b0000000000000000000000000000000100000000000000000000000000000001};
            bins max      = {64'b0111111111111111111111111111111111111111111111111111111111111111};
            bins maxm1    = {64'b0111111111111111111111111111111111111111111111111111111111111110};
            bins ones     = {64'b1111111111111111111111111111111111111111111111111111111111111111};
            bins onesm1   = {64'b1111111111111111111111111111111111111111111111111111111111111110};
            bins walkodd  = {64'b1010101010101010101010101010101010101010101010101010101010101010};
            bins walkeven = {64'b0101010101010101010101010101010101010101010101010101010101010101};
            wildcard bins random = {64'b01???????????????????????????????????????????????????????????010};
        `endif
    }

endgroup
// ---------------------
`endif
`ifdef UDB_MXLEN_64
`endif
function void zfad_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "fcvtmod.w.d"     : begin
            ZfaD_fcvtmod_w_d_cg.sample(ins);
        end
        "fleq.d"     : begin
            ZfaD_fleq_d_cg.sample(ins);
        end
        "fleq.s"     : begin
            ZfaD_fleq_s_cg.sample(ins);
        end
        "fli.d"     : begin
            ZfaD_fli_d_cg.sample(ins);
        end
        "fli.s"     : begin
            ZfaD_fli_s_cg.sample(ins);
        end
        "fltq.d"     : begin
            ZfaD_fltq_d_cg.sample(ins);
        end
        "fltq.s"     : begin
            ZfaD_fltq_s_cg.sample(ins);
        end
        "fmaxm.d"     : begin
            ZfaD_fmaxm_d_cg.sample(ins);
        end
        "fmaxm.s"     : begin
            ZfaD_fmaxm_s_cg.sample(ins);
        end
        "fminm.d"     : begin
            ZfaD_fminm_d_cg.sample(ins);
        end
        "fminm.s"     : begin
            ZfaD_fminm_s_cg.sample(ins);
        end
        "fround.d"     : begin
            ZfaD_fround_d_cg.sample(ins);
        end
        "fround.s"     : begin
            ZfaD_fround_s_cg.sample(ins);
        end
        "froundnx.d"     : begin
            ZfaD_froundnx_d_cg.sample(ins);
        end
        "froundnx.s"     : begin
            ZfaD_froundnx_s_cg.sample(ins);
        end
`ifdef UDB_MXLEN_32
        "fmvh.x.d"     : begin
            ZfaD_fmvh_x_d_cg.sample(ins);
        end
        "fmvp.d.x"     : begin
            ZfaD_fmvp_d_x_cg.sample(ins);
        end
`endif
`ifdef UDB_MXLEN_64
`endif
    endcase
endfunction
