///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZFAZFH
covergroup ZfaZfh_fleq_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fleq.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_badNB_S_H : coverpoint unsigned'(ins.current.fs2_val[31:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs2_edges_H : coverpoint unsigned'(ins.current.fs2_val[15:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_rd : coverpoint ins.get_gpr_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

    cr_fs1_fs2_edges_H : cross cp_fs1_edges_H,cp_fs2_edges_H  iff (ins.trap == 0 )  {
        // Cross coverage FS1, FS2 (half precision)
    }

endgroup
// ---------------------
covergroup ZfaZfh_fli_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fli.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_rs1_fli : coverpoint ins.current.insn[19:15]  iff (ins.trap == 0 )  {
        // FLI immediate encoding
    }

endgroup
// ---------------------
covergroup ZfaZfh_fltq_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "fltq.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_badNB_S_H : coverpoint unsigned'(ins.current.fs2_val[31:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs2_edges_H : coverpoint unsigned'(ins.current.fs2_val[15:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_rd : coverpoint ins.get_gpr_reg(ins.current.rd)  iff (ins.trap == 0 )  {
        // RD register assignment
    }

    cr_fs1_fs2_edges_H : cross cp_fs1_edges_H,cp_fs2_edges_H  iff (ins.trap == 0 )  {
        // Cross coverage FS1, FS2 (half precision)
    }

endgroup
// ---------------------
covergroup ZfaZfh_fmaxm_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cmp_fd_fs2 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs2 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fmaxm.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_badNB_S_H : coverpoint unsigned'(ins.current.fs2_val[31:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs2_edges_H : coverpoint unsigned'(ins.current.fs2_val[15:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cr_fs1_fs2_edges_H : cross cp_fs1_edges_H,cp_fs2_edges_H  iff (ins.trap == 0 )  {
        // Cross coverage FS1, FS2 (half precision)
    }

endgroup
// ---------------------
covergroup ZfaZfh_fminm_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cmp_fd_fs2 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs2 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fminm.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cp_fs2 : coverpoint ins.get_fpr_reg(ins.current.fs2)  iff (ins.trap == 0 )  {
        // FS2 register assignment
    }

    cp_fs2_badNB_S_H : coverpoint unsigned'(ins.current.fs2_val[31:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs2_edges_H : coverpoint unsigned'(ins.current.fs2_val[15:0])  iff (ins.trap == 0 )  {
        // FS2 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

    cr_fs1_fs2_edges_H : cross cp_fs1_edges_H,cp_fs2_edges_H  iff (ins.trap == 0 )  {
        // Cross coverage FS1, FS2 (half precision)
    }

endgroup
// ---------------------
covergroup ZfaZfh_fround_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_frm_2 : coverpoint get_frm(ins.ops[2].val)  iff (ins.trap == 0 )  {
        // Floating-point rounding mode in instruction
    }

    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fround.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_csr_frm : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "frm", "frm")  iff (ins.trap == 0 & ins.current.insn[14:12] == 3'b111)  {
        // Value of FCSR.frm during dynamic rounding
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
        bins illegal  = default;
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

endgroup
// ---------------------
covergroup ZfaZfh_froundnx_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_frm_2 : coverpoint get_frm(ins.ops[2].val)  iff (ins.trap == 0 )  {
        // Floating-point rounding mode in instruction
    }

    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_NaNBox_S_H : coverpoint unsigned'(ins.current.fd_val[31:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a float register)
        bins NaNBox = {16'hffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "froundnx.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_vn : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
        wildcard bins NX   = (5'b????0 => 5'b????1);
        wildcard bins NX1  = (5'b????1 => 5'b????1);
    }

    cp_csr_frm : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "frm", "frm")  iff (ins.trap == 0 & ins.current.insn[14:12] == 3'b111)  {
        // Value of FCSR.frm during dynamic rounding
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
        bins illegal  = default;
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_S_H : coverpoint unsigned'(ins.current.fs1_val[31:0])  iff (ins.trap == 0 )  {
        // "FS1 Bad NaNBox edges (half NaNBoxed to 32 bits)";
        bins pos0             = {32'h0000_0000};
        bins neg0             = {32'hfffe_8000};
        bins pos1             = {32'h7fff_3C00};
        bins neg1             = {32'hbeef_BC00};
        bins posminnorm       = {32'hfeff_0400};
        bins negminnorm       = {32'h0fff_8400};
        bins posmaxnorm       = {32'hefff_7BFF};
        bins negmaxnorm       = {32'hc0de_FBFF};
        bins posinfinity      = {32'h4f1a_7C00};
        bins neginfinity      = {32'h0fff_FC00};
        bins posQNaN          = {[32'hffef_7E00:32'hfeef_7FFF]};
        bins posSNaN          = {[32'ha1b2_7C01:32'h4fd7_7DFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

endgroup
// ---------------------
function void zfazfh_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "fleq.h"     : begin
            ZfaZfh_fleq_h_cg.sample(ins);
        end
        "fli.h"     : begin
            ZfaZfh_fli_h_cg.sample(ins);
        end
        "fltq.h"     : begin
            ZfaZfh_fltq_h_cg.sample(ins);
        end
        "fmaxm.h"     : begin
            ZfaZfh_fmaxm_h_cg.sample(ins);
        end
        "fminm.h"     : begin
            ZfaZfh_fminm_h_cg.sample(ins);
        end
        "fround.h"     : begin
            ZfaZfh_fround_h_cg.sample(ins);
        end
        "froundnx.h"     : begin
            ZfaZfh_froundnx_h_cg.sample(ins);
        end
    endcase
endfunction
