///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZFHD
covergroup ZfhD_fadd_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fclass_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_d_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_asm_count : coverpoint ins.ins_str == "fcvt.d.h"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs1_edges_H : coverpoint unsigned'(ins.current.fs1_val[15:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Half Precision)
        bins pos0             = {16'h0000};
        bins neg0             = {16'h8000};
        bins pos1             = {16'h3C00};
        bins neg1             = {16'hBC00};
        bins pos1p5           = {16'h3E00};
        bins neg1p5           = {16'hBE00};
        bins pos2             = {16'h4000};
        bins neg2             = {16'hC000};
        bins posminnorm       = {16'h0400};
        bins negminnorm       = {16'h8400};
        bins posmaxnorm       = {16'h7BFF};
        bins negmaxnorm       = {16'hFBFF};
        bins posmax_subnorm   = {16'h03FF};
        bins negmax_subnorm   = {16'h83FF};
        bins posmid_subnorm   = {16'h0200};
        bins negmid_subnorm   = {16'h8200};
        bins posmin_subnorm   = {16'h0001};
        bins negmin_subnorm   = {16'h8001};
        bins posinfinity      = {16'h7C00};
        bins neginfinity      = {16'hFC00};
        bins posQNaN          = {[16'h7E00:16'h7FFF]};
        bins posSNaN          = {[16'h7C01:16'h7DFF]};
        bins negQNaN          = {[16'hFE00:16'hFFFF]};
        bins negSNaN          = {[16'hFC01:16'hFDFF]};
        bins posrandom        = {16'h58B4};
        bins negrandom        = {16'hC93A};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_h_d_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_frm_2 : coverpoint get_frm(ins.ops[2].val)  iff (ins.trap == 0 )  {
        // Floating-point rounding mode in instruction
    }

    cmp_fd_fs1 : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.current.fd == ins.current.fs1 & ins.trap == 0 )  {
        // FD and FS1 register (assignment) WAR Hazard
    }

    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_asm_count : coverpoint ins.ins_str == "fcvt.h.d"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_voun : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
        wildcard bins OF   = (5'b??0?? => 5'b??1??);
        wildcard bins OF1  = (5'b??1?? => 5'b??1??);
        wildcard bins UF   = (5'b???0? => 5'b???1?);
        wildcard bins UF1  = (5'b???1? => 5'b???1?);
        wildcard bins NX   = (5'b????0 => 5'b????1);
        wildcard bins NX1  = (5'b????1 => 5'b????1);
    }

    cp_csr_frm : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "frm", "frm")  iff (ins.trap == 0 & ins.current.insn[14:12] == 3'b111)  {
        // Value of FCSR.frm during dynamic rounding
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
        bins illegal  = default;
    }

    cp_fd : coverpoint ins.get_fpr_reg(ins.current.fd)  iff (ins.trap == 0 )  {
        // FD register assignment
    }

    cp_fs1 : coverpoint ins.get_fpr_reg(ins.current.fs1)  iff (ins.trap == 0 )  {
        // FS1 register assignment
    }

    cp_fs1_edges_D : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        // FS1 edges (Double Precision)
        bins pos0             = {64'h0000000000000000};
        bins neg0             = {64'h8000000000000000};
        bins pos1             = {64'h3FF0000000000000};
        bins neg1             = {64'hBFF0000000000000};
        bins pos1p5           = {64'h3FF8000000000000};
        bins neg1p5           = {64'hBFF8000000000000};
        bins pos2             = {64'h4000000000000000};
        bins neg2             = {64'hc000000000000000};
        bins posminnorm       = {64'h0010000000000000};
        bins negminnorm       = {64'h8010000000000000};
        bins posmaxnorm       = {64'h7FEFFFFFFFFFFFFF};
        bins negmaxnorm       = {64'hFFEFFFFFFFFFFFFF};
        bins posmax_subnorm   = {64'h000FFFFFFFFFFFFF};
        bins negmax_subnorm   = {64'h800FFFFFFFFFFFFF};
        bins posmid_subnorm   = {64'h0008000000000000};
        bins negmid_subnorm   = {64'h8008000000000000};
        bins posmin_subnorm   = {64'h0000000000000001};
        bins negmin_subnorm   = {64'h8000000000000001};
        bins posinfinity      = {64'h7FF0000000000000};
        bins neginfinity      = {64'hFFF0000000000000};
        bins posQNaN          = {[64'h7FF8000000000000:64'h7FFFFFFFFFFFFFFF]};
        bins posSNaN          = {[64'h7FF0000000000001:64'h7FF7FFFFFFFFFFFF]};
        bins negQNaN          = {[64'hFFF8000000000000:64'hFFFFFFFFFFFFFFFF]};
        bins negSNaN          = {[64'hFFF0000000000001:64'hFFF7FFFFFFFFFFFF]};
        bins posrandom        = {64'h5A392534A57711AD};
        bins negrandom        = {64'hA6E895993737426C};
    }

    cr_fs1_edges_frm_D : cross cp_fs1_edges_D,cp_frm_2  iff (ins.trap == 0 )  {
        // Cross coverage FS1 (double precision), FRM
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_h_s_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_h_w_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_h_wu_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_s_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_S : coverpoint unsigned'(ins.current.fd_val[63:32])  iff (ins.trap == 0 )  {
        // NaNBoxing (float result in a double register)
        bins NaNBox = {32'hffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_w_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_wu_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fdiv_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_feq_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fle_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_flh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhD_flt_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fmadd_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs3_badNB_D_H : coverpoint unsigned'(ins.current.fs3_val[63:0])  iff (ins.trap == 0 )  {
        // "FS3 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fmax_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fmin_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fmsub_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs3_badNB_D_H : coverpoint unsigned'(ins.current.fs3_val[63:0])  iff (ins.trap == 0 )  {
        // "FS3 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fmul_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fmv_h_x_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhD_fmv_x_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fnmadd_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs3_badNB_D_H : coverpoint unsigned'(ins.current.fs3_val[63:0])  iff (ins.trap == 0 )  {
        // "FS3 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fnmsub_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs3_badNB_D_H : coverpoint unsigned'(ins.current.fs3_val[63:0])  iff (ins.trap == 0 )  {
        // "FS3 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fsgnj_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fsgnjn_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fsgnjx_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fsh_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fsqrt_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fsub_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

    cp_fs2_badNB_D_H : coverpoint unsigned'(ins.current.fs2_val[63:0])  iff (ins.trap == 0 )  {
        // "FS2 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
`ifdef UDB_MXLEN_64
covergroup ZfhD_fcvt_h_l_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_h_lu_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_NaNBox_D_H : coverpoint unsigned'(ins.current.fd_val[63:16])  iff (ins.trap == 0 )  {
        // NaNBoxing (half result in a double register)
        bins NaNBox = {48'hffffffffffff};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_l_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
covergroup ZfhD_fcvt_lu_h_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_fs1_badNB_D_H : coverpoint unsigned'(ins.current.fs1_val[63:0])  iff (ins.trap == 0 )  {
        //// "FS1 Bad NaNBox edges (half NaNBoxed to 64 bits)";
        bins pos0             = {64'hffffffff0000_0000};
        bins neg0             = {64'hfffffffffffe_8000};
        bins pos1             = {64'h7fffffffffff_3C00};
        bins neg1             = {64'hfeedbee5beef_BC00};
        bins posminnorm       = {64'hffffffefffff_0400};
        bins negminnorm       = {64'h00000000ffff_8400};
        bins posmaxnorm       = {64'hefffffffffff_7BFF};
        bins negmaxnorm       = {64'hc0dec0dec0de_FBFF};
        bins posinfinity      = {64'ha83ef1cc4f1a_7C00};
        bins neginfinity      = {64'hffffffff0fff_FC00};
        bins posQNaN          = {[64'hfffeffffffff_7E00:64'hffffffefffff_7FFF]};
        bins posSNaN          = {[64'ha1b2c3d4e5f6_7C01:64'hfffffffcffff_7DFF]};
    }

endgroup
// ---------------------
`endif
function void zfhd_sample(int hart, int issue, ins_t ins);

    case (traceDataQ[hart][issue][0].inst_name)
        "fadd.h"     : begin
            ZfhD_fadd_h_cg.sample(ins);
        end
        "fclass.h"     : begin
            ZfhD_fclass_h_cg.sample(ins);
        end
        "fcvt.d.h"     : begin
            ZfhD_fcvt_d_h_cg.sample(ins);
        end
        "fcvt.h.d"     : begin
            ZfhD_fcvt_h_d_cg.sample(ins);
        end
        "fcvt.h.s"     : begin
            ZfhD_fcvt_h_s_cg.sample(ins);
        end
        "fcvt.h.w"     : begin
            ZfhD_fcvt_h_w_cg.sample(ins);
        end
        "fcvt.h.wu"     : begin
            ZfhD_fcvt_h_wu_cg.sample(ins);
        end
        "fcvt.s.h"     : begin
            ZfhD_fcvt_s_h_cg.sample(ins);
        end
        "fcvt.w.h"     : begin
            ZfhD_fcvt_w_h_cg.sample(ins);
        end
        "fcvt.wu.h"     : begin
            ZfhD_fcvt_wu_h_cg.sample(ins);
        end
        "fdiv.h"     : begin
            ZfhD_fdiv_h_cg.sample(ins);
        end
        "feq.h"     : begin
            ZfhD_feq_h_cg.sample(ins);
        end
        "fle.h"     : begin
            ZfhD_fle_h_cg.sample(ins);
        end
        "flh"     : begin
            ZfhD_flh_cg.sample(ins);
        end
        "flt.h"     : begin
            ZfhD_flt_h_cg.sample(ins);
        end
        "fmadd.h"     : begin
            ZfhD_fmadd_h_cg.sample(ins);
        end
        "fmax.h"     : begin
            ZfhD_fmax_h_cg.sample(ins);
        end
        "fmin.h"     : begin
            ZfhD_fmin_h_cg.sample(ins);
        end
        "fmsub.h"     : begin
            ZfhD_fmsub_h_cg.sample(ins);
        end
        "fmul.h"     : begin
            ZfhD_fmul_h_cg.sample(ins);
        end
        "fmv.h.x"     : begin
            ZfhD_fmv_h_x_cg.sample(ins);
        end
        "fmv.x.h"     : begin
            ZfhD_fmv_x_h_cg.sample(ins);
        end
        "fnmadd.h"     : begin
            ZfhD_fnmadd_h_cg.sample(ins);
        end
        "fnmsub.h"     : begin
            ZfhD_fnmsub_h_cg.sample(ins);
        end
        "fsgnj.h"     : begin
            ZfhD_fsgnj_h_cg.sample(ins);
        end
        "fsgnjn.h"     : begin
            ZfhD_fsgnjn_h_cg.sample(ins);
        end
        "fsgnjx.h"     : begin
            ZfhD_fsgnjx_h_cg.sample(ins);
        end
        "fsh"     : begin
            ZfhD_fsh_cg.sample(ins);
        end
        "fsqrt.h"     : begin
            ZfhD_fsqrt_h_cg.sample(ins);
        end
        "fsub.h"     : begin
            ZfhD_fsub_h_cg.sample(ins);
        end
`ifdef UDB_MXLEN_64
        "fcvt.h.l"     : begin
            ZfhD_fcvt_h_l_cg.sample(ins);
        end
        "fcvt.h.lu"     : begin
            ZfhD_fcvt_h_lu_cg.sample(ins);
        end
        "fcvt.l.h"     : begin
            ZfhD_fcvt_l_h_cg.sample(ins);
        end
        "fcvt.lu.h"     : begin
            ZfhD_fcvt_lu_h_cg.sample(ins);
        end
`endif
    endcase
endfunction
