///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zmmul_mul_cg = new(); Zmmul_mul_cg.set_inst_name("obj_Zmmul_mul");
    Zmmul_mulh_cg = new(); Zmmul_mulh_cg.set_inst_name("obj_Zmmul_mulh");
    Zmmul_mulhsu_cg = new(); Zmmul_mulhsu_cg.set_inst_name("obj_Zmmul_mulhsu");
    Zmmul_mulhu_cg = new(); Zmmul_mulhu_cg.set_inst_name("obj_Zmmul_mulhu");
`ifdef UDB_MXLEN_64
    Zmmul_mulw_cg = new(); Zmmul_mulw_cg.set_inst_name("obj_Zmmul_mulw");
`endif
