///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zvfhmin_vfncvt_f_f_w_cg = new(); Zvfhmin_vfncvt_f_f_w_cg.set_inst_name("obj_Zvfhmin_vfncvt_f_f_w");
    Zvfhmin_vfwcvt_f_f_v_cg = new(); Zvfhmin_vfwcvt_f_f_v_cg.set_inst_name("obj_Zvfhmin_vfwcvt_f_f_v");
