///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZVFHMIN
`define COVER_ZVFHMINCUSTOM16
`ifdef UDB_ELEN_16
    `define SEW_16_EQ_ELEN
`endif
`ifdef UDB_ELEN_32
    `define SEW_16_EQ_ELEN_DIV_2
`endif
covergroup Zvfhmin_vfncvt_f_f_w_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "vfncvt.f.f.w"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_voun : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
        wildcard bins OF   = (5'b??0?? => 5'b??1??);
        wildcard bins OF1  = (5'b??1?? => 5'b??1??);
        wildcard bins UF   = (5'b???0? => 5'b???1?);
        wildcard bins UF1  = (5'b???1? => 5'b???1?);
        wildcard bins NX   = (5'b????0 => 5'b????1);
        wildcard bins NX1  = (5'b????1 => 5'b????1);
    }

    cp_csr_frm_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "fcsr", "frm")  iff (ins.trap == 0 )  {
        // Value of FCSR.frm for vector FP instructions, which do not specify dynamic rounding mode in opcode
        bins rne  = {3'b000};
        bins rtz  = {3'b001};
        bins rdn  = {3'b010};
        bins rup  = {3'b011};
        bins rmm  = {3'b100};
        bins illegal  = default;
    }

    cp_masking_edges : coverpoint mask_edges_check(ins.hart, ins.issue, ins.prev.v_wdata[0])  iff (ins.trap == 0 & ins.current.vm == 0)  {
        // Edges values of v0 (vector mask register)
        bins zero           = {mask_zero            };
        bins ones           = {mask_ones            };
        bins vlmaxm1ones    = {mask_vlmaxm1ones     };
        bins vlmaxd2p1ones  = {mask_vlmaxd2p1ones   };
        bins random         = {mask_random          };
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vd
    //////////////////////////////////////////////////////////////////////////////////

    cp_vd : coverpoint ins.get_vr_reg(ins.current.vd)  iff (ins.trap == 0 )  {
        // VD register assignment
    }

    //// end cp_vd////////////////////////////////////////////////

    cp_vl_0 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vl", "vl") {
    bins zero = {0};
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2_edges_f_emul2_sew16
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2_edges_f_emul2_sew16 : coverpoint get_vr_element_zero_widen(ins.hart, ins.issue, ins.current.vs2_val)[31:0]  iff (ins.trap == 0 )  {
        // Standard precision coverpoints
        bins pos0                   = {32'h00000000};
        bins neg0                   = {32'h80000000};
        bins pos1                   = {32'h3F800000};
        bins neg1                   = {32'hBF800000};
        bins posminnorm             = {32'h00800000};
        bins negmaxnorm             = {32'hFF7FFFFF};
        bins posinfinity            = {32'h7F800000};
        bins neginfinity            = {32'hFF800000};
        bins pos0p5                 = {32'h3F000000};
        bins pos1p5                 = {32'h3FC00000};
        bins neg2                   = {32'hC0000000};
        bins pi                     = {32'h40490FDB};
        bins twoToEmax              = {32'h7F000000};   // 2^127
        bins onePulp                = {32'h3F800001};   // 1 + ULP
        bins largestsubnorm         = {32'h007FFFFF};
        bins negSubnormLeadingOne   = {32'h80400000};   // subnormal with MSB of fraction = 1
        bins min_subnorm            = {32'h00000001};
        bins canonicalQNaN          = {32'h7FC00000};   // quiet NaN, canonical payload
        bins negNoncanonicalQNaN    = {[32'hFFC00001:32'hFFFFFFFF]}; // other quiet NaNs
        bins sNaN_payload1          = {32'h7F800001};   // signaling NaN with payload 1
    }

    //// end cp_vs2_edges_f_emul2_sew16        /////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2_emul2
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2_emul2 : coverpoint ins.get_vr_reg(ins.current.vs2) iff (ins.trap == 0) {
        // VS2 register assignment (widening operand, excluding odd registers)
        ignore_bins v1 = {v1};
        ignore_bins v3 = {v3};
        ignore_bins v5 = {v5};
        ignore_bins v7 = {v7};
        ignore_bins v9 = {v9};
        ignore_bins v11 = {v11};
        ignore_bins v13 = {v13};
        ignore_bins v15 = {v15};
        ignore_bins v17 = {v17};
        ignore_bins v19 = {v19};
        ignore_bins v21 = {v21};
        ignore_bins v23 = {v23};
        ignore_bins v25 = {v25};
        ignore_bins v27 = {v27};
        ignore_bins v29 = {v29};
        ignore_bins v31 = {v31};
    }

    //// end cp_vs2_emul2////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vl_lmul_sew16_lmul4max
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_lmul_all_lmul4max_sew16_lmul_le_4 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul")  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 1) {
        // Value of VTYPE.vlmul (vector register grouping), SEW = 16, excluding LMUL = 8
        `ifdef LMULf4_SUPPORTED
            bins fourth = {6};
        `endif
        `ifdef LMULf2_SUPPORTED
            bins half   = {7};
        `endif
        bins one    = {0};
        bins two    = {1};
        bins four   = {2};
    }

    cp_csr_vl_edges : coverpoint vl_check(ins.hart, ins.issue)  iff (ins.trap == 0 )  {
        // Edges values of VL (vector length)
        bins one        = {vl_one       };
        bins vlmax      = {vl_vlmax     };
        bins legal      = {vl_legal     };
    }

    cr_vl_lmul_lmul4max_sew16 : cross cp_csr_vtype_lmul_all_lmul4max_sew16_lmul_le_4, cp_csr_vl_edges  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 1)  {
        // Cross coverage all legal LMULs (excluding LMUL = 8) for SEW = 16 and vl edges (1, random, vlmax)
    }

    //////////////////////////////////////////////////////////////////////////////////

    //// end cr_vl_lmul_lmul4max_sew16////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vtype_agnostic_lmul4max
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_vta : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vta")  iff (ins.trap == 0)  {
        // Value of VTYPE.vta (vector tail agnostic)
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    cp_csr_vtype_vma : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vma")  iff (ins.trap == 0)  {
        // Value of VTYPE.vma (vector mask agnostic)
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    mask_enabled_agnostic: coverpoint ins.current.insn[25] {
        bins enabled = {1'b0};
    }

    cr_vtype_agnostic_lmul4max : cross cp_csr_vtype_vta,cp_csr_vtype_vma,mask_enabled_agnostic iff (ins.trap == 0 )  {
        // Cross coverage of vector tail and mask agnostic behaviors
    }

    //// end cr_vtype_agnostic_lmul4max////////////////////////////////////////////////

endgroup
// ---------------------
covergroup Zvfhmin_vfwcvt_f_f_v_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "vfwcvt.f.f.v"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_csr_fflags_v : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_AFTER, "fcsr", "fflags") iff (ins.trap == 0 )  {
        // Value of FCSR.fflags
        wildcard bins NV   = (5'b0???? => 5'b1????);
        wildcard bins NV1  = (5'b1???? => 5'b1????);
    }

    cp_masking_edges : coverpoint mask_edges_check(ins.hart, ins.issue, ins.prev.v_wdata[0])  iff (ins.trap == 0 & ins.current.vm == 0)  {
        // Edges values of v0 (vector mask register)
        bins zero           = {mask_zero            };
        bins ones           = {mask_ones            };
        bins vlmaxm1ones    = {mask_vlmaxm1ones     };
        bins vlmaxd2p1ones  = {mask_vlmaxd2p1ones   };
        bins random         = {mask_random          };
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vd_emul2
    //////////////////////////////////////////////////////////////////////////////////

    cp_vd_emul2 : coverpoint ins.get_vr_reg(ins.current.vd) iff (ins.trap == 0) {
        // VD register assignment (widening instruction, excluding odd registers)
        ignore_bins v1 = {v1};
        ignore_bins v3 = {v3};
        ignore_bins v5 = {v5};
        ignore_bins v7 = {v7};
        ignore_bins v9 = {v9};
        ignore_bins v11 = {v11};
        ignore_bins v13 = {v13};
        ignore_bins v15 = {v15};
        ignore_bins v17 = {v17};
        ignore_bins v19 = {v19};
        ignore_bins v21 = {v21};
        ignore_bins v23 = {v23};
        ignore_bins v25 = {v25};
        ignore_bins v27 = {v27};
        ignore_bins v29 = {v29};
        ignore_bins v31 = {v31};
    }

    //// end cp_vd_emul2////////////////////////////////////////////////

    cp_vl_0 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vl", "vl") {
    bins zero = {0};
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2 : coverpoint ins.get_vr_reg(ins.current.vs2)  iff (ins.trap == 0 )  {
        // VS2 register assignment
    }

    //// end cp_vs2////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2_edges_f_sew16
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2_edges_f_sew16 : coverpoint get_vr_element_zero(ins.hart, ins.issue, ins.current.vs2_val)[15:0]  iff (ins.trap == 0 )  {
        // (Half Precision)
        bins pos0                   = {16'h0000};
        bins neg0                   = {16'h8000};
        bins pos1                   = {16'h3C00};
        bins neg1                   = {16'hBC00};
        bins posminnorm             = {16'h0400};
        bins negmaxnorm             = {16'hFBFF};
        bins posinfinity            = {16'h7C00};
        bins neginfinity            = {16'hFC00};
        bins pos0p5                 = {16'h3800};
        bins pos1p5                 = {16'h3E00};
        bins neg2                   = {16'hC000};
        bins pi                     = {16'h4248};
        bins twoToEmax              = {16'h7800};
        bins onePulp                = {16'h3c01};
        bins largestsubnorm         = {16'h03FF};
        bins negSubnormLeadingOne   = {16'h8200};
        bins min_subnorm            = {16'h0001};
        bins canonicalQNaN          = {16'h7E00};                // Quiet NaN with only MSB of fraction set
        bins negNoncanonicalQNaN    = {[16'hFE01:16'hFFFF]};     // Quiet NaNs excluding canonical
        bins sNaN_payload1          = {16'h7D01};                // Signaling NaN with payload 1
    }

    //// end cp_vs2_edges_f_sew16////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vl_lmul_sew16_lmul4max
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_lmul_all_lmul4max_sew16_lmul_le_4 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul")  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 1) {
        // Value of VTYPE.vlmul (vector register grouping), SEW = 16, excluding LMUL = 8
        `ifdef LMULf4_SUPPORTED
            bins fourth = {6};
        `endif
        `ifdef LMULf2_SUPPORTED
            bins half   = {7};
        `endif
        bins one    = {0};
        bins two    = {1};
        bins four   = {2};
    }

    cp_csr_vl_edges : coverpoint vl_check(ins.hart, ins.issue)  iff (ins.trap == 0 )  {
        // Edges values of VL (vector length)
        bins one        = {vl_one       };
        bins vlmax      = {vl_vlmax     };
        bins legal      = {vl_legal     };
    }

    cr_vl_lmul_lmul4max_sew16 : cross cp_csr_vtype_lmul_all_lmul4max_sew16_lmul_le_4, cp_csr_vl_edges  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 1)  {
        // Cross coverage all legal LMULs (excluding LMUL = 8) for SEW = 16 and vl edges (1, random, vlmax)
    }

    //////////////////////////////////////////////////////////////////////////////////

    //// end cr_vl_lmul_lmul4max_sew16////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vtype_agnostic_lmul4max
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_vta : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vta")  iff (ins.trap == 0)  {
        // Value of VTYPE.vta (vector tail agnostic)
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    cp_csr_vtype_vma : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vma")  iff (ins.trap == 0)  {
        // Value of VTYPE.vma (vector mask agnostic)
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    mask_enabled_agnostic: coverpoint ins.current.insn[25] {
        bins enabled = {1'b0};
    }

    cr_vtype_agnostic_lmul4max : cross cp_csr_vtype_vta,cp_csr_vtype_vma,mask_enabled_agnostic iff (ins.trap == 0 )  {
        // Cross coverage of vector tail and mask agnostic behaviors
    }

    //// end cr_vtype_agnostic_lmul4max////////////////////////////////////////////////

endgroup
// ---------------------
function void zvfhmin_sample(int hart, int issue, ins_t ins);
    // Want to sample only if the SEW matches the target SEW of the file, some tests require
    // testing when vill is set, if vill=1 all other vtype bits are set to 0 so there is no
    // associated sew with these tests
    if (get_csr_val(hart, issue, `SAMPLE_BEFORE, "vtype", "vsew") == 1 ||
        get_csr_val(hart, issue, `SAMPLE_BEFORE, "vtype", "vill") == 1) begin
        case (traceDataQ[hart][issue][0].inst_name)
            "vfncvt.f.f.w"     : begin
                Zvfhmin_vfncvt_f_f_w_cg.sample(ins);
            end
            "vfwcvt.f.f.v"     : begin
                Zvfhmin_vfwcvt_f_f_v_cg.sample(ins);
            end
        endcase
    end
endfunction
