///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zvkg_vghsh_vv_cg = new(); Zvkg_vghsh_vv_cg.set_inst_name("obj_Zvkg_vghsh_vv");
    Zvkg_vgmul_vv_cg = new(); Zvkg_vgmul_vv_cg.set_inst_name("obj_Zvkg_vgmul_vv");
