///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups Initialization File
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////
    Zvknha_vsha2ch_vv_cg = new(); Zvknha_vsha2ch_vv_cg.set_inst_name("obj_Zvknha_vsha2ch_vv");
    Zvknha_vsha2cl_vv_cg = new(); Zvknha_vsha2cl_vv_cg.set_inst_name("obj_Zvknha_vsha2cl_vv");
    Zvknha_vsha2ms_vv_cg = new(); Zvknha_vsha2ms_vv_cg.set_inst_name("obj_Zvknha_vsha2ms_vv");
