///////////////////////////////////////////
//
// RISC-V Architectural Functional Coverage Covergroups
//
// This file is autogenerated by covergroupgen.
// Do not modify directly.
//
// Copyright (C) 2024 Harvey Mudd College, 10x Engineers, UET Lahore, Habib University
//
// SPDX-License-Identifier: Apache-2.0
//
////////////////////////////////////////////////////////////////////////////////////////////////

`define COVER_ZVKSH
`define COVER_ZVKSHCUSTOM32
`ifdef UDB_ELEN_32
    `define SEW_32_EQ_ELEN
`endif
`ifdef UDB_ELEN_64
    `define SEW_32_EQ_ELEN_DIV_2
`endif
covergroup Zvksh_vsm3c_vi_cg with function sample(ins_t ins);
    option.per_instance = 0;
    cp_asm_count : coverpoint ins.ins_str == "vsm3c.vi"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    cp_imm_5bit_u : coverpoint unsigned'(ins.current.imm)  iff (ins.trap == 0 )  {
        bins uimm[] = {[0:31]}; // 5 bit unsigned immediates for vector instructions
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vd_edges_egs4
    //////////////////////////////////////////////////////////////////////////////////

    cp_vd_edges_egs8 : coverpoint vs_edges_check_sew32_egs8(ins.hart, ins.issue, ins.get_vr_val_lmul8(ins.current.vd))
        iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul") == 3)  {
        // Edge values of vd (EGS=4), assuming vl = 1
        bins zero       = {vs_zero      };   //  = {(`EGS*SEW){1'b0}},
        bins ones       = {vs_ones      };   //  = {(`EGS*SEW){1'b1}},
        bins walkodd    = {vs_walkodd   };   //  = {(`EGS*SEW/2){2'b10}},
        bins walkeven   = {vs_walkeven  };   //  = {(`EGS*SEW/2){2'b01}},
        bins random     = {vs_random    };   //  = {(EGS*SEW){random}}
    }

    //// end cp_vd_edges_egs4////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vd_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_vd_egs8 : coverpoint ins.get_vr_reg(ins.current.vd)  iff (ins.trap == 0 )  {
        // VD register assignment (EGS=8, SEW=32: with VLEN=128 LMUL=2 is required, so odd registers are illegal, with VLEN=32, LMUL=4
        // is required so all registers must be a multiple of 4, and with VLEN=32 LMUL=8 is required, so all registers must be a multiple of 8)
        `ifndef ZVL256B_SUPPORTED
            ignore_bins v1  = {v1};
            ignore_bins v3  = {v3};
            ignore_bins v5  = {v5};
            ignore_bins v7  = {v7};
            ignore_bins v9  = {v9};
            ignore_bins v11 = {v11};
            ignore_bins v13 = {v13};
            ignore_bins v15 = {v15};
            ignore_bins v17 = {v17};
            ignore_bins v19 = {v19};
            ignore_bins v21 = {v21};
            ignore_bins v23 = {v23};
            ignore_bins v25 = {v25};
            ignore_bins v27 = {v27};
            ignore_bins v29 = {v29};
            ignore_bins v31 = {v31};
        `endif

        `ifndef ZVL128B_SUPPORTED
            ignore_bins v2  = {v2};
            ignore_bins v6  = {v6};
            ignore_bins v10  = {v10};
            ignore_bins v14  = {v14};
            ignore_bins v18  = {v18};
            ignore_bins v22 = {v22};
            ignore_bins v26 = {v26};
            ignore_bins v30 = {v30};
        `endif

        `ifndef ZVL64B_SUPPORTED
            ignore_bins v4  = {v4};
            ignore_bins v12  = {v12};
            ignore_bins v20  = {v20};
            ignore_bins v28  = {v28};
        `endif
    }

    //// end cp_vd_egs8 ////////////////////////////////////////////////

    cp_vl_0_egs8 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vl", "vl") {
        bins zero = {0};
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2_edges_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2_edges_egs8 : coverpoint vs_edges_check_sew32_egs8(ins.hart, ins.issue, ins.get_vr_val_lmul8(ins.current.vs2))
        iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul") == 3)  {
        // Edge values of vs2 (EGS=8), assuming vl = 8
        bins zero       = {vs_zero      };   //  = {(`EGS*SEW){1'b0}},
        bins ones       = {vs_ones      };   //  = {(`EGS*SEW){1'b1}},
        bins walkodd    = {vs_walkodd   };   //  = {(`EGS*SEW/2){2'b10}},
        bins walkeven   = {vs_walkeven  };   //  = {(`EGS*SEW/2){2'b01}},
        bins random     = {vs_random    };   //  = {(EGS*SEW){random}}
    }

    //// end cp_vs2_edges_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2_egs8 : coverpoint ins.get_vr_reg(ins.current.vs2)  iff (ins.trap == 0 )  {
        // VS2 register assignment (EGS=8, SEW=32: with VLEN=128 LMUL=2 is required, so odd registers are illegal, with VLEN=32, LMUL=4
        // is required so all registers must be a multiple of 4, and with VLEN=32 LMUL=8 is required, so all registers must be a multiple of 8)
        `ifndef ZVL256B_SUPPORTED
            ignore_bins v1  = {v1};
            ignore_bins v3  = {v3};
            ignore_bins v5  = {v5};
            ignore_bins v7  = {v7};
            ignore_bins v9  = {v9};
            ignore_bins v11 = {v11};
            ignore_bins v13 = {v13};
            ignore_bins v15 = {v15};
            ignore_bins v17 = {v17};
            ignore_bins v19 = {v19};
            ignore_bins v21 = {v21};
            ignore_bins v23 = {v23};
            ignore_bins v25 = {v25};
            ignore_bins v27 = {v27};
            ignore_bins v29 = {v29};
            ignore_bins v31 = {v31};
        `endif

        `ifndef ZVL128B_SUPPORTED
            ignore_bins v2  = {v2};
            ignore_bins v6  = {v6};
            ignore_bins v10  = {v10};
            ignore_bins v14  = {v14};
            ignore_bins v18  = {v18};
            ignore_bins v22 = {v22};
            ignore_bins v26 = {v26};
            ignore_bins v30 = {v30};
        `endif

        `ifndef ZVL64B_SUPPORTED
            ignore_bins v4  = {v4};
            ignore_bins v12  = {v12};
            ignore_bins v20  = {v20};
            ignore_bins v28  = {v28};
        `endif
    }

    //// end cp_vs2_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vl_lmul_egs8_sew32
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_lmul_egs8_sew32 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul")  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 2) {
        // LMUL values for EGS=8, SEW=32 instructions (EGS*SEW = 256 bits per group)
        // LMUL=8: always valid since VLEN=32 (minimum) satisfies LMUL*VLEN >= 256 bits
        bins eight  = {3};
        `ifdef ZVL64B_SUPPORTED
            bins four   = {2};   // LMUL=4: needs VLEN>=64 for valid configuration
        `endif
        `ifdef ZVL128B_SUPPORTED
            bins two    = {1};   // LMUL=2: needs VLEN>=128
        `endif
        `ifdef ZVL256B_SUPPORTED
            bins one    = {0};   // LMUL=1: needs VLEN>=256 for >=2 element groups
        `endif
        `ifdef ZVL512B_SUPPORTED
            `ifdef LMULf2_SUPPORTED
                bins half    = {7};   // LMUL=1/2: needs VLEN>=512
            `endif
        `endif
    }

    cp_csr_vl_edges_egs8 : coverpoint vl_check(ins.hart, ins.issue, 8)  iff (ins.trap == 0 )  {
        // Edge values of VL (vector length)
        bins vl_eight    = {vl_one      };
        bins vlmax       = {vl_vlmax    };
        bins vl_legal    = {vl_legal    };
    }

    cr_vl_lmul_egs8_sew32 : cross cp_csr_vtype_lmul_egs8_sew32, cp_csr_vl_edges_egs8  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 2)  {
        // Cross coverage of LMUL and VL edges for EGS=8 instructions at SEW=32
        `ifdef ZVL512B_SUPPORTED
            `ifndef ZVL1024B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmulf2 = binsof(cp_csr_vtype_lmul_egs8_sew32.half) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL2048B_SUPPORTED
                ignore_bins impossible_vl_legal_lmulf2 = binsof(cp_csr_vtype_lmul_egs8_sew32.half) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
        `ifdef ZVL256B_SUPPORTED
            `ifndef ZVL512B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmul1 = binsof(cp_csr_vtype_lmul_egs8_sew32.one) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL1024B_SUPPORTED
                ignore_bins impossible_vl_legal_lmul1 = binsof(cp_csr_vtype_lmul_egs8_sew32.one) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
        `ifdef ZVL128B_SUPPORTED
            `ifndef ZVL256B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmul2 = binsof(cp_csr_vtype_lmul_egs8_sew32.two) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL512B_SUPPORTED
                ignore_bins impossible_vl_legal_lmul2 = binsof(cp_csr_vtype_lmul_egs8_sew32.two) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
        `ifdef ZVL64B_SUPPORTED
            `ifndef ZVL128B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmul4 = binsof(cp_csr_vtype_lmul_egs8_sew32.four) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL256B_SUPPORTED
                ignore_bins impossible_vl_legal_lmul4 = binsof(cp_csr_vtype_lmul_egs8_sew32.four) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
        `ifdef ZVL32B_SUPPORTED
            `ifndef ZVL64B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmul8 = binsof(cp_csr_vtype_lmul_egs8_sew32.eight) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL128B_SUPPORTED
                ignore_bins impossible_vl_legal_lmul8 = binsof(cp_csr_vtype_lmul_egs8_sew32.eight) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
    }

    //////////////////////////////////////////////////////////////////////////////////

    //// end cr_vl_lmul_egs8_sew32 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vs2_vd_edges_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cr_vs2_vd_edges_egs8 : cross cp_vs2_edges_egs8, cp_vd_edges_egs8  iff (ins.trap == 0 )  {
        // Cross coverage of VS2 edges and VD edges (EGS=8)
    }

    //// end cr_vs2_vd_edges_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vtype_agnostic_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_vta_egs8 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vta")  iff (ins.trap == 0)  {
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    cp_csr_vtype_vma_egs8 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vma")  iff (ins.trap == 0)  {
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    mask_enabled_agnostic_egs8: coverpoint ins.current.insn[25] {
        bins enabled = {1'b1};
    }

    cr_vtype_agnostic_egs8 : cross cp_csr_vtype_vta_egs8, cp_csr_vtype_vma_egs8, mask_enabled_agnostic_egs8  iff (ins.trap == 0)  {
        // Cross coverage of vector tail and mask agnostic behaviors (EGS=8)
    }

    //// end cr_vtype_agnostic_egs8 ////////////////////////////////////////////////

endgroup
// ---------------------
covergroup Zvksh_vsm3me_vv_cg with function sample(ins_t ins);
    option.per_instance = 0;
    //////////////////////////////////////////////////////////////////////////////////
    // cmp_vd_vs1_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cmp_vd_vs1_egs8 : coverpoint ins.get_vr_reg(ins.current.vd)  iff (ins.current.vd == ins.current.vs1 & ins.trap == 0 )  {
        // Compare assignments of all 32 registers; with VLEN=128 only even registers are valid (LMUL=2), with VLEN=64 only multiples of 4 (LMUL=4), and with VLEN=32 only multiples of 8 (LMUL=8)
        `ifndef ZVL256B_SUPPORTED
            ignore_bins v1  = {v1};
            ignore_bins v3  = {v3};
            ignore_bins v5  = {v5};
            ignore_bins v7  = {v7};
            ignore_bins v9  = {v9};
            ignore_bins v11 = {v11};
            ignore_bins v13 = {v13};
            ignore_bins v15 = {v15};
            ignore_bins v17 = {v17};
            ignore_bins v19 = {v19};
            ignore_bins v21 = {v21};
            ignore_bins v23 = {v23};
            ignore_bins v25 = {v25};
            ignore_bins v27 = {v27};
            ignore_bins v29 = {v29};
            ignore_bins v31 = {v31};
        `endif

        `ifndef ZVL128B_SUPPORTED
            ignore_bins v2  = {v2};
            ignore_bins v6  = {v6};
            ignore_bins v10  = {v10};
            ignore_bins v14  = {v14};
            ignore_bins v18  = {v18};
            ignore_bins v22 = {v22};
            ignore_bins v26 = {v26};
            ignore_bins v30 = {v30};
        `endif

        `ifndef ZVL64B_SUPPORTED
            ignore_bins v4  = {v4};
            ignore_bins v12  = {v12};
            ignore_bins v20  = {v20};
            ignore_bins v28  = {v28};
        `endif
    }

    //// end cmp_vd_vs1_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cmp_vs1_vs2_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cmp_vs1_vs2_egs8 : coverpoint ins.get_vr_reg(ins.current.vs1)  iff (ins.current.vs1 == ins.current.vs2 & ins.trap == 0 )  {
        // Compare assignments of all 32 registers; with VLEN=128 only even registers are valid (LMUL=2), with VLEN=64 only multiples of 4 (LMUL=4), and with VLEN=32 only multiples of 8 (LMUL=8)
        `ifndef ZVL256B_SUPPORTED
            ignore_bins v1  = {v1};
            ignore_bins v3  = {v3};
            ignore_bins v5  = {v5};
            ignore_bins v7  = {v7};
            ignore_bins v9  = {v9};
            ignore_bins v11 = {v11};
            ignore_bins v13 = {v13};
            ignore_bins v15 = {v15};
            ignore_bins v17 = {v17};
            ignore_bins v19 = {v19};
            ignore_bins v21 = {v21};
            ignore_bins v23 = {v23};
            ignore_bins v25 = {v25};
            ignore_bins v27 = {v27};
            ignore_bins v29 = {v29};
            ignore_bins v31 = {v31};
        `endif

        `ifndef ZVL128B_SUPPORTED
            ignore_bins v2  = {v2};
            ignore_bins v6  = {v6};
            ignore_bins v10  = {v10};
            ignore_bins v14  = {v14};
            ignore_bins v18  = {v18};
            ignore_bins v22 = {v22};
            ignore_bins v26 = {v26};
            ignore_bins v30 = {v30};
        `endif

        `ifndef ZVL64B_SUPPORTED
            ignore_bins v4  = {v4};
            ignore_bins v12  = {v12};
            ignore_bins v20  = {v20};
            ignore_bins v28  = {v28};
        `endif
    }

    //// end cmp_vs1_vs2_egs8 ////////////////////////////////////////////////

    cp_asm_count : coverpoint ins.ins_str == "vsm3me.vv"  iff (ins.trap == 0 )  {
        // Number of times instruction is executed
        bins count[]  = {1};
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vd_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_vd_egs8 : coverpoint ins.get_vr_reg(ins.current.vd)  iff (ins.trap == 0 )  {
        // VD register assignment (EGS=8, SEW=32: with VLEN=128 LMUL=2 is required, so odd registers are illegal, with VLEN=32, LMUL=4
        // is required so all registers must be a multiple of 4, and with VLEN=32 LMUL=8 is required, so all registers must be a multiple of 8)
        `ifndef ZVL256B_SUPPORTED
            ignore_bins v1  = {v1};
            ignore_bins v3  = {v3};
            ignore_bins v5  = {v5};
            ignore_bins v7  = {v7};
            ignore_bins v9  = {v9};
            ignore_bins v11 = {v11};
            ignore_bins v13 = {v13};
            ignore_bins v15 = {v15};
            ignore_bins v17 = {v17};
            ignore_bins v19 = {v19};
            ignore_bins v21 = {v21};
            ignore_bins v23 = {v23};
            ignore_bins v25 = {v25};
            ignore_bins v27 = {v27};
            ignore_bins v29 = {v29};
            ignore_bins v31 = {v31};
        `endif

        `ifndef ZVL128B_SUPPORTED
            ignore_bins v2  = {v2};
            ignore_bins v6  = {v6};
            ignore_bins v10  = {v10};
            ignore_bins v14  = {v14};
            ignore_bins v18  = {v18};
            ignore_bins v22 = {v22};
            ignore_bins v26 = {v26};
            ignore_bins v30 = {v30};
        `endif

        `ifndef ZVL64B_SUPPORTED
            ignore_bins v4  = {v4};
            ignore_bins v12  = {v12};
            ignore_bins v20  = {v20};
            ignore_bins v28  = {v28};
        `endif
    }

    //// end cp_vd_egs8 ////////////////////////////////////////////////

    cp_vl_0_egs8 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vl", "vl") {
        bins zero = {0};
    }

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs1_edges_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs1_edges_egs8 : coverpoint vs_edges_check_sew32_egs8(ins.hart, ins.issue, ins.get_vr_val_lmul8(ins.current.vs1))
        iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul") == 3)  {
        // Edge values of vs1 (EGS=8), assuming vl = 8
        bins zero       = {vs_zero      };   //  = {(`EGS*SEW){1'b0}},
        bins ones       = {vs_ones      };   //  = {(`EGS*SEW){1'b1}},
        bins walkodd    = {vs_walkodd   };   //  = {(`EGS*SEW/2){2'b10}},
        bins walkeven   = {vs_walkeven  };   //  = {(`EGS*SEW/2){2'b01}},
        bins random     = {vs_random    };   //  = {(EGS*SEW){random}}
    }

    //// end cp_vs1_edges_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs1_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs1_egs8 : coverpoint ins.get_vr_reg(ins.current.vs1)  iff (ins.trap == 0 )  {
        // VS1 register assignment (EGS=8, SEW=32: with VLEN=128 LMUL=2 is required, so odd registers are illegal, with VLEN=32, LMUL=4
        // is required so all registers must be a multiple of 4, and with VLEN=32 LMUL=8 is required, so all registers must be a multiple of 8)
        `ifndef ZVL256B_SUPPORTED
            ignore_bins v1  = {v1};
            ignore_bins v3  = {v3};
            ignore_bins v5  = {v5};
            ignore_bins v7  = {v7};
            ignore_bins v9  = {v9};
            ignore_bins v11 = {v11};
            ignore_bins v13 = {v13};
            ignore_bins v15 = {v15};
            ignore_bins v17 = {v17};
            ignore_bins v19 = {v19};
            ignore_bins v21 = {v21};
            ignore_bins v23 = {v23};
            ignore_bins v25 = {v25};
            ignore_bins v27 = {v27};
            ignore_bins v29 = {v29};
            ignore_bins v31 = {v31};
        `endif

        `ifndef ZVL128B_SUPPORTED
            ignore_bins v2  = {v2};
            ignore_bins v6  = {v6};
            ignore_bins v10  = {v10};
            ignore_bins v14  = {v14};
            ignore_bins v18  = {v18};
            ignore_bins v22 = {v22};
            ignore_bins v26 = {v26};
            ignore_bins v30 = {v30};
        `endif

        `ifndef ZVL64B_SUPPORTED
            ignore_bins v4  = {v4};
            ignore_bins v12  = {v12};
            ignore_bins v20  = {v20};
            ignore_bins v28  = {v28};
        `endif
    }

    //// end cp_vs1_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2_edges_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2_edges_egs8 : coverpoint vs_edges_check_sew32_egs8(ins.hart, ins.issue, ins.get_vr_val_lmul8(ins.current.vs2))
        iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul") == 3)  {
        // Edge values of vs2 (EGS=8), assuming vl = 8
        bins zero       = {vs_zero      };   //  = {(`EGS*SEW){1'b0}},
        bins ones       = {vs_ones      };   //  = {(`EGS*SEW){1'b1}},
        bins walkodd    = {vs_walkodd   };   //  = {(`EGS*SEW/2){2'b10}},
        bins walkeven   = {vs_walkeven  };   //  = {(`EGS*SEW/2){2'b01}},
        bins random     = {vs_random    };   //  = {(EGS*SEW){random}}
    }

    //// end cp_vs2_edges_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cp_vs2_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_vs2_egs8 : coverpoint ins.get_vr_reg(ins.current.vs2)  iff (ins.trap == 0 )  {
        // VS2 register assignment (EGS=8, SEW=32: with VLEN=128 LMUL=2 is required, so odd registers are illegal, with VLEN=32, LMUL=4
        // is required so all registers must be a multiple of 4, and with VLEN=32 LMUL=8 is required, so all registers must be a multiple of 8)
        `ifndef ZVL256B_SUPPORTED
            ignore_bins v1  = {v1};
            ignore_bins v3  = {v3};
            ignore_bins v5  = {v5};
            ignore_bins v7  = {v7};
            ignore_bins v9  = {v9};
            ignore_bins v11 = {v11};
            ignore_bins v13 = {v13};
            ignore_bins v15 = {v15};
            ignore_bins v17 = {v17};
            ignore_bins v19 = {v19};
            ignore_bins v21 = {v21};
            ignore_bins v23 = {v23};
            ignore_bins v25 = {v25};
            ignore_bins v27 = {v27};
            ignore_bins v29 = {v29};
            ignore_bins v31 = {v31};
        `endif

        `ifndef ZVL128B_SUPPORTED
            ignore_bins v2  = {v2};
            ignore_bins v6  = {v6};
            ignore_bins v10  = {v10};
            ignore_bins v14  = {v14};
            ignore_bins v18  = {v18};
            ignore_bins v22 = {v22};
            ignore_bins v26 = {v26};
            ignore_bins v30 = {v30};
        `endif

        `ifndef ZVL64B_SUPPORTED
            ignore_bins v4  = {v4};
            ignore_bins v12  = {v12};
            ignore_bins v20  = {v20};
            ignore_bins v28  = {v28};
        `endif
    }

    //// end cp_vs2_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vl_lmul_egs8_sew32
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_lmul_egs8_sew32 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vlmul")  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 2) {
        // LMUL values for EGS=8, SEW=32 instructions (EGS*SEW = 256 bits per group)
        // LMUL=8: always valid since VLEN=32 (minimum) satisfies LMUL*VLEN >= 256 bits
        bins eight  = {3};
        `ifdef ZVL64B_SUPPORTED
            bins four   = {2};   // LMUL=4: needs VLEN>=64 for valid configuration
        `endif
        `ifdef ZVL128B_SUPPORTED
            bins two    = {1};   // LMUL=2: needs VLEN>=128
        `endif
        `ifdef ZVL256B_SUPPORTED
            bins one    = {0};   // LMUL=1: needs VLEN>=256 for >=2 element groups
        `endif
        `ifdef ZVL512B_SUPPORTED
            `ifdef LMULf2_SUPPORTED
                bins half    = {7};   // LMUL=1/2: needs VLEN>=512
            `endif
        `endif
    }

    cp_csr_vl_edges_egs8 : coverpoint vl_check(ins.hart, ins.issue, 8)  iff (ins.trap == 0 )  {
        // Edge values of VL (vector length)
        bins vl_eight    = {vl_one      };
        bins vlmax       = {vl_vlmax    };
        bins vl_legal    = {vl_legal    };
    }

    cr_vl_lmul_egs8_sew32 : cross cp_csr_vtype_lmul_egs8_sew32, cp_csr_vl_edges_egs8  iff (ins.trap == 0 & get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vsew") == 2)  {
        // Cross coverage of LMUL and VL edges for EGS=8 instructions at SEW=32
        `ifdef ZVL512B_SUPPORTED
            `ifndef ZVL1024B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmulf2 = binsof(cp_csr_vtype_lmul_egs8_sew32.half) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL2048B_SUPPORTED
                ignore_bins impossible_vl_legal_lmulf2 = binsof(cp_csr_vtype_lmul_egs8_sew32.half) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
        `ifdef ZVL256B_SUPPORTED
            `ifndef ZVL512B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmul1 = binsof(cp_csr_vtype_lmul_egs8_sew32.one) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL1024B_SUPPORTED
                ignore_bins impossible_vl_legal_lmul1 = binsof(cp_csr_vtype_lmul_egs8_sew32.one) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
        `ifdef ZVL128B_SUPPORTED
            `ifndef ZVL256B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmul2 = binsof(cp_csr_vtype_lmul_egs8_sew32.two) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL512B_SUPPORTED
                ignore_bins impossible_vl_legal_lmul2 = binsof(cp_csr_vtype_lmul_egs8_sew32.two) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
        `ifdef ZVL64B_SUPPORTED
            `ifndef ZVL128B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmul4 = binsof(cp_csr_vtype_lmul_egs8_sew32.four) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL256B_SUPPORTED
                ignore_bins impossible_vl_legal_lmul4 = binsof(cp_csr_vtype_lmul_egs8_sew32.four) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
        `ifdef ZVL32B_SUPPORTED
            `ifndef ZVL64B_SUPPORTED
                ignore_bins vleight_eq_vlmax_lmul8 = binsof(cp_csr_vtype_lmul_egs8_sew32.eight) && binsof(cp_csr_vl_edges_egs8.vlmax);
            `endif
            `ifndef ZVL128B_SUPPORTED
                ignore_bins impossible_vl_legal_lmul8 = binsof(cp_csr_vtype_lmul_egs8_sew32.eight) && binsof(cp_csr_vl_edges_egs8.vl_legal);
            `endif
        `endif
    }

    //////////////////////////////////////////////////////////////////////////////////

    //// end cr_vl_lmul_egs8_sew32 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vs2_vs1_edges_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cr_vs2_vs1_edges_egs8 : cross cp_vs2_edges_egs8, cp_vs1_edges_egs8  iff (ins.trap == 0 )  {
        // Cross coverage of VS2 edges and VS1 edges (EGS=8)
    }

    //// end cr_vs2_vs1_edges_egs8 ////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////////////
    // cr_vtype_agnostic_egs8
    //////////////////////////////////////////////////////////////////////////////////

    cp_csr_vtype_vta_egs8 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vta")  iff (ins.trap == 0)  {
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    cp_csr_vtype_vma_egs8 : coverpoint get_csr_val(ins.hart, ins.issue, `SAMPLE_BEFORE, "vtype", "vma")  iff (ins.trap == 0)  {
        bins undisturbed = {0};
        bins agnostic    = {1};
    }

    mask_enabled_agnostic_egs8: coverpoint ins.current.insn[25] {
        bins enabled = {1'b1};
    }

    cr_vtype_agnostic_egs8 : cross cp_csr_vtype_vta_egs8, cp_csr_vtype_vma_egs8, mask_enabled_agnostic_egs8  iff (ins.trap == 0)  {
        // Cross coverage of vector tail and mask agnostic behaviors (EGS=8)
    }

    //// end cr_vtype_agnostic_egs8 ////////////////////////////////////////////////

endgroup
// ---------------------
function void zvksh_sample(int hart, int issue, ins_t ins);
    // Want to sample only if the SEW matches the target SEW of the file, some tests require
    // testing when vill is set, if vill=1 all other vtype bits are set to 0 so there is no
    // associated sew with these tests
    if (get_csr_val(hart, issue, `SAMPLE_BEFORE, "vtype", "vsew") == 2 ||
        get_csr_val(hart, issue, `SAMPLE_BEFORE, "vtype", "vill") == 1) begin
        case (traceDataQ[hart][issue][0].inst_name)
        "vsm3c.vi"     : begin
            Zvksh_vsm3c_vi_cg.sample(ins);
        end
        "vsm3me.vv"     : begin
            Zvksh_vsm3me_vv_cg.sample(ins);
        end
        endcase
    end
endfunction
