name: cv32e40s-rv32imc-pma
compiler_exe: riscv64-unknown-elf-gcc
objdump_exe: riscv64-unknown-elf-objdump
ref_model_exe: sail_riscv_sim
udb_config: cv32e40s-rv32imc-pma.yaml
linker_script: link.ld
dut_include_dir: .
