name: cv32a65x
compiler_exe: riscv64-unknown-elf-gcc # executable name on $PATH or full path to executable
objdump_exe: riscv64-unknown-elf-objdump # executable name on $PATH or full path to executable, optional
ref_model_exe: sail_riscv_sim
udb_config: cv32a65x.yaml
linker_script: link.ld
dut_include_dir: . # Directory containing DUT specific rvmodel_macros.h header
